### ISSUE TITLE
Add a method to slice gtab using bvals (Eg : gtab[bvals>200])

### ISSUE THREAD

**Issue by quantshah** [dipy/dipy#1073]
A way to slice gradient tables to get bvals and bvecs according to a specific condition should be useful. For example :  

``` python
gtab[bvals > 200]
```

Should give me a gradient table with bvals and bvecs greater than 200. Similarly perhaps a mask in the data can be useful.

``` python
data[bvals > 200]
```

Refer to Pandas DataFrames : http://pandas.pydata.org/pandas-docs/version/0.15.2/indexing.html#boolean-indexing

Will a feature like that be of any general use ? In general, do researchers need to split data according to bvalues.

@arokem @Garyfallidis

**Comment by arokem** [comment]
Hey @sahmed95 : nice one. Just as side note about issues/PRs: no need to tag me and Eleftherios on every single one of these. We get an email about these by virtue of the fact that we are "watching" the repo (that's the button at the top of this page). Besides, there are many other contributors who could comment here (please do!), and we don't want them to feel like this only a conversation with three participants... End of this rant. keep up the good work!

**Comment by arokem** [comment]
Concerning details: 

I think this is a good idea. I think this could be done by implementing the `__getitem__` method for the `GradientTable` object. It would take an indexing variable, and return a GradientTable with that indexing variable applied to the bvals and bvecs separately:

   return GradientTable(self.bvals[idx], self.bvecs[idx])

But I might be missing something. Does this correspond to other peoples' intuitions about what should be returned from an indexing operation on a `GradientTable`?

**Comment by sahmed95** [comment]
Cool. I didn't know that. Looking forward to comments from everyone. If this feature is useful, we should certainly implement it. From my experience with Pandas DataFrame, slicing is a neat way to analyze parts of a large dataset if one wants to play around.

**Comment by sahmed95** [comment]
Regarding the indexing operation : I was thinking of stuff like ```python gtab[200 < bvals < 600] ``` or gtab[ bvectors pointing to a certain direction] . 

Another important part of this will be applying the same mask to the data. If we extract a particular set of bvalues we should get the corresponding image data too.

**Comment by arokem** [comment]
The latter can be achieved by doing:

    data[..., gtab.bvals > threshold]

and similar. Did you have another API in mind?

**Comment by sahmed95** [comment]
Oh, yes that'd work. I guess it's better not to add anything new and keep things simple. I was looking for a way to get data in between bvalues and found that numpy arrays can already be sliced like that. Using

```data[(data < 1000) & (data>200)] ```

So, no need for a new API I guess. Implementing __get__item should be enough with options for < b0, > b0, b1 < x < b2, and perhaps at a single bvalue. ```gtab[bval == 100]```

**Comment by riddhishb** [comment]
@sahmed95 I think this is a nice idea. If this is being implemented, what I believe a useful next step would be is to have an attribute of number of shells (especially for big datas like HCP) to the gtab. I think currently we have to open the bval file and see, but if it was included in the gtab.info or have a separate attribute it would be cool.

**Comment by shilpiprd** [comment]
HI! I'm interested in working on this feature. 
If i do implement the get_item function, I'll put it in dipy/core/gradients.py file as in that file, the calss GradientTable(object) method already exists. 
Thanks in advance!

**Comment by shilpiprd** [comment]
I made changes to the file and created a PR : #2749 
Please review it.
