### ISSUE TITLE
script path can not be found on OSX 

### ISSUE THREAD

**Issue by skoudoro** [dipy/dipy#1256]
After running the command "pip install --user -e ." on my dipy folder, I can found dipy executable on my home folder (.local/bin) but unfornatunatly I can not execute them outside of that folder. 

Is it normal ? Any idea how to resolve it  @matthew-brett @jchoude @arokem ? Should I add this path on my .bashrc file ? Shouldn't setup.py do that automagically? 

ps: env = OS X 10.11 - anaconda - python 3.6

**Comment by matthew-brett** [comment]
Right - if you do a user install, the executables go to that directory - actually in my case, on OSX, it's `$HOME/Library/Python/3.5/bin`.

I use something like this in my `.bash_profile` file to do that:

```
# Add the standard --user executable path
# Only expecting this to work on Unices (maybe including Cygwin)
export PATH="$(python -c 'import site; print(site.USER_BASE + "/bin")'):$PATH"
```

**Comment by skoudoro** [comment]
For information : https://github.com/pypa/pip/issues/3813

Thanks for this tip. It will be good to add this note on the documentation. I will make a PR for this later.

**Comment by skoudoro** [comment]
it seems to be solve now, closing
