### ISSUE TITLE
Questions/policies about writing .rst/web doc files

### ISSUE THREAD

**Issue by jhlegarreta** [dipy/dipy#1305]
I've been revising the doc on the webpage, and besides having done some PRs to fix some typos or cross-refs, I've detected a number of discrepancies that I'd like to fix if you think we should.

I'm well aware that these are minor, style issues, but I feel that sticking to a set of rules may benefit readers.

- The markdown for objects is double inverted commas (`` ``) or italics?
Inverted commas:  http://nipy.org/dipy/examples_built/gradients_spheres.html#example-gradients-spheres
vs.
Italics: http://nipy.org/dipy/examples_built/segment_quickbundles.html#example-segment-quickbundles

or
http://nipy.org/dipy/examples_built/reconst_csa.html#example-reconst-csa
See `np.clip` vs. `Peaks_from_model`

Are there any criteria to favor one over the other, or to use each under given circumstances? Features vs. methods vs. classes vs. modules vs. variable names?

- Which is the right case to write dipy? Always **dipy**? **Dipy** when at the beginning of a sentence and dipy for the rest? **DIPY**?

- Should we link dipy across the documentation?

- References should be numbered or the NameYear convention is preferred?

- Should we use `b0` (more commonly used across the .rst files) or `B0` (http://nipy.org/dipy/examples_built/syn_registration_2d.html#example-syn-registration-2d)?

Should we use double or simple quotes when referring to a filename, or other special name?
e.g. _(...) ”.trk” file we’ll need to move them to “trackvis space”, or the representation of streamlines specified by the trackvis Track File format_.

e.g.
_Each tissue classifier determines if the stopping is ‘valid’ or ‘invalid’. A streamline is ‘valid’ when the tissue classifier determines if the streamline stops in a position classified as ‘ENDPOINT’ or ‘OUTSIDEIMAGE’._

- Should we write **3D** or **3d**?

- Should we use uppercase for acronyms always and capitalized the first letters of the long names?
e.g.
`Constrained Spherical Deconvolution (CSD)`
vs.
`fractional anisotropy (FA)`

May be we could have a set of reduced rules (and make this into another .rst file) so that writing the .rst files is more consistent. We're safe on the code thanks to PEP8, but the criteria in .rst files may need to be made consistent.

BTW, the file `b_and_q.rst` seems not be being rendered or linked from anywhere.

I've got a bunch of changes or typos that I've detect in .rst files. I'm holding to submit a patch set; if these questions get hopefully answered I can submit all changes  in one topic/patch set.

**Comment by dmreagan** [comment]
Perhaps a tool like [this reStructuredText linter](https://github.com/twolfson/restructuredtext-lint) could help keep the docs in line?

**Comment by skoudoro** [comment]
> I've been revising the doc on the webpage, and besides having done some PRs to fix some typos or cross-refs, I've detected a number of discrepancies that I'd like to fix if you think we should.

Thank you for doing this !

> The markdown for objects is double inverted commas () or italics?

inverted commas

> Which is the right case to write dipy? Always dipy? Dipy when at the beginning of a sentence and dipy for the rest? DIPY?

I prefer DiPy but it is never written like this :-). We should ask @Garyfallidis @arokem 

> Should we link dipy across the documentation ?

it would be nice, but harder to maintain. What do you think @Garyfallidis ?

> Should we use b0 (more commonly used across the .rst files) or B0

b0

> Should we write 3D or 3d?

3D

> Should we use uppercase for acronyms always and capitalized the first letters of the long names?

I think so

> May be we could have a set of reduced rules (and make this into another .rst file) so that writing the .rst files is more consistent. We're safe on the code thanks to PEP8, but the criteria in .rst files may need to be made consistent.

I agree, it can be a new .rst file on _dipy/doc/devel_. You can start a file on your PR

**Comment by arokem** [comment]
Thanks both!

On Wed, Jul 19, 2017 at 6:42 AM, Serge Koudoro <notifications@github.com>
wrote:

> I've been revising the doc on the webpage, and besides having done some
> PRs to fix some typos or cross-refs, I've detected a number of
> discrepancies that I'd like to fix if you think we should.
>
> Thank you for doing this !
>
> The markdown for objects is double inverted commas () or italics?
>
> inverted commas
>
> Which is the right case to write dipy? Always dipy? Dipy when at the
> beginning of a sentence and dipy for the rest? DIPY?
>
> I prefer DiPy but it is never written like this :-). We should ask
> @Garyfallidis <https://github.com/garyfallidis> @arokem
> <https://github.com/arokem>
>

I like Dipy wherever we mention this in text (like "Python"), and of course
`dipy` in code. I prefer not to use DIPY or DiPy.

Should we link dipy across the documentation ?

**Comment by jhlegarreta** [comment]
@arokem @skoudoro @dmreagan Thanks for the input ! I'll try to do a PR over the next few days with these changes.

@dmreagan I did not know the tool, but I like it as another step towards generating better documentation. I ignore what others think, though.

**Comment by arokem** [comment]
That would be a great contribution - the docs could definitely use some love. Thanks @jhlegarreta!

**Comment by Garyfallidis** [comment]
Hi all,

In the code it should be dipy and in the documentation and papers it should be DIPY.

![image](https://user-images.githubusercontent.com/134276/28544052-e9c99c6c-708f-11e7-8297-a31d938e3cff.png)

**Comment by Garyfallidis** [comment]
I found that especially in papers dipy with small letters is very small. It looks hidden if next to other software. So, in all my last papers I am using DIPY. Also our logo is with capital letters for some years now. Finally, DIPY means Diffusion Imaging in PYthon so having it with capital letters kind of makes sense for the English teachers too. I hope you find those explanations reasonable.

@jhlegarreta I think it would be amazing if you can help us standardize the website and docs. Thank you for writing this issue.

**Comment by skoudoro** [comment]
What is the status of this @jhlegarreta ? Can I help you ? we can work together on this PR and split the task. Just let me know ! Thanks !

**Comment by jhlegarreta** [comment]
@skoudoro Thanks for keeping an eye and for the offer; still WIP. Sorry for the lag. A feasible estimate for a PR is next week. For the fixes in the existing rst files I think I'll be able to handle them, revisions will be more than welcome. I'll probably need help or guidance to locate in the appropriate place the guidelines, or if it is decided that the tool suggested by @dmreagan (interesting at first sight but haven't yet investigated) is to be used across DIPY, then I'll probably ask for help.

**Comment by jhlegarreta** [comment]
A couple of additional questions as I work on this:

- The `..admonition::` directive is present in some files. Looks like it is auto-generated (?) I couldn't find a pattern or explanation. Is it auto-generated to warn about some missing stuff? 
Is it related to the formatting of the bottom message where the example source code is linked?
http://nipy.org/dipy/examples_built/reconst_csa.html#example-reconst-csa
vs.
http://nipy.org/dipy/examples_built/reconst_csd.html#example-reconst-csd
vs.
http://nipy.org/dipy/examples_built/segment_quickbundles.html#example-segment-quickbundles

- Do we need to include the filename at the top as in
`examples/reconst-csd.py`
?

- Do we prefer to list references with _numbers_ or as _AuthorYear_:
http://nipy.org/dipy/examples_built/gradients_spheres.html#example-gradients-spheres
vs.
http://nipy.org/dipy/examples_built/reconst_csd.html#example-reconst-csd

While I like the latter for it points directly the author, the indentation is uneven, and that makes the rendering less nice.

**Comment by skoudoro** [comment]
> The ..admonition:: directive is present in some files. Looks like it is auto-generated (?) I couldn't find a pattern or explanation. Is it auto-generated to warn about some missing stuff?

It is generated by us. you can see and edit [here](https://github.com/nipy/dipy/blob/master/tools/ex2rst#L180). It is strange that it is not generated correctly sometimes. 

> Do we need to include the filename at the top as in `examples/reconst-csd.py` ?

No idea and I do not know why we would do this. any idea @arokem @Garyfallidis ?

> Do we prefer to list references with numbers or as AuthorYear

AuthorYear despite the uneven indentation. It will be wonderful if you know how to fix that. Specialy [here](http://nipy.org/dipy/examples_built/reconst_shore.html#example-reconst-shore) where we do not want number.

Thanks !

**Comment by jhlegarreta** [comment]
Added a style guideline in PR #1316.

**Comment by jhlegarreta** [comment]
A couple of additional stylistic minor questions:
- Should we make captions be boldface?
- Across the website some paths are written as `<./doc/devel`> while others are simply formatted as `doc/devel`. Just a minor detail, but for the sake of consistency, which one should we encourage?

Thanks.

**Comment by skoudoro** [comment]
Hi @jhlegarreta , sorry for the delay. To answer your question : 

> Should we make captions be boldface?

No

> Across the website some paths are written as <./doc/devel> while others are simply formatted as doc/devel

I think we should encourage `doc/level`.  The other syntax should be use for an other purpose

**Comment by jhlegarreta** [comment]
@skoudoro Thanks. Updated the coding style guide, made the corresponding changes to #1316.

Now, the question about cross-referencing objects is open due to a change requested to that topic. Please visit it.

**Comment by jhlegarreta** [comment]
Folks, I think this issue can be closed. There was a PR that tried to address most of the issues.

For the sake of the health of the repository, I would close the issue and open a new one if necessary or if at some point we gather some momentum to address the aspects that were mentioned in the comments (having to do with the use of a documentation linter and making all cross-references consistent and possibly be located in a single place).

Thanks.

**Comment by arokem** [comment]
Thanks! Closing.
