### ISSUE TITLE
How to convert from converted isotropic to original resolution (anisotropic)

### ISSUE THREAD

**Issue by John1231983** [dipy/dipy#1373]
Hello, thanks for your code for converting from anisotropic to isotropic resolution. It really helps for some kind of dataset such as MRBrainS13 (resolution 0.958mm x 0.958mm x 3.0). I was used your code to convert it to 1mmx1mmx1mm 
```
data, affine = reslice(data, affine, zoom, (1., 1., 1.), order)
```

After reslice both raw and ground-truth image, we will work in isotropic resolution. For validation, the result file should have the thick original slice resolution (voxel size: 0.958mm x 0.958mm x 3.0mm), since the ground truth is only available for the thick slice data. How could we convert the isotropic resolution of segmentation result to anisotropic resolution to perform the evaluation? 
I was tried the solution
```
data_recover, affine = reslice(data, affine, zoom, (0.958 ,0.958,3.0), order)
```
But the Mean Square Error between `data` and `data_recover` is so high. Hence, I guess we may have a better way to recover it. Thanks

**Comment by arokem** [comment]
This issue is old (and frankly, upon rereading, I still am not sure I understand what the issue was...), so I am going to close it. Feel free to reopen if this is still an issue for you.
