### ISSUE TITLE
Documentation: how to know which models support multi-shell?

### ISSUE THREAD

**Issue by stefanv** [dipy/dipy#1489]
I was trying to find a list of models that can be fit to multi-shell data.  Is this listed somewhere?  If not, would a table of models and their features be a useful addition to the documentation?

/cc @maryamv

**Comment by skoudoro** [comment]
funny, I had the same question last week. We definitively have to add it to the documentation. For the moment, here the table I did last week @stefanv @maryamv (maybe, it miss some models so it need to be improve):
 @Garyfallidis , Can you check it ?

| Method | Single Shell | Multi-Shell | Cartesian |
| :--- | :---: | :---: | :---: |
| SHORE |  | x |  |
| MAP-MRI              |              | x           |           |
| MAPL                 |              | x           |           |
| DKI - Standard       |              | x           |           |
| DKI - Micro          | ?            | ?           |           |
| DTI (SLS, WLS, NNLS) | x            | x           |           |
| CSD                  | x            |             |           |
| MCSD                 |              | x           |           |
| SDT                  | x            |             |           |
| DSI                  |              |             | x         |
| DSID                 |              |             | x         |
| GQI  - GQI2          |              | x           | x         |
| SFM                  | x            | x           |           |
| Q-BALL               | x            |             |           |
|  CSA  |    x   |             |           |
| Westin CSA | x |             |           |
|  ForeCast | x  |             |           |
|  IVIM  |              |  x  |           |
| ActiveAx  |              |       x      |           |
| Noddi / NoddiX  |              |      x       |           |
|  Ball & Stick    |   x   |    x   |           |

**Comment by arokem** [comment]
I believe that the table above is incorrect in that it works (and does "the right thing") with multi-shell data. But should not to be confused with the CSD multi-shell/multi-tissue model (an implementation of which is languishing over on #1168).

**Comment by scott-trinkle** [comment]
I think "DKI - micro", and "Forecast" are multi-shell, not single-shell. I'm also not finding where "Westin CSA" or "Ball and Stick" are implemented...? Also the "OPDT" model is another implemented single-shell model not listed. 

It would definitely be nice to have all of the models clearly listed in the documentation somewhere, along with the data requirements and citations for each. There are some models that are not in the gallery examples, but are still implemented in dipy/reconst.
