### ISSUE TITLE
Test suite fails with errors regarding the ConvexHull of scipy.spatial.qhull objects

### ISSUE THREAD

**Issue by TheChymera** [dipy/dipy#1531]
## Description
The test suite fails with [this traceback](http://bpaste.net/show/94299dbcd04e) (including build output)

## Way to reproduce
Tests are performed inside the (Portage) build directory with: 

```
cd "${TEST_DIR}"/lib || die
nosetests || die
```

- Python 3.5
- dipy 0.14.0
- dependency version (numpy, scipy, nibabel, h5py, cvxpy, vtk)
    * numpy 1.13.3
    * scipy 1.0.0
    * nibabel 2.1.0
    * h5py 2.7.1
    * cvxpy not installed
    * vtk not installed (are these two even mandatory deps?)

**Comment by skoudoro** [comment]
Thank you for this info @TheChymera. Strange that it did not fail before with our Travis bots. We need to investigate this point too.

> vtk not installed (are these two even mandatory deps?)

No

**Comment by skoudoro** [comment]
We do not have the traceback anymore and the issue does not have enough information on what is failing so closing
