### ISSUE TITLE
dti.py - quantize_evecs - error

### ISSUE THREAD

**Issue by supremi** [dipy/dipy#1552]
I am getting TypeError: 'numpy.float64' object cannot be interpreted as an integer while using quantize_evecs function.

I am passing a evecs as 3x3 array and odf_vertices as get_sphere('symmetric724').vertices

Hence,

max_evecs is an array of 3x1

max_evecs.shape is (3,)

and

max_evecs.shape[:-1] is ()

and so, tup = ()

Now, tup being empty causing the first item of max_evecs.reshape() function to be of float64 object and that is why this error.

But, if it is not empty then its datatype changes to int32 and the function should work fine.

Please tell how can I resolve this issue as my evecs will always be 3x3 array?

![image](https://user-images.githubusercontent.com/33626343/41044554-d064b372-69a6-11e8-8c72-c3914f55eec6.png)

**Comment by arokem** [comment]
I would solve this by adding a singleton dimension to your inputs: 

    arr = arr[:, np.newaxis]

Sorry that it's taken so long to answer this... :-( 

Given how long it's been, I am going to close this issue now, but feel free to reopen if this is still an issue for you.
