### ISSUE TITLE
Fetcher should not be under coverage

### ISSUE THREAD

**Issue by BramshQamar** [dipy/dipy#1646]
Having fetcher under coverage means we have to test every fetcher and download all data files?

**Comment by arokem** [comment]
Yeah. We've tried to avoid doing that, instead testing just that the logic of the fetcher makes sense (see: https://github.com/nipy/dipy/blob/master/dipy/data/tests/test_fetcher.py). Following #1643, I am thinking that maybe one change we might want to introduce is requiring an MD5 hash for all the files, so we don't run into what you were seeing in #1638.

**Comment by skoudoro** [comment]
+1 for removing fetcher from coverage

+1 for requiring an md5 hash for all the files 

Do you want to add this test on #1643 @arokem or can I merge this PR?

**Comment by arokem** [comment]
Let's follow up with another PR for that. You can merge #1643 for now, and let's keep this issue open, so we don't forget to do that.
