### ISSUE TITLE
Question about shm_coeff

### ISSUE THREAD

**Issue by tashrifbillah** [dipy/dipy#1671]
To be able to get shm_coeff from http://nipy.org/dipy/reference/dipy.reconst.html#dipy.reconst.shm.QballModel, do I need to do full sampling like the following:

```
bvals = np.concatenate((bvals, bvals), axis=0)
bvecs = np.concatenate((bvecs,-bvecs), axis=0)
data= np.concatenate((data, data), axis=3)
```

FYI, I am using the following to obtain shm_coeff:
```
gtab = gradient_table(bvals,  bvecs)
shm_order= 8
qb_model = QballModel(gtab, sh_order=shm_order, smooth=0.006)
qb_fit = qb_model.fit(data)
shm_coeff= qb_fit.shm_coeff
```

**Comment by arokem** [comment]
Sorry for slowness here. I don't think that you do, but I might be missing something. 

What makes you think that you need to do this?

**Comment by arokem** [comment]
I believe this question has been answered, and there seems to be no folllow-up here, so I am going to close this for now. Feel free to reopen if you think this needs another look.
