### ISSUE TITLE
Details in aparc-reduced.nii.gz

### ISSUE THREAD

**Issue by YerongLi** [dipy/dipy#1699]
Hi:
 in notes on **aparc-reduced.nii.gz**:
"
The image aparc-reduced.nii.gz, which we load as labels_img, is a modified version of label map
aparc+aseg.mgz created by FreeSurfer. The corpus callosum region is a combination of the FreeSurfer labels 251-255.
The remaining FreeSurfer labels were re-mapped and reduced so that they lie between 0 and 88. To see the FreeSurfer
region, label and name, represented by each value see label_info.txt in ~/.dipy/stanford_hardi.
"
I noticed freesurfer will produce labels ranging from 0 to 2035 in the file **aparc+aseg.mgz**, could anyone share any details in all you obtain this file? (aparc-reduced.nii.gz)

I am curious because **aparc+aseg.mgz** have shape (256, 256, 256), while aparc-reduced.nii.gz has shape (81, 106, 76)

**Comment by arokem** [comment]
The file was resampled to the resolution of the Stanford HARDI DWI data. 

The label information is in the text file mentioned in the notes. It's a straightforward mapping from the original labels in Freesurfer to the "new" labels stored in this file.

Does that answer your question?

**Comment by YerongLi** [comment]
Yes, here are probably last few questions, you answers to them are very helpful, I am ccing @ShreyasFadnavis @wasserth as well in case they are familiar with those:

1.
I noticed that `/.dipy/stanford_hardi/aparc-reduced.nii.gz` has size: **(81, 106, 76)**, while **aparc+aseg.mgz** from freesurfer has size **(256, 256, 256)**, which is in so-called *conformed shape* in freesurfer. 

 - I am wondering in this case, how did you do the mapping? 
 - Does this affect the usage of **utils.connectivity_matrix(...)**? 
     Which is to say in the input of the "connectivity_matrix" do I have to transform the volumetric labels to the original space, so the labels and input T1 volume have same size?

2. In the example we are talking about: http://nipy.org/dipy/examples_built/streamline_tools.html#example-streamline-tools
In generating connectivity matrix:
```
M, grouping = utils.connectivity_matrix(cc_streamlines, labels, affine=affine,
                                        return_mapping=True,
                                        mapping_as_streamlines=True)
M[:3, :] = 0
M[:, :3] = 0
```
I noticed *affine is identity*, but **cc_streamlines** is in Euclidean space wile labels are in voxel space. Could you give me any hint why this is happening?

3. In the mapping infomation file:
```
new label, freesurfef label, freesurfer name
1, 2, "Left-Cerebral-White-Matter"
1, 41, "Right-Cerebral-White-Matter"
1, 77, "WM-hypointensities"
1, 85, "Optic-Chiasm"
1, 1004, "ctx-lh-corpuscallosum"
1, 2004, "ctx-rh-corpuscallosum"
2, 251, "CC_Posterior"
2, 252, "CC_Mid_Posterior"
2, 253, "CC_Central"
2, 254, "CC_Mid_Anterior"
...
```
dipy mapped 98 freesurfer labels to 88 new labels, so what are the rest of the (2035-98) labels? Should I map them to 0?

**Comment by arokem** [comment]
I don't know the answer to these questions without some further digging. Given it's been a while since this question was asked, I am going to close this issue. Feel free to reopen if this is still holding you back.
