### ISSUE TITLE
Font on instructions is small on mac

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#1762]
Expanding with `e` works. No error is raised when I hit `f`. 

This is on a mac laptop.

**Comment by Garyfallidis** [comment]
f shouldn't do anything.

**Comment by arokem** [comment]
Oh darn, the font is so small on my screen that I confused "f" and "r". 

'r' works as advertised. Closing.

**Comment by Garyfallidis** [comment]
I would keep it open. I need to understand why text so small in the mac.

**Comment by Garyfallidis** [comment]
Maybe just change the title.

**Comment by arokem** [comment]
Just did that :-)

**Comment by arokem** [comment]
And reopened!

**Comment by skoudoro** [comment]
is it still a relevant issue @Garyfallidis? Can I close? I suppose that anti-aliasing should help now.
