### ISSUE TITLE
Refactor  dipy/stats/analysis.py

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#1765]
I have a couple of comments about the code from the recently-merged #1755 : 

1. The function called "dti_measures" is not DTI-specific as far as I can tell. If I understand correctly, it does something similar to [`afq_profiles`](https://github.com/nipy/dipy/blob/master/dipy/segment/bundles.py#L711), so maybe we put it in segment.bundles? Or maybe move afq_profiles here? Either way, it needs to have a different name. 

2. The function `bundle_analysis` currently mixes analysis and file I/O. I think that it would be good to separate these things. In general, I think that this function does way too much. It probably needs to be separated into about three different functions: 
    - Bundle extraction
    - Disk extraction and assignments
    - Extracting metrics based on the disks. 
And I/O should be involved in none of these, I think.

3. We also still need an example for this functionality. Maybe something similar to the AFQ example. 

It also looks like there are a few comments in that PR that @Garyfallidis made and were not addressed in the original PR.

**Comment by Garyfallidis** [comment]
Agreed! :)

**Comment by arokem** [comment]
What do you think about point 1? Should we move `afq_profiles` into dipy/stats/analysis.py or vice versa?

**Comment by Garyfallidis** [comment]
Absolutely!

**Comment by arokem** [comment]
Absolutely which? There are two options.

**Comment by Garyfallidis** [comment]
Move it to analysis.py

**Comment by arokem** [comment]
OK. I will do that.

**Comment by arokem** [comment]
Another question I have is about saving things to HDF5. Why HDF5 rather than, say, CSV? The latter might lose us some precision, but is more user-friendly, in that it can be read in excel and more readily shared with others. And it's not like that added precision is necessary with this kind of data, given the SNR.

**Comment by Garyfallidis** [comment]
The problem is that the data are too big for CSV. But we should support output to CSV. So, that people can extract parts or whole.

**Comment by arokem** [comment]
Is it that big because it stores data per streamline per node?

**Comment by Garyfallidis** [comment]
I need to check with @BramshQamar but I think that is one of the reasons. The other one is that it can save the points too for each of the disks.

**Comment by arokem** [comment]
Another thing to think about is using `glob.glob` instead of `os.listdir` [here](https://github.com/nipy/dipy/blob/master/dipy/stats/analysis.py#L206-L212) to avoid issues with other files in these directories (e.g., `.DS_Store` on macs)

**Comment by arokem** [comment]
For 1.0, let's add a warning that this module is still under heavy development and API is likely to change. I will make a PR later today!

**Comment by Garyfallidis** [comment]
Just a reminder here for @BramshQamar and @arokem that we need to

- [ ]  bundles_analytics because it deals with filenames should go to workflows
- [ ]  assignment_profiles and afq_profiles should have options to provide the same number/types of outputs and similar input.
- [ ]  dti_measures should be renamed in a more generic and precise way
- [ ]  check tables of hd5 for consistency across new and afq methods
- [ ] save_hdf5 should go to dipy.io.tables.py
- [ ] raise a warning for large api changes

**Comment by Garyfallidis** [comment]
Addressed in #2088 and #2124.
