### ISSUE TITLE
`c_compress_streamline` keeps identical points when it shouldn't

### ISSUE THREAD

**Issue by jchoude** [dipy/dipy#1805]
## Description
When trying to compress a streamline, if two or more consecutive points are identical, only the first should be kept, and the subsequent points removed. However, currently, `c_compress_streamline` keeps them. 

When computing the offset in `c_dist_to_line`, 2 identical points yield a `nan`. However, currently, there is a check on `nan`, and points are still added.

Does anyone know what other case could yield a `nan` there? Else, we could remove it or change it.

Tagging @MarcCote since he's the last one to change this part of the code.

FA is the ref anat, and an example track is https://www.dropbox.com/s/v2uxq5b0hywhbbh/853.trk?dl=0

[fa.nii.gz](https://github.com/nipy/dipy/files/3073633/fa.nii.gz)

I can fix it, but I wanted to validate the reasoning behind the check.

**Comment by MarcCote** [comment]
If you have the following 2D streamline `[(0,1), (0,20), (0,1)]`, you don't want to remove the second point which is what would happen if we discard on `nan`.

I think the code should be removing two consecutive points that are identical like `[(0,1), (0,1), (0,20)]`, but won't work when you have 2+ identical consecutive points. Do you think that's your case? (I haven't look at your trk yet).

**Comment by jchoude** [comment]
That's indeed my case. The first 11 points are identical.

I see the use for the nan now.

**Comment by MarcCote** [comment]
But there's clearly something we can do in such case like skipping the point if `curr == prev`.

**Comment by jchoude** [comment]
Yes, I was wondering if that would incur too much overhead, but such a simple check is still less time consuming than the norm computations. I'll work on a fix, thanks @MarcCote  :)

**Comment by MarcCote** [comment]
Cool. Tag me, I'll be happy to review it.

**Comment by skoudoro** [comment]
Hi @jchoude,

Do still plan to create a PR concerning this issue/New feature? Can you give us a feedback? 

Thank you!
