### ISSUE TITLE
RF/OPT: Use scipy.optimize instead of dipy.core.sphere.disperse_charges

### ISSUE THREAD

**Issue by ecaruyer** [dipy/dipy#184]
Most methods for optimal single shell and multishell design are based on electrostatic-like energy minimization [1-5]. To that extent, we already have in Dipy two very useful methods: dipy.core.sphere._get_forces and dipy.core.sphere.disperse_charges. I think to begin with, it would be cool to make these functions a bit more versatile so that they can be reused for the implementations of methods in [1-5]. Two major features would be:
1. to generalize repulsion energy from 1/r to 1/r^k, as suggested in [3]
2. to add some weighting matrix, which is the basis of methods in [4, 5]

So the general problem is a constrained optimization problem: the cost function is the potential, the constraints are imposed by the fact that points lie on the surface of the unit sphere. Both the cost function and the constraint have analytical gradient expressions, so I'd suggest using a constrained optimization routine in scipy.optimize. In particular, scipy.optimize.fmin_slsqp has proved useful in my tests.

Backward compatibility with _get_forces is not a problem. Question: Do we need backward compatibility with disperse_charges?

Suggestions welcome! 
1. Jones, D. K., M. A. Horsfield, and A. Simmons. "Optimal strategies for measuring diffusion in anisotropic systems by magnetic resonance imaging." Magn Reson Med 42 (1999).
2. Jansons, Kalvis M., and Daniel C. Alexander. "Persistent angular structure: new insights from diffusion magnetic resonance imaging data." Inverse problems 19.5 (2003): 1031.
3. Papadakis, Nikolaos G., et al. "Minimal gradient encoding for robust estimation of diffusion anisotropy☆." Magnetic resonance imaging 18.6 (2000): 671-679.
4. Cook, Philip A., et al. "Optimal acquisition orders of diffusion‐weighted MRI measurements." Journal of magnetic resonance imaging 25.5 (2007): 1051-1058.
5. Caruyer, Emmanuel, et al. "Design of multishell sampling schemes with uniform coverage in diffusion MRI." Magnetic Resonance in Medicine (2013).

**Comment by theaverageguy** [comment]
I guess this can be closed @arokem

**Comment by arokem** [comment]
You'd think, but I believe this still hasn't been merged.

If anyone wants to make this into a PR, that would be great.

**Comment by jhlegarreta** [comment]
@arokem with some guidance about how to proceed and progress, I guess I could open a PR, since the code is available in @ecaruyer's DIPY fork.

**Comment by jhlegarreta** [comment]
Thanks @arokem. So should we start by adding the methods pointed at the end of `dipy.core.sphere.py`, name `disperse_charges` as `disperse_charges_alt` for example, and then call it from some place or the profiling script to perform the profiling?

**Comment by jhlegarreta** [comment]
OK, so first draft attempt submitted to #1711. We will be able to discuss there then.
