### ISSUE TITLE
Add Dipy to MRI-Hub (ISMRM Reproducible Research Study Group)

### ISSUE THREAD

**Issue by RafaelNH** [dipy/dipy#1848]
The ISMRM Reproducible Research Study Group created a website where researchers can publicise their open-source contribution ([MR-hub](https://ismrm.github.io/mrhub/))
 
Should we submit a Dipy entree?

**Comment by arokem** [comment]
Yes! What information do they need?

**Comment by RafaelNH** [comment]
We only need to follow the steps described in the readme.md of [https://github.com/ISMRM/mrhub](https://github.com/ISMRM/mrhub)

**Comment by skoudoro** [comment]
I just submitted a PR on their repo: https://github.com/ISMRM/mrhub/pull/33.

I will close this PR when it is merged.

**Comment by skoudoro** [comment]
PR merged, Project added, closing this issue. 

Thanks for the notice @RafaelNH
