### ISSUE TITLE
apply transformation to all volumes in a series of DWI (4D)

### ISSUE THREAD

**Issue by snapfinger** [dipy/dipy#1871]
Hi there, say I obtained the transformation after a registration using [tutorial code](http://nipy.org/dipy/examples_built/affine_registration_3d.html). This is done based on two b = 0 volumes (3D). Now I want to apply this transformation to all volumes in the moving DWI (4D), is there a method in dipy that can handle this? I tried `.transform` on the 4D sequence but seems it doesn't broadcast automatically.

**Comment by arokem** [comment]
I would just loop through and apply it one by one

**Comment by arokem** [comment]
I think this question has been answered, so I am going to close this, but feel free to reopen if you have any follow-up questions.
