### ISSUE TITLE
ERROR while import data

### ISSUE THREAD

**Issue by foxet** [dipy/dipy#1873]
![图片](https://user-images.githubusercontent.com/1968438/60170345-d7f20b80-983a-11e9-9ad6-63dbdd6bd806.png)

**Comment by arokem** [comment]
I don't know what this is and how to solve it, but here are some initial clues: 

https://github.com/pytorch/pytorch/issues/2083
https://stackoverflow.com/questions/19268293/matlab-error-cannot-open-with-static-tls

**Comment by skoudoro** [comment]
An old issue that we can not reproduce. For now, I am closing but Feel free to reopen it.
