### ISSUE TITLE
Interesting dataset for linear, planar, spherical encoding

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#1883]
"Linear, planar and spherical tensor-valued diffusion MRI data by free waveform encoding in healthy brain, water, oil and liquid crystals" 

Filip Szczepankiewicz, Scott Hoge, Carl-Fredrik Westin

Data in Brief, in press

https://doi.org/10.1016/j.dib.2019.104208

**Comment by skoudoro** [comment]
superseded by #1991, closing
