### ISSUE TITLE
imaffine mask support

### ISSUE THREAD

**Issue by d-v-b** [dipy/dipy#1969]
## Description
Affine registration doesn't support masked regions. The mutual information metric does appear to have some mask support, but it's not exposed by `AffineRegistration`. Is this on the roadmap?

**Comment by skoudoro** [comment]
Hi @d-v-b, 

Thank you for pointing that, we will try to look into it. Indeed, I saw some mask support and test for the `ParzenJointHistogram` but we need to go deeper and play a bit with it. But feel free to create a PR if you see exactly what needs to be done!

**Comment by d-v-b** [comment]
Hi @skoudoro 
I'm playing around with the code at the moment to try and understand things properly... If I feel like I can get the mask stuff working I will absolutely submit a PR.

**Comment by d-v-b** [comment]
@skoudoro I got the masking working in the `mask` branch of my fork of `dipy`, e.g.: https://github.com/d-v-b/dipy/blob/mask/dipy/align/imaffine.py

Here are the results: the middle blob is moved while the outer 8 blobs remain in place. Aligning without a mask doesn't find the translation of the middle blob, but using a mask to focus the optimization on the central region (colored square) does find that translation. 
![image](https://user-images.githubusercontent.com/3805136/64926185-93866400-d7c8-11e9-9ba2-26d0368e87f9.png)


I next need to put together a proper test for it (maybe the example above can be the test case).

I was pretty aggressive about moving code around in `AffineRegistration`, I'm not sure you will like all my changes. But hopefully we can separate that from the changes related to getting the masking working right.

I'm also interested in benchmarking the timings -- i'm not sure how much (if any) speed benefit will come from masking.

**Comment by skoudoro** [comment]
Good job @d-v-b ! The result look nice! Will look into your code tonight or tomorrow.

Concerning the test, I agree that your example above is a nice test case. Look forward to see your benchmarking results!
