### ISSUE TITLE
Recobundles documentation

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#1973]
I am trying to understand how recobundles performance is affected by changes to parameters, but I am not 100% sure that I understand what the parameters mean and the doc-string is a bit sparse at the moment. For example, what do `model_clust_thr` and `reduction_thr` do? It would be great to flesh this out here: https://github.com/nipy/dipy/blob/master/dipy/segment/bundles.py#L173-L209

**Comment by skoudoro** [comment]
Thank you @arokem for pointing that. I just assigned this to @Garyfallidis, he will give you a more precise answer.

**Comment by skoudoro** [comment]
Hi @BramshQamar,

Can you look at this issue and fix it, please? I know that you have some expérience with reccoBundles. 

Thank you
