### ISSUE TITLE
Documentation not being rendered correctly

### ISSUE THREAD

**Issue by jhlegarreta** [dipy/dipy#1996]
## Description
The documentation of some methods is not being rendered correctly: the variable name and the type are rendered with no space in between: check for example the documentation of
[dipy.align.diffeomorphicregistration](https://dipy.org/documentation/1.0.0./reference/dipy.align/#diffeomorphicregistration)
or
[dipy.core.gradient-table-from-gradient-strength-bvecs](https://dipy.org/documentation/1.0.0./reference/dipy.core/#gradient-table-from-gradient-strength-bvecs)

Virtually documentation of all files show the same issue. Unfortunately I found no method that does not show such a behavior.

## Way to reproduce
Check the online documentation (links above) or generate the documentation the way it is currently generated and check it locally.

## Additional information
Related to [fury issue 122](https://github.com/fury-gl/fury/issues/122)

**Comment by jhlegarreta** [comment]
@skoudoro @Garyfallidis Any insight as to why this is happening?

**Comment by aryanshomray** [comment]
#2086

**Comment by aryanshomray** [comment]
#2086

**Comment by jhlegarreta** [comment]
> #2086

Thanks for doing this @aryanshomray.

Not sure if this is the root cause of the issue described here, though. But it will certainly help in making the docstrings consistent.

**Comment by skoudoro** [comment]
I agree with @jhlegarreta,  I do not think this is the reason but it helps!

**Comment by skoudoro** [comment]
This issue is fixed by https://github.com/dipy/dipy_web/pull/120. Thank you @jhlegarreta for pointing this

**Comment by jhlegarreta** [comment]
Awesome @skoudoro ! Thanks for having fixed it.
