### ISSUE TITLE
Apply deformation map to render "registered" image

### ISSUE THREAD

**Issue by b2jia** [dipy/dipy#2019]
I'm picking up after another researcher's project. Specifically, they used DIPY's symmetric diffeomorphic coregistration tool to extract a deformation map between two co-registered images. From what I understand, deformation maps tell how to "warp" features of one image to another registered image.

Extracting these deformation maps are very clear and easy (ie. get_forward_map). I currently have a set of deformation map and no longer have the latent data. It is not clear given the deformation map how I can warp an image to produce the registered image. Would someone be able to comment/advise? Thank you!

**Comment by arokem** [comment]
Hi! Thanks for posting this question. I think that you might be looking for the `transform` (https://github.com/nipy/dipy/blob/master/dipy/align/imwarp.py#L501) or `transform_inverse` (https://github.com/nipy/dipy/blob/master/dipy/align/imwarp.py#L547) methods of that class.

**Comment by b2jia** [comment]
Thanks @arokem ! I was reading through ```transform_inverse earlier```, and had a difficult time understanding what the method is really doing as many other methods it calls are heavily nested. Is there a paper you could refer me to that explains the algorithm? 

The motivation behind this question is, I am trying to recapitulate what the ```transform_inverse``` in Tensorflow. Another coworker saved the diffeomorphic maps as three separate images (dx, dy, dz), and I am trying to understand how to utilize this information to warp an input image. Thank you so much for your help!

**Comment by arokem** [comment]
Does this example help? https://dipy.org/documentation/1.0.0./examples_built/syn_registration_2d/
Once you have the `mapping` variable, it has `forward` and `backward` arrays that hold your displacements on the 4th dimension. You can also inject these values from your saved images (I have an example of doing something like that [here](https://github.com/yeatmanlab/pyAFQ/blob/master/AFQ/registration.py#L185-L196))

I think that the best reference we have to offer is the Avants paper mentioned in the example, but others can correct me if there's something more detailed to look at.

**Comment by arokem** [comment]
I believe the question has been answered, so I am going to close this. Feel free to reopen if you still have a follow-up.
