### ISSUE TITLE
Group analysis 

### ISSUE THREAD

**Issue by miladseyfi** [dipy/dipy#2048]
Hello dear developers and users 
Is that possible to run group analysis on a bundle specific measurement (like FA) between subjects?

**Comment by skoudoro** [comment]
Hi @miladseyfi,

Thank you for asking. I think @BramshQamar, @Garyfallidis or @arokem are the most appropriate person to answer your question and they will do as soon as they can.

**Comment by arokem** [comment]
Hi @miladseyfi

You have (at least) two options:

1. The `dipy_ba` CLI performs a bundle analytics procedure that uses linear
mixed models to compare groups of subjects.

2. pyAFQ (http://yeatmanlab.github.io/pyAFQ/) is a DIPY spinoff project
that extracts bundle-specific properties (such as FA), but you'll have to
do your own statistical analysis once you have these properties.

Hope that helps!

**Comment by BramshQamar** [comment]
Hi @miladseyfi,

As mentioned by Ariel above, there are two ways you can do group analysis based on bundle specific measurement (like FA). 

'dipy_ba' is our first version and it is still in the research mode. The final version of the bundle analytics 'dipy_ba' should be up in few weeks. 

Bramsh

**Comment by arokem** [comment]
I believe the question has been answered, so I am going to close this. Feel free to reopen if you still have a follow-up.
