### ISSUE TITLE
dipy.tracking.utils.density_map order of arguments changed by mistake

### ISSUE THREAD

**Issue by ilyanelken** [dipy/dipy#2052]
## Description
in dipy.tracking.utils.density_map() the order of arguments was changed by mistake in
commit 7761d5ce26c38cf5f18dccd6c537d07eec4d79b9.
The order of "vol_shape" and "affine" arguments was changed with no special reason.

[If reporting a bug, attach the entire traceback from Python and follow the way to reproduce below]
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example

Original code I had:
dipy.tracking.utils.density_map(streamlines, vol_shape, affine=ref_affine)
Is not working anymore.

**Comment by skoudoro** [comment]
Thank you @ilyanelken for this report.

This change was done in purpose by @frheault and it is a part of the 1.0.0 API change which is not compatible with the 0.16.0. This change brings more consistency across the library. 

More information about the API change: https://dipy.org/documentation/1.0.0./api_changes/#dipy-1-0-changes

Hope it answers your question. Let us know if you have more questions.

**Comment by arokem** [comment]
@ilyanelken: Sorry for the API-breaking changes. We try to avoid these, but sometimes, and especially on major releases, we might do that to introduce improvements to the API going forward. I believe this question has been answered, so I am going to go ahead and close this issue.

**Comment by ilyanelken** [comment]
@skoudoro @arokem Guys, thanks for fast and clear response!
