### ISSUE TITLE
Is dipy.viz supported in Colab or Kaggle Notebooks?

### ISSUE THREAD

**Issue by rahullabs** [dipy/dipy#2061]
## Colab/Kaggle Notebook crashes everytime I run the dipy.viz code from example

I have been going through the examples and everytime there is some kind of interactive visualization, notebook automatically shutdown and resets.

I am trying to run this code:

```
from dipy.viz import window, actor

# Enables/disables interactive visualization
interactive = False

ren = window.Renderer()
ren.SetBackground(1, 1, 1)

ren.add(actor.point(hsph_initial.vertices, window.colors.red,
                    point_radius=0.05))
ren.add(actor.point(hsph_updated.vertices, window.colors.green,
                    point_radius=0.05))

print('Saving illustration as initial_vs_updated.png')
window.record(ren, out_path='initial_vs_updated.png', size=(300, 300))
if interactive:
    window.show(ren)
```

But I keep on getting **Your session crashed for an unknown reason.**

However this code works perfectly in my juypter notebook in my laptop

**Comment by arokem** [comment]
Unfortunately, I don't think that the viz code will work on colab or kaggle notebooks, or any other headless environment (that means an environment where the computer running the code is not connected to a display). 

There might be a way to hack it to work using xvfb (https://en.wikipedia.org/wiki/Xvfb), but I am not sure.

**Comment by skoudoro** [comment]
I confirm what @arokem said and it works with Xvfb on Linux and Windows. Concerning macOS, you will have to do a bit more...
