### ISSUE TITLE
Python has stopped working during import 

### ISSUE THREAD

**Issue by ShubhamShaswat** [dipy/dipy#2070]
## Description
When I tried to import following files in jupyter notebook,The window open with the message "Python has stopped working"

When I do this in the Google Colab it worked fine.So,the error must be due to local configurations.  

```
from dipy.core.gradients import gradient_table
from dipy.data import get_fnames
from dipy.io.image import load_nifti, save_nifti
```  
### System Configuration:

Windows Version : 8.1 64-bit
conda Version : 4.4.10
conda-build version : 2.0.2
python version : 3.5.6.final.0
dipy version : 1.1.1 (Build: pip)
fury version : 0.4.0 (Build: pip)

### Event Properties
```
Log Name:      Application
Source:        Application Error
Date:          3/9/2020 4:47:06 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Lenovo-PC
Description:
Faulting application name: python.exe, version: 3.5.6150.1013, time stamp: 0x5b832238
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x98c
Faulting application start time: 0x01d5f603e2fd5d07
Faulting application path: C:\Users\Shubham\Anaconda3\python.exe
Faulting module path: unknown
Report Id: 81d4f55d-61f7-11ea-8412-54ee752c50d8
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-03-09T11:17:06.000000000Z" />
    <EventRecordID>493596</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Lenovo-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>python.exe</Data>
    <Data>3.5.6150.1013</Data>
    <Data>5b832238</Data>
    <Data>unknown</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>c0000005</Data>
    <Data>0000000000000000</Data>
    <Data>98c</Data>
    <Data>01d5f603e2fd5d07</Data>
    <Data>C:\Users\Shubham\Anaconda3\python.exe</Data>
    <Data>unknown</Data>
    <Data>81d4f55d-61f7-11ea-8412-54ee752c50d8</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by ShrishtiHore** [comment]
I guess you are using Anaconda then this is an issue with configurations. I use Anaconda too. And I used to get the same errors So I had uninstalled Anaconda then installed Miniconda and then installed anaconda through Miniconda. Just try reinstalling python again if does not work then try checking the configurations again and reinstalling Anaconda through Miniconda. It worked for me.

**Comment by ShubhamShaswat** [comment]
Hi @ShrishtiHore,Thanks for the suggestion,I will try that. Do you have any intuition behind this problem.I mean why this is happening,can we identify the configuration which is causing this problem.
Let me know if you have some idea regarding this.

**Comment by ShrishtiHore** [comment]
Honestly No idea But I Kinda had this experience before, Twice to be real ! But both the times it worked for me so I thought maybe it will help you too.

**Comment by skoudoro** [comment]
closing this issue for the moment. We can not reproduce it. Feel free to reopen it
