### ISSUE TITLE
Q-Space Interpolation Methods

### ISSUE THREAD

**Issue by jjbouza** [dipy/dipy#2098]
## Description

Hello,

Are there any functions available for q-space interpolation? 

The motivation is that for an arbitrary non-Cartesian sampling scheme in dMRI it might be desirable to interpolate the q-space signal onto a Cartesian grid to use Cartesian reconstruction methods or to simulate certain undersampling patterns for experiments.  

Linear interpolation is an obvious and easy choice for this, but there are better choices such as sinc interpolation as well (e.g. [see this paper](https://ieeexplore.ieee.org/abstract/document/6132426/) or [this article](https://en.wikipedia.org/wiki/Lanczos_resampling)), Sinc interpolation is "optimal" in the sense that it allows perfect reconstruction for band-limited signals, which in the context of q-space interpolation means that the EAP P(r) has compact support.

**Comment by StongeEtienne** [comment]
I'm not an expert on this, and sorry for the late answer,
Dipy use numpy/scipy interpolation, and could use "more advance" cubic / spline  interplation.
I think for DSI with a grid/ cartesian acquisition of que Q-space, there is a  "map_coordinates" and "spline filter".
https://github.com/dipy/dipy/blob/master/dipy/reconst/dsi.py

However, I did not see an implementation specificly using sinc.
