### ISSUE TITLE
PNG images saved by window.record in the tutorial example are always black

### ISSUE THREAD

**Issue by ruizengalways** [dipy/dipy#2107]
## Description
In the tutorial [Reconstruction with Constrained Spherical Deconvolution](https://dipy.org/documentation/1.1.1./examples_built/reconst_csd/#example-reconst-csd)

I run the following code snippet:

```python
import numpy as np

from dipy.core.gradients import gradient_table
from dipy.data import get_fnames, default_sphere
from dipy.io.gradients import read_bvals_bvecs
from dipy.io.image import load_nifti

hardi_fname, hardi_bval_fname, hardi_bvec_fname = get_fnames('stanford_hardi')

data, affine = load_nifti(hardi_fname)

bvals, bvecs = read_bvals_bvecs(hardi_bval_fname, hardi_bvec_fname)
gtab = gradient_table(bvals, bvecs)

from dipy.reconst.csdeconv import auto_response

response, ratio = auto_response(gtab, data, roi_radius=10, fa_thr=0.7)

from dipy.viz import window, actor
from dipy.sims.voxel import single_tensor_odf

interactive = True
ren = window.Renderer()
evals = response[0]
evecs = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]]).T


response_odf = single_tensor_odf(default_sphere.vertices, evals, evecs)

response_odf = response_odf[None, None, None, :]
response_actor = actor.odf_slicer(response_odf, sphere=default_sphere,
                                  colormap='blues')
ren.add(response_actor)
print('Saving illustration as csd_response.png')
window.record(ren, out_path='csd_response.png', size=(200, 200))
if interactive:
    window.show(ren)
```

The saved image 'csd_response.png' is always black. I checked it using PIL.Image. It shows me that all pixels in this image are filled by zero.

- [ ] Operating system and Python Packages version 
Ubuntu 18.04
dipy                      1.1.1                    pypi_0    pypi       
vtk                       8.2.0           py38h1e82295_211    conda-forge
fury                      0.4.0                      py_0    conda-forge
python                    3.8.2                hcf32534_0
nibabel                   3.0.2                    pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
umpy                     1.18.1           py38h4f9e942_0
numpy-base                1.18.1           py38hde5b4d6_1
scipy                     1.4.1            py38h0b6359f_0

**Comment by sidkapoor97** [comment]
Try changing  
`response_actor = actor.odf_slicer(response_odf, sphere=default_sphere,
                                  colormap='blues')` in your code to 
`response_actor = actor.odf_slicer(response_odf, sphere=default_sphere,
                                  colormap='plasma')`

for documentation on dipy.viz you can go to https://dipy.org/documentation/1.1.1./reference/dipy.viz/

**Comment by skoudoro** [comment]
fixed by [FURY](https://github.com/fury-gl/fury). closing
