### ISSUE TITLE
Independent section on Fiber tracking evaluation not necessary

### ISSUE THREAD

**Issue by Garyfallidis** [dipy/dipy#2115]
We have a section on tracking evaluation with a single tutorial. We can move this tutorial back to the original fiber tracking section there is no need for an independent section just for one tutorial.
See here https://dipy.org/tutorials/

**Comment by arokem** [comment]
👍 sounds good!

**Comment by skoudoro** [comment]
Hi @areeshatariq,

Can you fix this issue? Thank you!

**Comment by skoudoro** [comment]
Just a quick reminder @areeshatariq. It would be good to have PR soon. Thank you!
