### ISSUE TITLE
RecoBundles workflow still using old API

### ISSUE THREAD

**Issue by BramshQamar** [dipy/dipy#2117]
RecoBundles workflow is still using old API for reading and saving .trk files.
Needs to be changed from 
`nib.streamlines.load` to `load_tractogram`
`nib.streamlines.Tractogram` to  `StatefulTractogram`
`nib.streamlines.save` to `save_tractogram`

I will make a PR with the fixes later. Keeping it an open issue here so we don't forget about it.

Bramsh

**Comment by sidkapoor97** [comment]
Updated API for RecoBundles
