### ISSUE TITLE
Local namespace of Scipy is same as a variable name

### ISSUE THREAD

**Issue by ShubhamShaswat** [dipy/dipy#2118]
In [test_imaffine.py](https://github.com/dipy/dipy/blob/4bd3d7035d7eb14596ef47800cfc4a285139f103/dipy/align/tests/test_imaffine.py),

Line 2 : `import scipy as sp`
Line 48 : ` sp = vf.create_sphere.....`

The both have same local name `sp`,but the `scipy` library was never used .
should we change the variable names to something like `sp_` or leave it?

**Comment by sidkapoor97** [comment]
changing `sp` to `sp_` would be better to avoid confusion

**Comment by ShubhamShaswat** [comment]
Thanks @sidkapoor97 for reply, Let's wait for what others have to say.Meanwhile if you would like,you can look at other issues and PRs such as in #2113, the azure pipeline keeps failing.

**Comment by skoudoro** [comment]
Thank you for catching that! we should:
- remove it if the import is not used
- rename the local name to be more explicit

**Comment by ShubhamShaswat** [comment]
Thanks @skoudoro , based on suggestion should I open a PR with:

-  rename `sp` to `sph`
- leave import as it is may it will be required in future tests
