### ISSUE TITLE
dipy / fury fails to install on Ubuntu 18 with pip3

### ISSUE THREAD

**Issue by soichih** [dipy/dipy#2126]
I am trying to install dipy / fury on fresh Ubuntu16 image. When I run the following command

```
$ pip3 install --upgrade dipy fury joblib pandas nibabel
```

I ran into the following error message.

```
 ---> Running in 9e4e6ad4dd3d
Collecting dipy
  Downloading https://files.pythonhosted.org/packages/06/a8/eab34dfa1a10aa4937c260cbe94a804a97c30e7486d4fffefab242eb76d8/dipy-1.1.1-cp35-cp35m-manylinux1_x86_64.whl (8.0MB)
Collecting fury
  Downloading https://files.pythonhosted.org/packages/f8/4b/a6301a3e7a12ca20c93af2ecadf34c37069c3fcc2cbd34ae0535d9e97b76/fury-0.5.1-py3-none-any.whl (245kB)
Requirement already up-to-date: joblib in /usr/local/lib/python3.5/dist-packages
Collecting pandas
  Downloading https://files.pythonhosted.org/packages/2f/79/f236ab1cfde94bac03d7b58f3f2ab0b1cc71d6a8bda3b25ce370a9fe4ab1/pandas-1.0.3.tar.gz (5.0MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0zj486z3/pandas/setup.py", line 42
        f"numpy >= {min_numpy_ver}",
                                  ^
    SyntaxError: invalid syntax
    
```

Here is the Dockerfile that I am running

```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y python3-pip
RUN apt-get install -y xvfb x11-xkb-utils
RUN apt-get install -y xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic

RUN pip3 install vtk numpy cython scipy h5py nibabel nipype
RUN pip3 install cvxpy scikit-learn
RUN pip3 install --upgrade dipy fury joblib pandas nibabel

RUN pip3 install xvfbwrapper

ENV PYTHONNOUSERSITE=true

#https://wiki.ubuntu.com/DashAsBinSh
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

```

This works perfectly with ubuntu:18.04, however. I am trying to build it with Ubuntu 16 as it does not require the latest kernel/glibs (like Karst)

**Comment by skoudoro** [comment]
Hi @soichih,

I do not understand this line: ` f"numpy >= {min_numpy_ver}",`

f-strings are available only for python 3.6+.  We do not have that on our repo so I wonder what happens ? Why this `f` is added.   I supposed the default python3  version on ubuntu 16 is python3.5

**Comment by skoudoro** [comment]
It seems to be a pandas issue and not a DIPY issue @soichih. Can you install them individually to confirm. Thank you

**Comment by soichih** [comment]
I've installed pandas via apt and now it's working. I believe something is wrong with pip version of pandas.

**Comment by skoudoro** [comment]
great ! so I'm closing this issue.

**Comment by matthew-brett** [comment]
@soichih - I agree - I think the problem must be that Pandas now depends on Python >= 3.6, and so doesn't have a wheel for Python 3.5, and so pip has to run `setup.py` to discover its dependencies, which fails on Python 3.5 because the `setup.py` uses f-strings, which only appeared in 3.6.

Would you consider reporting this bug to the Pandas issues?   If I were them, I'd remove the use of f-strings from `setup.py` so you get a better error message.
