### ISSUE TITLE
Checking empty Cluster objects generates NumPy warning

### ISSUE THREAD

**Issue by jhlegarreta** [dipy/dipy#2130]
## Description
When running the [test_clustering](https://github.com/dipy/dipy/blob/master/dipy/segment/tests/test_clustering.py) suite, a number of warnings are generated due to NumPy checking the truth value of an empty array:
```
DeprecationWarning: The truth value of an empty array is ambiguous.
Returning False, but in future this will result in an error. Use `array.size > 0` to check
that an array is not empty.
```
triggered at
https://github.com/numpy/numpy/blob/master/numpy/testing/_private/utils.py#L395
and stemming from
https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/number.c#L842

## Way to reproduce
Test the `test_clustering` suite. No input data required.

See for example
https://dev.azure.com/dipy/46625eaf-7255-4a2c-9e92-befcdbdca2a8/_apis/build/builds/293/logs/263

A method of the test set where this is seen is `test_cluster_attributes_and_constructor`, where empty clusters are created.

On a side note, but still related to creating empty clusters, in `test_cluster_map_comparison_with_object` the first [cluster that is created](https://github.com/dipy/dipy/blob/master/dipy/segment/tests/test_clustering.py#L537) is empty when the index is 0 because there is no range to account for. Not sure if that is an intended behavior.

Not sure about the specific dependency versions or python versions that trigger the warning. Although the deprecation note in NumPy is 3 years old, reproducing it locally is still elusive to me.

Using [assert_arrays_equal](https://github.com/dipy/dipy/blob/master/dipy/testing/__init__.py#L41) avoids comparing empty arrays (even when one of the two is empty) but returns `None`, so no effective comparison takes place (not sure if that case should be covered in `assert_arrays_equal` regardless of whether its use is appropriate for the current issue). Also, not sure how that would avoid the case of the mentioned side note, where one of the clusters is an empty list.

Suggestions are welcome.

**Comment by skoudoro** [comment]
same comment as #2131 et #2132

**Comment by jhlegarreta** [comment]
> same comment as #2131 et #2132

Yes, they seem to be related. They open up a side issue as to whether empty clusters were intended or their expected behavior.
