### ISSUE TITLE
Elementwise comparison failure warning in multi_voxel test

### ISSUE THREAD

**Issue by jhlegarreta** [dipy/dipy#2131]
## Description
When running the [test_multi_voxel](https://github.com/dipy/dipy/blob/master/dipy/reconst/tests/test_multi_voxel.py) suite, NumPy generates some warnings:
```
DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
```
triggered at
https://github.com/numpy/numpy/blob/master/numpy/testing/_private/utils.py#L395
and stemming from
https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/arrayobject.c#L1317

## Way to reproduce
Test the [`test_squash`](https://github.com/dipy/dipy/blob/master/dipy/reconst/tests/test_multi_voxel.py#L11) method in the `test_multi_voxel` suite. No input data required.

Not sure about the specific NumPy testing assert statements that triggers this.

See for example
https://dev.azure.com/dipy/46625eaf-7255-4a2c-9e92-befcdbdca2a8/_apis/build/builds/293/logs/263

Not sure about the specific dependency versions or python versions that trigger the warning. Although the deprecation note in NumPy is 3 years old, reproducing it locally is still elusive to me.

Not sure if using [assert_arrays_equal](https://github.com/dipy/dipy/blob/master/dipy/testing/__init__.py#L41) applies here.

Suggestions are welcome.

**Comment by skoudoro** [comment]
Thank you for this report. 

Unfortunately, I can not reproduce this error and the log file does not give us the libraries' versions. I need to find another log file to get more information. I suppose the probleme is the same at #2132
