### ISSUE TITLE
Generating ndarrays with different shapes generates NumPy warning at testing

### ISSUE THREAD

**Issue by jhlegarreta** [dipy/dipy#2132]
## Description
When running the [test_clustering](https://github.com/dipy/dipy/blob/master/dipy/segment/tests/test_clustering.py) suite, a number of warnings are generated due to NumPy testing methods needing to create arrays inferring their data type:
```
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences
(which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes)
is deprecated.
If you meant to do this, you must specify 'dtype=object' when creating the ndarray
```
triggered at
https://github.com/numpy/numpy/blob/master/numpy/testing/_private/utils.py#L703
and explained [here](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html).

## Way to reproduce
Test the `test_clustering` suite. No input data required.

The methods where this warning is triggered are
```
test_cluster_map_getitem()
test_cluster_map_comparison_with_object()
```

See for example
https://travis-ci.org/github/dipy/dipy/jobs/676101427#L5543

Not sure about the specific dependency versions or python versions that trigger the warning. `NEP 34` was filed/created on 2019-10-10. Reproducing it locally is still elusive to me.

Looks like for the `test_cluster_map_getitem()` method the warning is triggered only once. There are multiple calls to `assert_equal` and [`assert_arrays_equal`](https://github.com/dipy/dipy/blob/master/dipy/testing/__init__.py#L41), which in turn calls to `assert_array_equal`. Maybe the warning is triggered for the cluster that is empty (i.e. the first one) (?), since otherwise the arrays that the NumPy testing statement needs to create have the same length.

Could be loosely related to #2130.

Suggestions are welcome.

**Comment by skoudoro** [comment]
Thank you for this report @jhlegarreta!

That is a huge change from Numpy that we need to update and be aware of. I think, this problem is everywhere.

> Not sure about the specific dependency versions or python versions that trigger the warning. NEP 34 was filed/created on 2019-10-10. Reproducing it locally is still elusive to me.

I agree, it is strange but it seems the warning will only appear on Numpy 1.19 as you can see from this [Release Notes](https://numpy.org/devdocs/release/1.19.0-notes.html).
Numpy 1.19 is not released yet

So we need to create an environment with the pre-release of Numpy to fix that locally. I hope it helps.
