### ISSUE TITLE
saving tracts in obj format

### ISSUE THREAD

**Issue by svabhishek29** [dipy/dipy#2169]
hi, i was wondering if dipy provides a way to save tracts that are generated into a format like obj or something?

```
sft = StatefulTractogram(streamlines, hardi_img, Space.RASMM)
save_trk(sft, "tractogram_EuDX.trk", streamlines)
```

i was able to use the code above from the documentation to save it as a .trk file, but this can't loaded into programs like unity. 

is it possible to save it in a format that is readable by programs like unity? or is there a way .trk files can be parsed and rendered in unity other than writing our own custom method?

thanks

**Comment by skoudoro** [comment]
Hi @svabhishek29,

I think [this dipy module](https://github.com/dipy/dipy/blob/master/dipy/io/vtk.py) can help you to do what you want.

you can save streamlines as vtk files by using `save_vtk_streamlines`. However,  you can add an option to save them as `obj`. you can look at the `save_polydata` function for replacing `vtk` extension to `obj`.

Looking forward to your pull request for extending this function!

I hope it helps

**Comment by svabhishek29** [comment]
thanks your suggestion, i was able to save it to ply format which was exactly what i wanted, i have submitted a pull request 

svabhishek29:saving-streamlines-to-VTK,FIB,PLY,STLandXML
