### ISSUE TITLE
fetch_gold_standard_io fetcher failed regularly

### ISSUE THREAD

**Issue by skoudoro** [dipy/dipy#2172]
As you can see on Travis or Azure, `fetch_gold_standard_io` failed really often, too often...

We need to understand why this fetcher fails so often.   

I am not sure if the SSL error on Azure is relevant: 

```
C:\Miniconda\envs\testenv\lib\urllib\request.py:1321: in do_open
    raise URLError(err)
E   urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
```

Do you have an idea @frheault or a specific setup on zenodo?

**Comment by skoudoro** [comment]
FYI, The SSL issue seems to be specific to Windows. no issue with MacOS and Linux.

**Comment by frheault** [comment]
Could it be something related to size?
The total size is 47kb and some files are 2-4kb, is it possible that an operation is taking a millisecond and download is even faster?
On some cluster I/O and download speeds are a problem and download has to be throttled down.
