### ISSUE TITLE
Callable response broken in csd module

### ISSUE THREAD

**Issue by MrBago** [dipy/dipy#218]
I want to help improve test coverage of the csd module. I was looking over the doc-strings and I run into this.

```
    response : tuple or callable
        If tuple, then it should have two elements. The first is the eigen-values as an (3,) ndarray
        and the second is the signal value for the response function without diffusion weighting.
        This is to be able to generate a single fiber synthetic signal. If callable then the function
        should return an ndarray with the all the signal values for the response function. The response
```

In the docs it says the response can be a callable, but this is never test (and I believe it is currently broken) the code looks like maybe the intent was to have the response be data from a single voxel. I just wanted to clarify, do we want to support a callable with no arguments, signal from a single voxel, both, or other?

Thanks

**Comment by skoudoro** [comment]
closing in favor of #314 and #313
