### ISSUE TITLE
Inconsistency in stating references in dti.py

### ISSUE THREAD

**Issue by kushaangupta** [dipy/dipy#2185]
## Description
Inconsistency in stating references

In the docstring of restore_fit_tensor function, there was an inconsistency in the way References were attributed. Everywhere else numeric indices were used as placeholders for References, but here Chang2005 was used.

https://github.com/dipy/dipy/blob/5e4adff8b1d86210a683b84034c18e388914a09e/dipy/reconst/dti.py#L1740

https://github.com/dipy/dipy/blob/5e4adff8b1d86210a683b84034c18e388914a09e/dipy/reconst/dti.py#L1754

https://github.com/dipy/dipy/blob/5e4adff8b1d86210a683b84034c18e388914a09e/dipy/reconst/dti.py#L1773

**Comment by skoudoro** [comment]
Thank you for pointing that @kushaangupta. 

Can you fix it @areeshatariq? Thanks!
