### ISSUE TITLE
Bringing AffineMap and DiffeomorphicMap a little closer together

### ISSUE THREAD

**Issue by 36000** [dipy/dipy#2192]
The AffineMap class has a function transform with argument 'interp' specifying "the type of interpolation to be used":
https://github.com/dipy/dipy/blob/988f2c03fd0bda1f2679fa6a40766fd5d6aa091d/dipy/align/imaffine.py#L362
The DiffeomorphicMap class has a similar function with  a similar argument, but it is labelled 'interpolation':
https://github.com/dipy/dipy/blob/988f2c03fd0bda1f2679fa6a40766fd5d6aa091d/dipy/align/imwarp.py#L500

It would be nice if these arguments had the same name so that I could do something like:
`mapping.transform(roi.get_fdata(), interpolation='linear')`
Without having to know whether mapping is an AffineMap or a DiffeomorphicMap.

**Comment by skoudoro** [comment]
+1 !  Thanks for this feedback @36000. We will start a deprecation cycle on release 1.3 and update this parameter name.
