### ISSUE TITLE
Gradient table message error

### ISSUE THREAD

**Issue by IRISstrasbourg** [dipy/dipy#2201]
Hello,

 New Dipy user, I'm following the tuto 'getting started". I met a problem with gradient_table command line. 
I get this message error: 
>>> gtab = gradient_table(bvals, bvecs, b0_threshold=30, big_delta=0.012)
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/po/anaconda3/lib/python3.8/site-packages/dipy/core/gradients.py", line 441, in gradient_table
    return gradient_table_from_bvals_bvecs(bvals, bvecs, big_delta=big_delta,
  File "/home/po/anaconda3/lib/python3.8/site-packages/dipy/core/gradients.py", line 174, in gradient_table_from_bvals_bvecs
    raise ValueError("The vectors in bvecs should be unit (The tolerance "
ValueError: The vectors in bvecs should be unit (The tolerance can be modified as an input parameter)**

I checked the shape of my bvecs and bvals. They look goods : 
>>> print (bvecs.shape)
(49, 3)
>>> print (bvals.shape)
(49,)

All value in bvecs are ranged between -0.99 and 0.99
Bvalues range between 28 and 1020. 

Someone could tell me what is wrong?
Thank you

**Comment by arokem** [comment]
Hi @IRISstrasbourg : We assume that b-vectors are all unit length and it looks like some of the _vector lengths_ of the bvecs are not close enough to 1. 

Try: 

```
import numpy as np
np.linalg.norm(bvecs, axis=1)  
```

These numbers should all be 1 or very close to 1. If you'd still like to go ahead with these b-vecs (though we recommend you don't! It might affect downstream calculations...), you can set the tolerance as an input to the `gradient_table` function.

**Comment by skoudoro** [comment]
I am closing this issue, feel free to reopen it if your problem is not resolved @IRISstrasbourg
