### ISSUE TITLE
Add error handling in Diffeomorphic map `get_map`

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#2202]
See question and answer on gitter here: https://gitter.im/dipy/dipy?at=5f2bc43f83a82b0f05a383a8

Currently, when you try to run the `get_map` method of a `DiffeomorphicMap` class instance before running `optimize` you get a rather cryptic error. It would be nice if that error instead explained what is going on and what you should do next.

**Comment by arokem** [comment]
Sorry for the cryptic title. Now edited!

**Comment by skoudoro** [comment]
Can you fix it @sarathknv? Thank you.

**Comment by sarathknv** [comment]
Sure, I'll send a PR.
