### ISSUE TITLE
Smooth contour of roi

### ISSUE THREAD

**Issue by yokiqust** [dipy/dipy#2213]
I want to show some smooth contour, i have tried gaussian_filter and scipy.ndimage.zoom, they doesn't work.

**Comment by skoudoro** [comment]
Hi @yokiqust,

This is not a DIPY issue. I will have to close it. I recommend you to ask this question in one of this channel:

- On neurostars: https://neurostars.org/c/neuroquestions/1
- DIPY gitter: https://gitter.im/dipy/dipy
- Neuroimaging mailing list: https://mail.python.org/mailman/listinfo/neuroimaging
