### ISSUE TITLE
problem with fetching stanford data

### ISSUE THREAD

**Issue by vinkirk** [dipy/dipy#2215]
Hi DIPY experts,

I'm having trouble fetching the stanford dataset and get the following error message (please see below).  Any help would be greatly appreciated.

Thanks,

Vinny

---------------------------------------------------------------------------
SSLCertVerificationError                  Traceback (most recent call last)
/home/vinny/miniconda3/lib/python3.7/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1316                 h.request(req.get_method(), req.selector, req.data, headers,
-> 1317                           encode_chunked=req.has_header('Transfer-encoding'))
   1318             except OSError as err: # timeout error

/home/vinny/miniconda3/lib/python3.7/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1243         """Send a complete request to the server."""
-> 1244         self._send_request(method, url, body, headers, encode_chunked)
   1245 

/home/vinny/miniconda3/lib/python3.7/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1289             body = _encode(body, 'body')
-> 1290         self.endheaders(body, encode_chunked=encode_chunked)
   1291 

/home/vinny/miniconda3/lib/python3.7/http/client.py in endheaders(self, message_body, encode_chunked)
   1238             raise CannotSendHeader()
-> 1239         self._send_output(message_body, encode_chunked=encode_chunked)
   1240 

/home/vinny/miniconda3/lib/python3.7/http/client.py in _send_output(self, message_body, encode_chunked)
   1025         del self._buffer[:]
-> 1026         self.send(msg)
   1027 

/home/vinny/miniconda3/lib/python3.7/http/client.py in send(self, data)
    965             if self.auto_open:
--> 966                 self.connect()
    967             else:

/home/vinny/miniconda3/lib/python3.7/http/client.py in connect(self)
   1413             self.sock = self._context.wrap_socket(self.sock,
-> 1414                                                   server_hostname=server_hostname)
   1415 

/home/vinny/miniconda3/lib/python3.7/ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    422             context=self,
--> 423             session=session
    424         )

/home/vinny/miniconda3/lib/python3.7/ssl.py in _create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
    869                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
--> 870                     self.do_handshake()
    871             except (OSError, ValueError):

/home/vinny/miniconda3/lib/python3.7/ssl.py in do_handshake(self, block)
   1138                 self.settimeout(None)
-> 1139             self._sslobj.do_handshake()
   1140         finally:

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
<ipython-input-7-99dffbde21fd> in <module>()
----> 1 fetch_stanford_t1()

/home/vinny/miniconda3/lib/python3.7/site-packages/dipy/data/fetcher.py in fetcher()
    216             files[n] = (baseurl + f, md5_list[i] if
    217                         md5_list is not None else None)
--> 218         fetch_data(files, folder, data_size)
    219 
    220         if msg is not None:

/home/vinny/miniconda3/lib/python3.7/site-packages/dipy/data/fetcher.py in fetch_data(files, folder, data_size)
    165         all_skip = False
    166         _log('Downloading "%s" to %s' % (f, folder))
--> 167         _get_file_data(fullpath, url)
    168         check_md5(fullpath, md5)
    169     if all_skip:

/home/vinny/miniconda3/lib/python3.7/site-packages/dipy/data/fetcher.py in _get_file_data(fname, url)
    115 
    116 def _get_file_data(fname, url):
--> 117     with contextlib.closing(urlopen(url)) as opener:
    118         try:
    119             response_size = opener.headers['content-length']

/home/vinny/miniconda3/lib/python3.7/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

/home/vinny/miniconda3/lib/python3.7/urllib/request.py in open(self, fullurl, data, timeout)
    523             req = meth(req)
    524 
--> 525         response = self._open(req, data)
    526 
    527         # post-process response

/home/vinny/miniconda3/lib/python3.7/urllib/request.py in _open(self, req, data)
    541         protocol = req.type
    542         result = self._call_chain(self.handle_open, protocol, protocol +
--> 543                                   '_open', req)
    544         if result:
    545             return result

/home/vinny/miniconda3/lib/python3.7/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    501         for handler in handlers:
    502             func = getattr(handler, meth_name)
--> 503             result = func(*args)
    504             if result is not None:
    505                 return result

/home/vinny/miniconda3/lib/python3.7/urllib/request.py in https_open(self, req)
   1358         def https_open(self, req):
   1359             return self.do_open(http.client.HTTPSConnection, req,
-> 1360                 context=self._context, check_hostname=self._check_hostname)
   1361 
   1362         https_request = AbstractHTTPHandler.do_request_

/home/vinny/miniconda3/lib/python3.7/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1317                           encode_chunked=req.has_header('Transfer-encoding'))
   1318             except OSError as err: # timeout error
-> 1319                 raise URLError(err)
   1320             r = h.getresponse()
   1321         except:

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)>

**Comment by vinkirk** [comment]
I had to put in the following code to solve this problem...
from dipy.data import fetch_stanford_t1

import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

fetch_stanford_t1()

**Comment by kev1nzh37** [comment]
> 

you 're my hero!!!!
