### ISSUE TITLE
Replace fetcher progress bar with tqdm

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#2219]
Does anyone mind if we replace the progress bar defined here:

https://github.com/dipy/dipy/blob/b0b89bcdd2fa349b8f7fde50287fac3cf35bc845/dipy/data/fetcher.py#L45

with a [tqdm](https://tqdm.github.io/) progress bar? 

The one we are currently using tends to create very long logs, because each iteration generates its own line. I think that tqdm would solve that problem. This would add another dependency, but I think it's pretty light-weight.

**Comment by skoudoro** [comment]
Is tqdm multi-platform? I am ok with that if it is really light. I need to give a look.

**Comment by skoudoro** [comment]
After a deeper look, +1  👍
