### ISSUE TITLE
This should be len(np.unique(gtab.bvals)) - 1 or somesuch

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#2232]
https://github.com/dipy/dipy/blob/e6369b5a45ed3124003f902f664238785cc261aa/dipy/reconst/mcsd.py#L746

**Comment by arokem** [comment]
See #2230

**Comment by skoudoro** [comment]
I think #2233 close this issue. Can you confirm @arokem?

**Comment by arokem** [comment]
Confirmed!
