### ISSUE TITLE
Parallelize gibbs_removal

### ISSUE THREAD

**Issue by j1c** [dipy/dipy#2236]
## Description
`gibbs_removal` in essence does fft on each 2d slice of either a 3d or 4d volume. This particular this line, https://github.com/dipy/dipy/blob/c1c43b4ea71086682a5b408b539274495a9052cb/dipy/denoise/gibbs.py#L290 just loops through each slice sequentially. It should be fairly trivial to parallelize the process via `multiprocessing`.

Of course this can be done at the user level by simply running the function with either 2d or 3d inputs, which is what I am doing, but seems like a good addition to dipy itself.

Thoughts?

**Comment by skoudoro** [comment]
Indeed @j1c, 

Following our calendar, this feature can be integrated for the release 1.5 (in March). However, feel free to give a try if you want it for an earlier release!

Thank you for your feedback.
