### ISSUE TITLE
gibbs_removal overwrites input data when inputting 3-d or 4-d data.

### ISSUE THREAD

**Issue by j1c** [dipy/dipy#2237]
## Description
`gibbs_removal` overwrite input data when inputting 3-d or 4-d data that happens on this line. https://github.com/dipy/dipy/blob/c1c43b4ea71086682a5b408b539274495a9052cb/dipy/denoise/gibbs.py#L291 I doubt this is intentional, but is an easy fix by simply making a copy of the input data in the beginning or creating an empty array to write into.

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example

> import numpy as np
> from dipy.denoise.gibbs import gibbs_removal
> 
> X = np.random.normal(size=(50, 50, 25))
> Y = X.copy()
> _ = gibbs_removal(X)
> np.array_equal(X, Y)
> False

- [ ] Relevant images (if any)
- [x] Operating system and version (run `python -c "import platform; print(platform.platform())"`)
  - Darwin-19.6.0-x86_64-i386-64bit
- [x] Python version (run `python -c "import sys; print("Python", sys.version)"`)
  - Python 3.7.9
- [x] dipy version (run `python -c "import dipy; print(dipy.__version__)"`)
  - Dipy 1.2.0
- [x] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
  - NumPy 1.19.1
  - SciPy 1.5.2
  - Nibabel 3.1.1
  - H5py 2.10.0

**Comment by skoudoro** [comment]
Thanks @j1c!

I see 2 options here:
- We might add an option `inplace` or not. Some people want to save memory and keep this behavior as it is.
- Otherwise, we can just warn (in the documentation) the user to create an image before if they do not want their image to be overwritten.

What do you think @arokem ? others?

**Comment by arokem** [comment]
I think that an `inplace=True` key-word argument would be my preferred
option.

**Comment by j1c** [comment]
Ok I can add an inplace kwarg. 

Looking at the code a bit more, it appears that in the case of 2d input, it will always return a copy. Should I make the inplace behavior consistent for 2d, 3d, and 4d inputs?

**Comment by skoudoro** [comment]
> Looking at the code a bit more, it appears that in the case of 2d input, it will always return a copy. Should I make the inplace behavior consistent for 2d, 3d, and 4d inputs?

yes, Thank you for that!
