### ISSUE TITLE
Unable to visualize data through dipy_horizon 

### ISSUE THREAD

**Issue by areeshatariq** [dipy/dipy#2243]
## Description
Dataset: 
- isbi2013_2shell (Before & After LPCA denoising)
- cfin_multib (After MPPCA denoising)

On visualizing the above-mentioned datasets, dipy_horizon is showing a plain white image

## Way to reproduce
To visualize the dataset, use the following command on CLI:

dipy_horizon absolute_path_to_dataset

Please note the following important information:
- VTK version 9.0.1
- Operating system and version Ubuntu 18.04
- Commit hash 0ab4e903

**Comment by jhlegarreta** [comment]
@areeshatariq Can you please specify the VTK version ?
