### ISSUE TITLE
localpca tau_factor is hard coded to 2.3

### ISSUE THREAD

**Issue by j1c** [dipy/dipy#2251]
## Description
`localpca` will always use 2.3 as `tau_factor` since the line below doesn't reference the input argument. According to the docs, seems like the user should be able to set this.

https://github.com/dipy/dipy/blob/8c4b76d7ece74cb06d24dfaa1ce4f2b4fb274be9/dipy/denoise/localpca.py#L318

**Comment by skoudoro** [comment]
Good catch! Thanks @j1c. addressed in #2252
