### ISSUE TITLE
Trackvis header saved with Dipy (nibabel) is not read  by Matlab or other tools 

### ISSUE THREAD

**Issue by alecrimi** [dipy/dipy#2254]
## Description
I am having issues loading some information from tracts saved by Dipy from Matlab or other things that need certain informations on the header

I use the library nibabel:
```
import nibabel as nib 
from nibabel import trackvis as tv
```

and I save the tracks like this
```
hdr = nib.trackvis.empty_header()
hdr['voxel_size'] = img.get_header().get_zooms()[:3]
hdr['voxel_order'] = 'LAS'
hdr['dim'] = fa.shape
hdr['n_count'] = len(csd_streamlines)
tensor_streamlines_trk = ((sl, None, None) for sl in csd_streamlines)
ten_sl_fname = 'tensor_streamlines_2182_1_b3000.trk'
nib.trackvis.write(ten_sl_fname, tensor_streamlines_trk, hdr, points_space='voxel')
```

one of the missing field which is very important to me is "n_count"
the command `len(csd_streamlines)` produces a real integer number, and it seems stored into hdr['n_count'].
However, when read by [TRK-read in Matlab](https://github.com/johncolby/along-tract-stats/blob/master/trk_read.m) 
it appears empty (set to zero). 

> Subscript indices must either be real positive integers or logicals.

>Error in trk_read_raw (line 56)
>tracks(header.n_count).nPoints = 0;

If I take the same file, first I open it in trackvis and then do the same, the problem is gone. It is like trackvis sort out the issue.

**Comment by skoudoro** [comment]
Hi @alecrimi,

Thank you for the feedback.

Can you tell us your DIPY version and how you save your tracks? Are you using the `StatefulTractogram` and `dipy.io.streamlines.save_tractogram`?

**Comment by skoudoro** [comment]
After a deeper look, it seems to be a Nibabel issue. So I am closing this one and the discussion should continue on the issue https://github.com/nipy/nibabel/issues/959
