### ISSUE TITLE
Visibility of Workflow Tutorials on DIPY website

### ISSUE THREAD

**Issue by BramshQamar** [dipy/dipy#2279]
Hello,

Right now workflow tutorials are hard to find. They are listed under: Documentation -> Manual xyz -> DIPY Workflows Interfaces.

Adding them to tutorials will increase its accessibility as they are also tutorials.

Inside tutorials, we can list workflow tutorials along with its pythonic script tutorials. It will also make it easier for user to decide which one meets their needs.

**Comment by skoudoro** [comment]
Thank you for the feedback @BramshQamar!

website updated, closing
