### ISSUE TITLE
Black Output for pam5 file with dipy_horizon

### ISSUE THREAD

**Issue by areeshatariq** [dipy/dipy#2281]
## Description
Dataset:
- stanford_hardi
- cfin_multib

Methods:
- dipy_fit_dki
- dipy_fit_csa
- dipy_fit_csd

Black Output for peaks.pam5 file with dipy_horizon

## Way to reproduce
To visualize the dataset, use the following command on CLI:

dipy_horizon <absolute_path_to_dataset>

Please note the following important information:
- VTK version 9.0.1
- Operating system and version Ubuntu 18.04

**Comment by skoudoro** [comment]
Thank you for the feedback @areeshatariq. We will look into it

**Comment by skoudoro** [comment]
Hi @guaje,

Can you look and fix this? thank you

**Comment by skoudoro** [comment]
Can you look at this @maharshi-gor?

**Comment by maharshi-gor** [comment]
Hi @skoudoro 
I think this is already been completed as I visualized the stanford _hardi dataset peaks with dipy_fit_csa
![Screenshot 2024-03-06 at 6 10 48 PM](https://github.com/dipy/dipy/assets/39947025/ac83b128-e0db-4cd8-80e8-487d70f7b898)

**Comment by skoudoro** [comment]
Closing, it has been fixed
