### ISSUE TITLE
Tractogram Header in RecoBundles Tutorial

### ISSUE THREAD

**Issue by BramshQamar** [dipy/dipy#2309]
Hello,

I am confused why are we creating a target tractogram header that is exactly the same as the atlas tractogram header?

https://github.com/dipy/dipy/blob/f149c756e09f172c3b77a9e6c5b5390cc08af6ea/doc/examples/bundle_extraction.py#L31-L45

Thanks,
Bramsh

**Comment by Garyfallidis** [comment]
I agree it seems in line 44 it should be target_file rather than atlas_file. Give it a go @BramshQamar. @frheault do confirm this change is correct.

**Comment by frheault** [comment]
Yes I think it should be target_file.

This should indeed have the same header as the original file since the streamlines are from the original file (this is line 168)
`reco_af_l = StatefulTractogram(target[af_l_labels], target_header, Space.RASMM)`
