### ISSUE TITLE
DIPY open group meetings, Spring 2021

### ISSUE THREAD

**Issue by skoudoro** [dipy/dipy#2312]
Hello @dipy/dipy-community! 

Here the schedule for our open meetings for Spring 2021. Don't forget DIPY Workshop starts March 15 2021! More information here https://workshop.dipy.org

The zoom link for the open meeting is : https://iu.zoom.us/j/84926066336.

Feel free to request a talk or to share interesting work.

| Date          | time               | orator                      | title                                        |
|---------------|--------------------|-----------------------------|----------------------------------------------|
| January 14th  | 1pm EST / 7pm CET / 10am PT | @Garyfallidis                 | Workshop preparation                         |
| January 21th  | 1pm EST / 7pm CET / 10am PT | Jelle Veraart: @jelleveraart | On axon diameter mapping using diffusion MRI |
| February 4th  | 1pm EST / 7pm CET / 10am PT |        Cancelled     |         Cancelled                          |
| February 18th | 1pm EST / 7pm CET / 10am PT |       @Garyfallidis            |    Workshop action items               |
| March 4th     | 1pm EST / 7pm CET / 10am PT |    @skoudoro                      |         Release Preparation for upcoming workshop              |
| March 18th     | 1pm EST / 7pm CET / 10am PT |    @dipy/dipy-community                 |   During  DIPY WORKSHOP March 15th-19 2021           | 
| April 1st    | 1pm EST / 7pm CET / 10am PT |              @Garyfallidis                 |                        Great workshop - Next steps - Community Feedback                       |
| April 15th    | 1pm EST / 7pm CET / 10am PT |              ‪Leevi Kerkelä‬: @kerkelae                 |                      Q-Space Trajectory Imaging                         |
| April 29th    | 1pm EST / 7pm CET / 10am PT |             @skoudoro  @gabknight                  |                 Tractography contest, Tractography API  / Release overview                        |
| May 13th      | 1pm EST / 7pm CET / 10am PT |               @skoudoro |                     Roadmap                      |

**Comment by skoudoro** [comment]
Hi @dipy/dipy-community,

This is just a reminder about the talk tommorrow by Jelle Veraart : On axon diameter mapping using diffusion MRI

See example paper https://elifesciences.org/articles/49855

link: https://washington.zoom.us/j/95978299081.

See you tomorrow all at 1pm EST / 7pm CET / 10am PT!

**Comment by arokem** [comment]
@Garyfallidis : could we please change this to use your IU zoom account? I have graduate student interviews on the 18th. I can still come to the DIPY meeting, but my UW zoom account will be in use at the same time.

**Comment by skoudoro** [comment]
here you are @arokem: https://iu.zoom.us/j/84926066336.

I updated all the link above

**Comment by skoudoro** [comment]
Hello @dipy/dipy-community,

Quick reminder for the meeting today at 1pm EST / 7pm CET / 10am PT! 

It should be a short meeting and the Subject will be DIPY Release. If you have a question, requirement about a PR, feel free to connect.

Cheers!

ps: same link as usual:  https://iu.zoom.us/j/84926066336

**Comment by arokem** [comment]
Sorry about this I've had an unavoidable conflict this morning, so I will have to miss this meeting. 😞

**Comment by skoudoro** [comment]
Hello @dipy/dipy-community,

Quick reminder for the meeting tomorrow at 1pm EST / 7pm CET / 10am PT! 

@Garyfallidis will talk about the future steps after the successful workshop. Feel free to come and ask your question, make some requests, etc. Be part of the future of DIPY!

See you tomorrow!

Cheers!

ps: same link as usual:  https://iu.zoom.us/j/84926066336

**Comment by skoudoro** [comment]
Hello @dipy/dipy-community,

Dr. Leevi Kerkelä (UCL) will discuss today (Thursday 15 April at 1pm EST / 7pm CET / 10am PT) his project on integrating Q-Space Trajectory Imaging in DIPY.

The zoom link for the open meeting is https://iu.zoom.us/j/84926066336.

We hope to see you online! 

Cheers !

**Comment by skoudoro** [comment]
Hello @dipy/dipy-community,

Quick reminder for the meeting today at 1pm EST / 7pm CET / 10am PT!

- @gabknight will talk about the new Tractography competition.
- We willhave a bief talk about our Tracking framework
- @skoudoro will make a quick overview of the future Release. Let us know if there is any request.

Cheers!

ps: same link as usual: https://iu.zoom.us/j/84926066336

**Comment by skoudoro** [comment]
Hi @dipy/dipy-community,

Open group meetings in Spring 2021 reach their end.

We are preparing for the new season, Fall 2021, which will start in September 2021.

You can stay tuned by adding the DIPY event calendar to your agenda: https://calendar.google.com/calendar/u/0?cid=dXY4YzUwZmtmdnM1Mjk4MzdrMjk4dWVxaDBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ.

As usual, I am closing this issue and convert it into a discussion. 

Cheers!
