### ISSUE TITLE
Approx_polygon_track with repeated points gives an error

### ISSUE THREAD

**Issue by dulietina** [dipy/dipy#2314]
## Description
Approx_polygon_track under tracking/distances seems to have an issue with repeated points in a track. 
If the track is the numpy vector [[1,0,0],[2,0,0],[3,0,0],[4,0,0]] the output is, correctly, [[1,0,0],[4,0,0]] 
(I am not adding floating points for readability)

If the track though has a repeated point this happens:

>>> track=np.array([[1.,0.,0.],[1.,0.,0.],[3.,0.,0.],[4.,0.,0.]])
>>> approx_polygon_track(track)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dipy/tracking/distances.pyx", line 1123, in dipy.tracking.distances.approx_polygon_track
ZeroDivisionError: float division

It seems that the code takes in account this possibility through a dpy_isnan but it's not enough as there is no try?

## Way to reproduce
- Debian (Linux-4.19.0-12-amd64-x86_64-with-glibc2.10
- Python version 3.8.5
- [ ] dipy version 1.3.0
- [ ] dependency version (numpy 1.19.4, scipy 1.6.0, nibabel 3.2.1, h5py 3.1.0)

**Comment by skoudoro** [comment]
Hi @dulietina,

Thank you for pointing that out, we will look into it and give you feedback as soon as we can.

**Comment by drombas** [comment]
Hi! Looking to the incoming GSoC I would like start getting familiar with the project. May I tackle this as a good first issue?

**Comment by skoudoro** [comment]
Hi @drombas,

Not sure this issue is a good first issue. You should like all issues related to CLI since some GSOC projects are related to this theme. You can look at #2269 #2300 #2299 #2298 #2297. Those issues will help you to get familiar with our CLI system.

**Comment by drombas** [comment]
Thanks @skoudoro! I will have a look at those issues.

**Comment by Garyfallidis** [comment]
Also to say here that this function expects points to be different. Not sure in which situation it would make sense to have multiple points with same values on a track. In other words what is the user case for this?

**Comment by dulietina** [comment]
> Also to say here that this function expects points to be different. Not sure in which situation it would make sense to have multiple points with same values on a track. In other words what is the user case for this?

Hi, I can tell you that my use case stemmed from using your library in the geotracks world, where a tracker can stay still in a point and hence capture two times the same coordinates, for example.

It would be great hence if this function would work in this setting, if though it is not meant to work this way, at least there could be some asserting of some kind. Or at least the information could be packed in the docstring?

**Comment by skoudoro** [comment]
GeoTrack, Interesting! Thank you for the feedback @dulietina!

I just created a PR to fix this issue. Please, feel free to test the PR (#2406)

Will you be interested to give an informal talk during a DIPY open meeting (the next one in September / October)? It is always interesting to learn how people use DIPY outside of diffusion imaging. 

Let me know and I will send you an email!

**Comment by dulietina** [comment]
Hi @skoudoro sure, with pleasure if that could be of interest for the community. 
I'll wait for your mail and we can discuss then further details.
