### ISSUE TITLE
RecoBundles distances 

### ISSUE THREAD

**Issue by lmu4** [dipy/dipy#2320]
Hello, 

I discovered the RecoBundles algorithm and I wanted to test it on my tractogram built from the Tractometer Challenge diffusion data and segment the corpus callosum using the ground truth bundle provided by the Challenge. 
However, I might have discovered some issue in version 1.3.0 of RecoBundles. 

In fact, when launching the code, I have the following error : "Streamlines do not have the same number of points". I checked my tractograms and I previously used the function dipy.tracking.streamline.set_number_of_points to be sure to have the same number of points. 
However, I discovered that in the file dipy.tracking.distances.pyx, line 511, you check if the len of the tractograms are the same and if not, the error is  "Streamlines do not have the same number of points". Why would you want to have the same number of fibers in both tractograms ?

To be sure that my input were good, I downgraded dipy to version 1.2.0, where the test in line 511 of dipy.tracking.distances.pyx does not exist, and launched the same code. RecoBundles runs perfectly and I checked the segmentation using the Mrtrix viewer. 

Thank you in advance for your help, 
Best regards, 
Louise

**Comment by skoudoro** [comment]
Hi @lmu4, 

Sorry for the very late reply.  From what I see, It is not an error but just a warning and it seems related to https://github.com/dipy/dipy/issues/342. 
I think we should just cool down the message. Can you confirm that you have the same result in both versions? 
thank you

**Comment by Garyfallidis** [comment]
@lmu4 is correct the check should be for len(tracksA[0]) == len(tracksB[0])
