### ISSUE TITLE
Brain mask as a required argument to CLI

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#2323]
A brain mask is currently required to fit a model to data using the CLI (e.g., to `dipy_fit_dti`). 

Maybe we should relax this requirement to make this an optional input? Any strong objections?

**Comment by skoudoro** [comment]
Hi @arokem,

It was done on purpose to force good habits. We are afraid that if we relax,  90 % of the people will run it without a mask. We have already seen a lot of issues with DIPY related to the masks.

Personally, I am fine to relax this feature, but I am afraid that it gives the wrong signal...

**Comment by arokem** [comment]
That makes sense. One thing I noticed in preparing for the workshop is that if you do the kinda obvious example: 

```
dipy_fetch "stanford_hardi" --out_dir .

dipy_median_otsu ./stanford_hardi/HARDI150.nii.gz --vol_idx 0 --out_dir ./stanford_hardi 

dipy_fit_dti ./stanford_hardi/HARDI150.nii.gz ./stanford_hardi/HARDI150.bval ./stanford_hardi/HARDI150.bvec ./stanford_hardi/brain_mask.nii.gz --out_dir ./stanford_hardi 

```
things look pretty bad, because the mask crops a lot of brain that shouldn't be cropped. I might need to tweak the inputs to median_otsu to get it right. But this is OK. Closing.

**Comment by sitek** [comment]
Hi @arokem , I'm having the same issue – `dipy_median_otsu` does some poor cropping. Any suggestions when using the CLI?
<img width="824" alt="image" src="https://user-images.githubusercontent.com/2488038/132099268-c9542399-b167-4479-a634-587e64b04e19.png">

**Comment by arokem** [comment]
You can try experimenting with some of the parameters through the CLI: 

```
usage: dipy_median_otsu [-h] [--save_masked] [--median_radius int]
                        [--numpass int] [--autocrop]
                        [--vol_idx [int [int ...]]] [--dilate int]
                        [--out_dir str] [--out_mask str] [--out_masked str]
                        [--force] [--version] [--out_strat string]
                        [--mix_names] [--log_level string] [--log_file string]
                        input_files
```

I'd focus in particular on `median_radius`, `dilate`, `numpass` (see [here](https://github.com/dipy/dipy/blob/master/dipy/segment/mask.py#L142-L157) for defaults).

**Comment by sitek** [comment]
> I'd focus in particular on `median_radius`, `dilate`, `numpass` (see [here](https://github.com/dipy/dipy/blob/master/dipy/segment/mask.py#L142-L157) for defaults).

Thanks! Still figuring out the optimal values, but getting close.
