### ISSUE TITLE
gtab.info does not print anything

### ISSUE THREAD

**Issue by BramshQamar** [dipy/dipy#2331]
https://github.com/dipy/dipy/blob/10621cd0ffaf8c1f16b76931486b669a4da33a81/dipy/core/gradients.py#L215 info from GradientTable doesn't print anything in Spyder and Jupyter. Perhaps because it uses logger which might be disabled by Spyder and Jupyter and works best for CLIs only?

**Comment by arokem** [comment]
Yep. Using logging here was probably overkill. We should change that back to `print`

**Comment by arokem** [comment]
Alternatively, we could implement a proper `__repr__` for this object.
