### ISSUE TITLE
Aphysical signal after running patch2self

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#2334]
We  (with @jyeatman and @SendyCaffarra) have been analyzing a dataset of children's dMRI. We were interested in trying out patch2self for denoising and noticed something in the comparison with mp-pca (Sendy is running both of these through qsiprep). Using patch2self denoising, we find quite a few voxels with aphysical signals (DWI higher than b0 measurements), particularly in the corpus callosum, which then translate through DIPY processing into zero FA voxels. This is with patch2self: 

![image (5)](https://user-images.githubusercontent.com/118582/111505873-4e692800-8706-11eb-8341-f70627136557.png)

And this is the same data denoised with mp-pca: 

<img width="1661" alt="Screen Shot 2021-03-17 at 9 42 53 AM" src="https://user-images.githubusercontent.com/118582/111506079-7d7f9980-8706-11eb-8b4c-1fa675287c60.png">

As mentioned above, we are running patch2self through qsiprep, with the default settings used there.

Has anyone seen something like this with patch2self? Any thoughts about how to mitigate this when using p2s?

**Comment by ShreyasFadnavis** [comment]
Hi @arokem ! Thank you for reporting this... I have not seen this issue in the past, but my guess is that this arises from using the `np.clip`. In the latest version of Qsiprep,  I have integrated the `shift_intensity` mode. Can you try setting it to True and setting `clip_negative_vals=False`. I would also like to take a quick look personally to see what's going wrong. Would it be possible to share 1 subject with me?

**Comment by arokem** [comment]
> It could also be due to choosing a wrong b0_threshold for segregating the b-values. Also was model='ols' used?

What's the qsiprep default? That's the one they used, I believe. 

> I would also like to take a quick look personally to see what's going wrong. Would it be possible to share 1 subject with me?

Sure. Let me coordinate data hand-off by email.

**Comment by ShreyasFadnavis** [comment]
> > It could also be due to choosing a wrong b0_threshold for segregating the b-values. Also was model='ols' used?
> 
> What's the qsiprep default? That's the one they used, I believe.
> 
> > I would also like to take a quick look personally to see what's going wrong. Would it be possible to share 1 subject with me?
> 
> Sure. Let me coordinate data hand-off by email.

Thanks @arokem! The default in QSIprep should be the same as DIPY `b0_threshold=50`.

**Comment by ShreyasFadnavis** [comment]
@mattcieslak -- just to be sure, we do expose the `b0_threshold` argument for users to tweak right? I also think it might be a good idea to set it to `100` in general?

**Comment by mattcieslak** [comment]
In qsiprep we set the b=0 threshold to 100 (https://github.com/PennBBL/qsiprep/blob/master/qsiprep/cli/run.py#L188) but the user can always set it so something different via `--b0-threshold` and this will be used throughout the whole workflow

**Comment by arokem** [comment]
I don't think that's the issue for this particular data, which has b-values that are 0.

**Comment by mattcieslak** [comment]
@arokem do you have the working directories saved from your run? Those will have the before-and-after images from each step in there. Denoising is the very first step in the qsiprep workflow. Maybe the unringing is introducing the implausible values? Bias correction divides each voxel by a single number so that couldn't be it

**Comment by ShreyasFadnavis** [comment]
Hi @mattcieslak ! Thank you for your response 👍🏽 I did look at the data that @arokem shared with me and I did not get any implausible values from `patch2self` in the FA map. This is how I ran Patch2Self via DIPY:
```
denoised_arr = patch2self(data, bvals, verbose=True, model='ols', shift_intensity=True, clip_negative_vals=False)
```
We added these options to `QSIPrep` recently and I think are needed in this case: `shift_intensity` and `clip_negative_vals`.

Are they in the current release of `QSIPrep`?

**Comment by arokem** [comment]
Thanks for jumping on this so quickly. I can reproduce your findings: 

![image](https://user-images.githubusercontent.com/118582/111685205-dde50880-87e4-11eb-8b55-ed9ddaf9c54e.png)

But with the default settings `patch2self(data, bvals)`, I still see this: 

![image](https://user-images.githubusercontent.com/118582/111685254-e9d0ca80-87e4-11eb-997b-e6e4cb807cb3.png)

From a couple more experiments I did, it looks like both `shift_intensity=True` and `clip_negative_vals=False` are required and `model='ols'` is not crucial

Should we change the defaults to `shift_intensity=True, clip_negative_vals=False` ?

**Comment by arokem** [comment]
Also (maybe less important), maybe you can explain why clipping negative values and shifting the intensity distribution is so important in these data?

**Comment by ShreyasFadnavis** [comment]
> Thanks for jumping on this so quickly. I can reproduce your findings:
> 
> ![image](https://user-images.githubusercontent.com/118582/111685205-dde50880-87e4-11eb-8b55-ed9ddaf9c54e.png)
> 
> But with the default settings `patch2self(data, bvals)`, I still see this:
> 
> ![image](https://user-images.githubusercontent.com/118582/111685254-e9d0ca80-87e4-11eb-997b-e6e4cb807cb3.png)
> 
> From a couple more experiments I did, it looks like both `shift_intensity=True` and `clip_negative_vals=False` are required and `model='ols'` is not crucial
> 
> Should we change the defaults to `shift_intensity=True, clip_negative_vals=False` ?

Yes! Both are necessary. I think I am going to eventually deprecate `clip_negative_vals`, it was added for aesthetic purposes and because the Local PCA code made use of it. The reason being that these models sometimes undergo mean reversion pushing the intensity of the negative side. This is something that happens when noise is shifted too far away from the mean `0` that Patch2Self expects. It does not exactly need to be `mean 0` but if it is too far off, the shift correction is needed!

**Comment by mattcieslak** [comment]
There aren't options for the user to change these on the command line yet. The current default is the opposite of what you recommend above (https://github.com/PennBBL/qsiprep/blob/master/qsiprep/interfaces/dipy.py#L109).

**Comment by arokem** [comment]
I just put in https://github.com/dipy/dipy/pull/2337 to address this upstream, but might be good to change here as well until that propagates through?

**Comment by arokem** [comment]
And by "here" I mean "there"  (on qsiprep) 😵

**Comment by ShreyasFadnavis** [comment]
> And by "here" I mean "there" (on qsiprep) 😵

Thanks for the PR @arokem and @mattcieslak ! I'll make a PR on QSIprep shortly 👍🏽

**Comment by skoudoro** [comment]
Do we consider this issue closed by #2337 and PennBBL/qsiprep#239?

**Comment by ShreyasFadnavis** [comment]
Yes from me! I am also following up with a PR for detailed documentation of options for `Patch2Self`

**Comment by arokem** [comment]
Yes!
