### ISSUE TITLE
Missing Python 3.9 wheels

### ISSUE THREAD

**Issue by effigies** [dipy/dipy#2343]
## Description
[PyPI](https://pypi.org/project/dipy/#files) doesn't have Python 3.9 wheels, making CI that depends on dipy slow for 3.9 builds.

**Comment by skoudoro** [comment]
Hi @effigies, thank you for letting us know, we will update it

**Comment by skoudoro** [comment]
As you can see [here](https://pypi.org/project/dipy/1.4.0/#files), it should be good now. 

Let us know if you have any issues @effigies and thanks!

**Comment by effigies** [comment]
Thanks, @skoudoro!
