### ISSUE TITLE
Streamlines get negative coordinates in voxel space

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#2364]
In our work with the GPUStreamlines code, we ran into this strange situation, and @36000 reported that here: 

https://github.com/dipy/GPUStreamlines/issues/7 

But it turns out that this code is a replica of our interpolation code. Specifically this line: 

https://github.com/dipy/dipy/blob/b69ea7011b5e5a26fd14aa27ff8bbb2b93d58c60/dipy/core/interpolation.pyx#L332

Is this erroneous? I should add: I believe that this is happening in the rather exotic situation where we are tracking very close to the edge of the volume.

**Comment by skoudoro** [comment]
the GPUStreamlines issue has been closed and it seems there is no problem. 

I believe you can close this issue but a quick explanation by @36000 would have been great! (just in case someone run into the same situation/question)

**Comment by skoudoro** [comment]
Do you remember what was the fix @arokem? 

Can we close this?
