### ISSUE TITLE
RF: standardize the argument name for the number of threads/cores

### ISSUE THREAD

**Issue by drombas** [dipy/dipy#2377]
## Description
Following #2352, currently four different argument names are used to specify the number of threads/cores to be used: ``num_threads``, ``slr_num_threads``, ``num_processes``,  and ``nbr_processes``. 

The general rule across the codebase (although not always followed) seems to be to use ``num_threads`` and ``slr_num_threads`` for OpenMP parallelization, and ``num_processes`` and ``nbr_processes`` for parallelization using multiprocessing package. 

## Possible solution
1.  Decide the appropriate name
2.  Update it where necessary

**Comment by skoudoro** [comment]
Thank you @drombas for spotting this.

I vote for `numthreads` and `num_processes`.  If you want to tackle this problem, you can use [`deprecate_params`](https://github.com/dipy/dipy/blob/master/dipy/utils/deprecator.py#L195) decorator. 

You can find an [example here](https://github.com/dipy/dipy/blob/master/dipy/align/imaffine.py#L248)

Let us know if you have any questions.
