### ISSUE TITLE
Community and governance

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#2380]
We would like to clarify project community guidelines and governance. I think that we can emulate and develop the process that nibabel went through in this issue: https://github.com/nipy/nibabel/pull/778

**Comment by arokem** [comment]
Looking back at that issue, I see now that this should be really straightforward. It basically moves the nipy CoC (which we already point to) into the repo and adds a small section with names/emails for folks that should be contacted in case of an incident.

**Comment by Garyfallidis** [comment]
Great, please go ahead and make the PR.
