### ISSUE TITLE
Add a function to read streamline from the result generated by the command "probtrackx2" in FMRIB's Diffusion Toolbox

### ISSUE THREAD

**Issue by forwho** [dipy/dipy#2393]
Adding the option "--savepaths" when using the command "probtrackx2" in FMRIB's Diffusion Toolbox, the program will save the streamline coordinates in a text file. Could developers of DIPY add a function to read the text file and save the streamlines to a Tractogram object.

**Comment by skoudoro** [comment]
Hi @forwho,

Can you provide an example of this text file?

I am not sure we will add this function and I am surprised that they do not provide a command to convert their text file to a standard tractography file like tck/trk.

I recommend you to ask the question on [Neurostars](https://neurostars.org/). I supposed someone already faces this problem and I am pretty sure a converter already exists.

Please, keep us updated and we will look at your text file

**Comment by skoudoro** [comment]
Also, I am moving this question on [our forum](https://github.com/dipy/dipy/discussions)
