### ISSUE TITLE
Documentation References - Remove (1, 2, ...)

### ISSUE THREAD

**Issue by Garyfallidis** [dipy/dipy#2394]
Can we investigate if we can disable the sphinx option that does the references to look like this?

[Author] (1, 2, 3, 5) , Title etc?

See example with issue here.

https://dipy.org/documentation/1.4.1./examples_built/bundle_extraction/#example-bundle-extraction

And example working well here
https://dipy.org/documentation/1.4.1./examples_built/denoise_patch2self/#example-denoise-patch2self

You will have to go to the end of the page and try to click on the links.

**Comment by skoudoro** [comment]
Unfortunatly, it seems not trivial. we need to create a script to do that by parsing the documentation
closing since this is very low priority
