### ISSUE TITLE
Applying image-based deformations to streamlines example

### ISSUE THREAD

**Issue by BramshQamar** [dipy/dipy#2400]
## Description
In this example on applying image-based deformations to streamlines [doc/examples/streamline_registration.py](https://dipy.org/documentation/1.4.1./examples_built/streamline_registration/#example-streamline-registration),
I don't understand what this part is doing https://github.com/dipy/dipy/blob/541b5b2992e786b5f51d05649a398cb331903456/doc/examples/streamline_registration.py#L32-L34

Also gives me an error when I run it:

`ModuleNotFoundError: No module named 'streamline_tools'`

And why are we accessing hardi_img variable before it is initialized? https://github.com/dipy/dipy/blob/541b5b2992e786b5f51d05649a398cb331903456/doc/examples/streamline_registration.py#L34

**Comment by arokem** [comment]
Hi Bramsh,

Fair question. It's a bit of a strange pattern: the example you are trying
to run depends on running this other example first:

https://github.com/dipy/dipy/blob/541b5b2992e786b5f51d05649a398cb331903456/doc/examples/streamline_tools.py

That's the thing it's trying to import. That also explains where the
already-initialized variable is coming from. But it also means that the
example will only work if it is run in the context of our source tree. This
is not a free-standing example that runs on its own. Maybe we should
document this better?

**Comment by BramshQamar** [comment]
<img width="554" alt="Screen Shot 2021-05-20 at 12 45 32 PM" src="https://user-images.githubusercontent.com/26060471/119017763-52fdc700-b969-11eb-999f-f5a0c5c533dc.png">

Visualized with template

**Comment by skoudoro** [comment]
Thank you for pointing that out. it would be good to:
- separate this 2 tutorials
- fix the space problem

**Comment by arokem** [comment]
Maybe we should make a fetcher for these trk files, just so we can make this example freestanding?
