### ISSUE TITLE
How to apply MI metric in dipy？

### ISSUE THREAD

**Issue by zhang-qiang-github** [dipy/dipy#2432]
I want to use mutual information as the metric in SyN registration. 

My code is:

```
        from dipy.align.imaffine import MutualInformationMetric
        from dipy.align.imwarp import SymmetricDiffeomorphicRegistration
        metric = MutualInformationMetric()
        level_iters = [300, 100, 5]
        sdr = SymmetricDiffeomorphicRegistration(metric, level_iters, ss_sigma_factor=smoothingSigmas)
        mapping = sdr.optimize(static, moving)
```

Then, a bug is reported:

```
  File "C:\Users\MLoong\Desktop\medpro\CellWidgetModule\RegistrationWindow.py", line 337, in synRegistration
    sdr = SymmetricDiffeomorphicRegistration(metric, level_iters, ss_sigma_factor=smoothingSigmas)
  File "D:\Anaconda3\envs\gitlab_medpro\lib\site-packages\dipy\align\imwarp.py", line 928, in __init__
    super(SymmetricDiffeomorphicRegistration, self).__init__(metric)
  File "D:\Anaconda3\envs\gitlab_medpro\lib\site-packages\dipy\align\imwarp.py", line 850, in __init__
    self.dim = metric.dim
AttributeError: 'MutualInformationMetric' object has no attribute 'dim'
```

How can I apply MI metric in SyN?

**Comment by skoudoro** [comment]
Hi @zhang-qiang-github,

With this current version of DIPY, you can not.  This metric works only with AffineRegistration and needs to be improved if you want to make it work with SYN. 

Thank you for your feedback and Feel free to contribute if you improve this metric!

**Comment by rtaiello** [comment]
Hi @skoudoro are there anyone who is working on the implementation of MI for SYN?

**Comment by skoudoro** [comment]
I do not know and I don't think so @rtaiello,

This is on my long TODO list, but very low priority compare to other tasks. 

Feel free to add it! we can help you!

**Comment by rtaiello** [comment]
Many thanks, @skoudoro! 

I could be interested, but I don't know precisely what are the things that are missing from the already implemented `MutualInformationMetric` available for Affine registration.
