### ISSUE TITLE
Citation for IVIM dataset not present in docs

### ISSUE THREAD

**Issue by jerryfrancis-97** [dipy/dipy#2443]
## Description
Hi Dipy developers, I need to know the data source/ citation of the ivim dataset which is present in-built in the dipy package. This info is also missing in the [docs](https://dipy.org/documentation/1.4.1./data/).

Regards,
Jerome

PS : Thanks for creating and improving dipy! :)

**Comment by skoudoro** [comment]
Hi @jerryfrancis-97,

Thank you for catching that. I, personally have no idea about this dataset source.  Maybe @ShreyasFadnavis, @arokem will have a better idea. 

Feel free to create a PR as soon as we post the reference here!

**Comment by arokem** [comment]
We got this data from @etpeterson around 2016 when @quantshah originally developed the IVIM module as part of his GSoC project. Eric: is there a particular reference we should use? Do you happen to have records of the experimental protocol that was used? If Eric doesn't have a specific reference, you can refer to this Figshare entry: https://figshare.com/articles/dataset/IVIM_dataset/3395704. It has a doi, so you should be able to cite it as: "Peterson, Eric (2016): IVIM dataset. figshare. Dataset. https://doi.org/10.6084/m9.figshare.3395704.v1 ".

**Comment by etpeterson** [comment]
Sorry, I don't remember and I don't have any way to look back at that so @arokem's suggestion is the way to go.

**Comment by arokem** [comment]
Thanks for the quick response here!

**Comment by jerryfrancis-97** [comment]
Thanks @arokem @etpeterson @skoudoro for the citation. Can the above citation mentioned by @arokem be added into the docs?
