### ISSUE TITLE
Patch2Self: Less than 10 3D Volumes Bug

### ISSUE THREAD

**Issue by tecork** [dipy/dipy#2461]
## Description
When using a dataset with less than 10 diffusion directions, the warning flag that mentions denoising performance might not give great performance has a minor bug.

---------------------------------------------------------------------------
```python
TypeError                                 Traceback (most recent call last)
<ipython-input-10-6eb883803c06> in <module>
      1 # Denoising Step: Patch2Self
      2 from dipy.denoise.patch2self import patch2self
----> 3 denoised_arr = patch2self(data, bvals)


~/opt/anaconda3/lib/python3.7/site-packages/dipy/denoise/patch2self.py in patch2self(data, bvals, patch_radius, model, b0_threshold, out_dtype, alpha, verbose, b0_denoising, clip_negative_vals, shift_intensity)
    246     if data.shape[3] < 10:
    247         warn("The intput data has less than 10 3D volumes. Patch2Self may not",
--> 248              "give denoising performance.")
    249 
    250     if out_dtype is None:

TypeError: category must be a Warning subclass, not 'str'
```
---------------------------------------------------------------------------

The quick fix is to change the comma into a plus sign:
```python
warn("The input data has less than 10 3D volumes. Patch2Self may not" +
              "give denoising performance.")
```

Also a minor typo on input, but I have it corrected in my modification. It works when I corrected it on my local machine. Awesome tool though!

Best,

Tyler

**Comment by skoudoro** [comment]
This has been fixed on master via #2438 so closing this issue.

Thanks again @tecork
