### ISSUE TITLE
MAINT: Get Python 3.10 binaries up on scipy-wheels-nightly

### ISSUE THREAD

**Issue by larsoner** [dipy/dipy#2489]
NumPy and SciPy have nightly 3.10 wheels up at https://pypi.anaconda.org/scipy-wheels-nightly/simple, it would be great if dipy had some so that downstream libraries (e.g., MNE-Python) could fully test 3.10 capabilities! FWIW, local testing suggests that the parts of dipy we use do work with 3.10, so hopefully it's not too terrible to get it working!

**Comment by skoudoro** [comment]
Thanks for the feedback @larsoner. 

I will look into it at the end of this day or tomorrow.

**Comment by skoudoro** [comment]
After looking at it, it seems we need to cut a release for python 3.10 wheels.  it works well with the main branch but not with the release 1.4.1

**Comment by hoechenberger** [comment]
Hello, I know you're tracking progress towards 1.5.0 in https://github.com/dipy/dipy/pull/2462; just wanted to let you know that a release with Python 3.10 would be greatly appreciated, as `dipy` seems to be the only package in our fairly big dependency stack that prevents us from switching to 3.10. Thank you!

**Comment by skoudoro** [comment]
Hi @hoechenberger,

Apologize for the delay, the release should happen this weekend or next week.

I will update #2462.

**Comment by hoechenberger** [comment]
This sounds amazing! Thank you very much!

**Comment by skoudoro** [comment]
![image](https://user-images.githubusercontent.com/23106443/157313238-c700cc0a-cb0a-4906-9141-fc6fcd25cb23.png)

Closing, as we can see above, there are present. Thanks again for the feedback.
