### ISSUE TITLE
ENH: Extend Horizon to visualize 2 volumes simultaneously

### ISSUE THREAD

**Issue by drombas** [dipy/dipy#2491]
Hi! As an idea for future development, it would be cool to extend Horizon to be able to visualize two volumes at the same time.

Not sure how hard the implementation would be but it would be a useful feature (for instance, when checking registration results).

**Comment by skoudoro** [comment]
That's a great idea! Thanks @drombas. @guaje is working on the horizon so maybe he will have time to add this feature

**Comment by skoudoro** [comment]
done by @guaje, closing for now. we might need a new issue to be able to see 2 volumes side by side instead of overlapping.
