### ISSUE TITLE
Problem generating Connectivity Matrix: "Slice step cannot be zero"

### ISSUE THREAD

**Issue by itellaetxe** [dipy/dipy#2499]
Hello,

I am working with a DWI dataset from the ADNI database, trying to build the connectivity matrix of a tractogram I computed from a subject with Tractoflow, using the Brainnetome Atlas and its MNI standard space. This work is for the yearly class project, for my Master's degree.

Following a DIPY documentation tutorial ([Applying image-based deformations to streamlines](https://dipy.org/documentation/1.4.0./examples_built/streamline_registration/)) for streamline registration, I tried to register my tractogram to a standard MNI space, using the _deform_streamlines()_ function. Some streamlines seem to be incorrectly modified (I visualized the tracts) by the deformation field I computed from the b0 -> MNISpace registration, but it that is not the main issue as this step ran with no errors.

The problem comes when I try to generate the connectivity matrix of the mentioned tractogram (following [Connectivity Matrices, ROI Intersections and Density Maps](https://dipy.org/documentation/1.0.0./examples_built/streamline_tools/)) as it raises an error saying _"Slice step cannot be zero"_. While building the tractogram, I compressed the streamlines, which seems to be an important thing to mention.

How could I fix this?

Thanks for your help, I hope I am not asking a trivial thing.

Error traceback:
```python
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_16300/2721825022.py in <module>
----> 1 M, grouping = utils.connectivity_matrix(sft,tracks_affine, atlas.astype(np.uint8), return_mapping=True, mapping_as_streamlines=True)

~/miniconda3/envs/pblneuromod/lib/python3.8/site-packages/dipy/tracking/utils.py in connectivity_matrix(streamlines, affine, label_volume, inclusive, symmetric, return_mapping, mapping_as_streamlines)
    216     else:
    217         # take the first and last point of each streamline
--> 218         endpoints = [sl[0::len(sl)-1] for sl in streamlines]
    219 
    220         # Map the streamlines coordinates to voxel coordinates

~/miniconda3/envs/pblneuromod/lib/python3.8/site-packages/dipy/tracking/utils.py in <listcomp>(.0)
    216     else:
    217         # take the first and last point of each streamline
--> 218         endpoints = [sl[0::len(sl)-1] for sl in streamlines]
    219 
    220         # Map the streamlines coordinates to voxel coordinates

~/miniconda3/envs/pblneuromod/lib/python3.8/site-packages/dipy/io/stateful_tractogram.py in __getitem__(self, key)
    231             key = [key]
    232 
--> 233         return self.from_sft(self.streamlines[key], self,
    234                              data_per_point=self.data_per_point[key],
    235                              data_per_streamline=self.data_per_streamline[key])

~/miniconda3/envs/pblneuromod/lib/python3.8/site-packages/nibabel/streamlines/array_sequence.py in __getitem__(self, idx)
    383 
    384         if isinstance(off_idx, slice):  # Standard list slicing
--> 385             seq._offsets = self._offsets[off_idx]
    386             seq._lengths = self._lengths[off_idx]
    387             return seq
ValueError: slice step cannot be zero
```
## Way to reproduce
I attach the piece of code relevant to the issue.
**CODE:**
```python
kable = load_tractogram('Track0.trk', 'same')
affineT, dimensions, voxel_sizes, voxel_order = get_reference_info(kable)
B0_im, B0_affine = load_nifti('b0_resampled.nii.gz')
np.unique(B0_im.shape == dimensions)
atlas, atlas_affine = load_nifti('BN_Atlas_246_1mm.nii.gz')
std_im, std_affine, prev_voxel_size = load_nifti('HCP40_MNI_1.25mm.nii.gz', return_voxsize=True)
new_voxel_size = (1., 1., 1.)
std_im_rs, std_affine_rs = reslice(std_im, std_affine, prev_voxel_size, new_voxel_size)
print('ATLAS dimensions = ' + str(atlas.shape))
print('Resliced standard image dimensions = ' + str(std_im_rs.shape))
plt.subplot(121)
plt.imshow(std_im_rs[:,:, 120], cmap='gray')
plt.subplot(122)
plt.imshow(atlas[:,:, 120])
std_im = std_im_rs
std_affine = std_affine_rs # Overwrite the resliced volumes.

# Registration
static = std_im
static_affine = std_affine
moving = B0_im
moving_affine = B0_affine
affine_map = transform_origins(static, static_affine, moving, moving_affine)

nbins = 32
sampling_prop = None
metric = MutualInformationMetric(nbins, sampling_prop)
level_iters = [10, 10, 5]
sigmas = [3.0, 1.0, 0.0]
factors = [4, 2, 1]
affine_reg = AffineRegistration(metric=metric, level_iters=level_iters,
                                sigmas=sigmas, factors=factors)
transform = TranslationTransform3D()

params0 = None
translation = affine_reg.optimize(static, moving, transform, params0,
                                  static_affine, moving_affine)
transformed = translation.transform(moving)
transform = RigidTransform3D()

rigid_map = affine_reg.optimize(static, moving, transform, params0,
                                static_affine, moving_affine,
                                starting_affine=translation.affine)
transformed = rigid_map.transform(moving)
transform = AffineTransform3D()
affine_reg.level_iters = [20, 20, 5]
highres_map = affine_reg.optimize(static, moving, transform, params0,
                                  static_affine, moving_affine,
                                  starting_affine=rigid_map.affine)
transformed = highres_map.transform(moving)
metric = CCMetric(3)
level_iters = [10, 10, 5]
sdr = SymmetricDiffeomorphicRegistration(metric, level_iters)

mapping = sdr.optimize(static, moving, static_affine, moving_affine,
                       highres_map.affine)
warped_moving = mapping.transform(moving)
vox_size = 1
# Create an isocentered affine
target_isocenter = np.diag(np.array([-vox_size, vox_size, vox_size, 1]))
# Take the off-origin affine capturing the extent contrast between the mean B0 image and the template
origin_affine = affine_map.affine.copy()
origin_affine[0][3] = -origin_affine[0][3]
origin_affine[1][3] = -origin_affine[1][3]

mni_streamlines = deform_streamlines(
    kable.streamlines, deform_field=mapping.get_forward_field(),
    stream_to_current_grid=target_isocenter,
    current_grid_to_world=origin_affine, stream_to_ref_grid=target_isocenter,
    ref_grid_to_world=np.eye(4))

std_Nifti = nib.Nifti1Image(std_im, std_affine)
sft = StatefulTractogram(mni_streamlines, std_Nifti, Space.RASMM)
save_tractogram(sft, 'mni-lr-superiorfrontal.trk', bbox_valid_check=False) # This returns True, meaning it was successful saving the file.
tracks_affine, dims, voxel_szs, voxel_ords = get_reference_info(sft)

# CONFLICTIVE PART
M, grouping = utils.connectivity_matrix(sft,tracks_affine, label_volume=atlas.astype(np.uint8), return_mapping=False, mapping_as_streamlines=False)
```

**OS, PYTHON & DEPENDENCIES VERSION:**
- Operating system and version: Linux-5.11.0-46-generic-x86_64-with-glibc2.17
- Python version: Python  3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
- dipy version: 1.4.1
- Numpy  1.22.1
- SciPy  1.7.3
- Nibabel  3.2.1
- H5Py: Not installed
- Cvxpy: Not installed
- fury  0.7.1
(Working on jupyter notebook. )

**Comment by itellaetxe** [comment]
Hi again,

My problem was solved by adding the **_.streamlines_** method to the tractogram variable (_kable_ in my code).
I am closing the issue with this.

Thank you again @drombas for the help and the amazing explanations.

**Comment by brunodireito** [comment]
Hi, 

I am having the exact same output, but using streamlines as input. Any idea on how to debug this problem? thank you

**Comment by alienx-zero** [comment]
> Hello,
> 
> I am working with a DWI dataset from the ADNI database, trying to build the connectivity matrix of a tractogram I computed from a subject with Tractoflow, using the Brainnetome Atlas and its MNI standard space. This work is for the yearly class project, for my Master's degree.
> 
> Following a DIPY documentation tutorial ([Applying image-based deformations to streamlines](https://dipy.org/documentation/1.4.0./examples_built/streamline_registration/)) for streamline registration, I tried to register my tractogram to a standard MNI space, using the _deform_streamlines()_ function. Some streamlines seem to be incorrectly modified (I visualized the tracts) by the deformation field I computed from the b0 -> MNISpace registration, but it that is not the main issue as this step ran with no errors.
> 
> The problem comes when I try to generate the connectivity matrix of the mentioned tractogram (following [Connectivity Matrices, ROI Intersections and Density Maps](https://dipy.org/documentation/1.0.0./examples_built/streamline_tools/)) as it raises an error saying _"Slice step cannot be zero"_. While building the tractogram, I compressed the streamlines, which seems to be an important thing to mention.
> 
> How could I fix this?
> 
> Thanks for your help, I hope I am not asking a trivial thing.
> 
> Error traceback:
> 
> ```python
> ValueError                                Traceback (most recent call last)
> /tmp/ipykernel_16300/2721825022.py in <module>
> ----> 1 M, grouping = utils.connectivity_matrix(sft,tracks_affine, atlas.astype(np.uint8), return_mapping=True, mapping_as_streamlines=True)
> 
> ~/miniconda3/envs/pblneuromod/lib/python3.8/site-packages/dipy/tracking/utils.py in connectivity_matrix(streamlines, affine, label_volume, inclusive, symmetric, return_mapping, mapping_as_streamlines)
>     216     else:
>     217         # take the first and last point of each streamline
> --> 218         endpoints = [sl[0::len(sl)-1] for sl in streamlines]
>     219 
>     220         # Map the streamlines coordinates to voxel coordinates
> 
> ~/miniconda3/envs/pblneuromod/lib/python3.8/site-packages/dipy/tracking/utils.py in <listcomp>(.0)
>     216     else:
>     217         # take the first and last point of each streamline
> --> 218         endpoints = [sl[0::len(sl)-1] for sl in streamlines]
>     219 
>     220         # Map the streamlines coordinates to voxel coordinates
> 
> ~/miniconda3/envs/pblneuromod/lib/python3.8/site-packages/dipy/io/stateful_tractogram.py in __getitem__(self, key)
>     231             key = [key]
>     232 
> --> 233         return self.from_sft(self.streamlines[key], self,
>     234                              data_per_point=self.data_per_point[key],
>     235                              data_per_streamline=self.data_per_streamline[key])
> 
> ~/miniconda3/envs/pblneuromod/lib/python3.8/site-packages/nibabel/streamlines/array_sequence.py in __getitem__(self, idx)
>     383 
>     384         if isinstance(off_idx, slice):  # Standard list slicing
> --> 385             seq._offsets = self._offsets[off_idx]
>     386             seq._lengths = self._lengths[off_idx]
>     387             return seq
> ValueError: slice step cannot be zero
> ```
> 
> ## Way to reproduce
> I attach the piece of code relevant to the issue. **CODE:**
> 
> ```python
> kable = load_tractogram('Track0.trk', 'same')
> affineT, dimensions, voxel_sizes, voxel_order = get_reference_info(kable)
> B0_im, B0_affine = load_nifti('b0_resampled.nii.gz')
> np.unique(B0_im.shape == dimensions)
> atlas, atlas_affine = load_nifti('BN_Atlas_246_1mm.nii.gz')
> std_im, std_affine, prev_voxel_size = load_nifti('HCP40_MNI_1.25mm.nii.gz', return_voxsize=True)
> new_voxel_size = (1., 1., 1.)
> std_im_rs, std_affine_rs = reslice(std_im, std_affine, prev_voxel_size, new_voxel_size)
> print('ATLAS dimensions = ' + str(atlas.shape))
> print('Resliced standard image dimensions = ' + str(std_im_rs.shape))
> plt.subplot(121)
> plt.imshow(std_im_rs[:,:, 120], cmap='gray')
> plt.subplot(122)
> plt.imshow(atlas[:,:, 120])
> std_im = std_im_rs
> std_affine = std_affine_rs # Overwrite the resliced volumes.
> 
> # Registration
> static = std_im
> static_affine = std_affine
> moving = B0_im
> moving_affine = B0_affine
> affine_map = transform_origins(static, static_affine, moving, moving_affine)
> 
> nbins = 32
> sampling_prop = None
> metric = MutualInformationMetric(nbins, sampling_prop)
> level_iters = [10, 10, 5]
> sigmas = [3.0, 1.0, 0.0]
> factors = [4, 2, 1]
> affine_reg = AffineRegistration(metric=metric, level_iters=level_iters,
>                                 sigmas=sigmas, factors=factors)
> transform = TranslationTransform3D()
> 
> params0 = None
> translation = affine_reg.optimize(static, moving, transform, params0,
>                                   static_affine, moving_affine)
> transformed = translation.transform(moving)
> transform = RigidTransform3D()
> 
> rigid_map = affine_reg.optimize(static, moving, transform, params0,
>                                 static_affine, moving_affine,
>                                 starting_affine=translation.affine)
> transformed = rigid_map.transform(moving)
> transform = AffineTransform3D()
> affine_reg.level_iters = [20, 20, 5]
> highres_map = affine_reg.optimize(static, moving, transform, params0,
>                                   static_affine, moving_affine,
>                                   starting_affine=rigid_map.affine)
> transformed = highres_map.transform(moving)
> metric = CCMetric(3)
> level_iters = [10, 10, 5]
> sdr = SymmetricDiffeomorphicRegistration(metric, level_iters)
> 
> mapping = sdr.optimize(static, moving, static_affine, moving_affine,
>                        highres_map.affine)
> warped_moving = mapping.transform(moving)
> vox_size = 1
> # Create an isocentered affine
> target_isocenter = np.diag(np.array([-vox_size, vox_size, vox_size, 1]))
> # Take the off-origin affine capturing the extent contrast between the mean B0 image and the template
> origin_affine = affine_map.affine.copy()
> origin_affine[0][3] = -origin_affine[0][3]
> origin_affine[1][3] = -origin_affine[1][3]
> 
> mni_streamlines = deform_streamlines(
>     kable.streamlines, deform_field=mapping.get_forward_field(),
>     stream_to_current_grid=target_isocenter,
>     current_grid_to_world=origin_affine, stream_to_ref_grid=target_isocenter,
>     ref_grid_to_world=np.eye(4))
> 
> std_Nifti = nib.Nifti1Image(std_im, std_affine)
> sft = StatefulTractogram(mni_streamlines, std_Nifti, Space.RASMM)
> save_tractogram(sft, 'mni-lr-superiorfrontal.trk', bbox_valid_check=False) # This returns True, meaning it was successful saving the file.
> tracks_affine, dims, voxel_szs, voxel_ords = get_reference_info(sft)
> 
> # CONFLICTIVE PART
> M, grouping = utils.connectivity_matrix(sft,tracks_affine, label_volume=atlas.astype(np.uint8), return_mapping=False, mapping_as_streamlines=False)
> ```
> 
> **OS, PYTHON & DEPENDENCIES VERSION:**
> 
> * Operating system and version: Linux-5.11.0-46-generic-x86_64-with-glibc2.17
> * Python version: Python  3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
> * dipy version: 1.4.1
> * Numpy  1.22.1
> * SciPy  1.7.3
> * Nibabel  3.2.1
> * H5Py: Not installed
> * Cvxpy: Not installed
> * fury  0.7.1
>   (Working on jupyter notebook. )

Hi, any soultion in detail to solve the problem?  how to add the streamlieans to the tractogram variabe and perfoming the registration quality checks?
