### ISSUE TITLE
MAP issue

### ISSUE THREAD

**Issue by foxet** [dipy/dipy#2500]
## Description
[Please provide a general introduction to the issue/proposal.]
I ran the code in https://dipy.org/documentation/1.4.1./examples_built/reconst_mapmri/#example-reconst-mapmri
to process my own diffusion data. But the output doesn't seem right.

Here is the output image, bvecs and bvals.

0.0       [0. 0. 0.]
200.0       [ 3.48180009e-04 -9.99954581e-01 -9.52272583e-03]
200.0       [ 0.03110844 -0.00640043 -0.99949551]
200.0       [ 0.9996106  -0.01076003  0.02574727]
400.0       [-0.70316595 -0.71081001 -0.0175163 ]
350.0       [-0.68277079 -0.00642464 -0.73060441]
400.0       [ 0.02372988 -0.71344954 -0.70030469]
400.0       [ 0.02378176  0.712053   -0.70172286]
400.0       [ 0.70311475 -0.71082491  0.0189108 ]
350.0       [ 0.7343049  -0.00642466 -0.67878938]
550.0       [-0.55537099 -0.58339208 -0.59263539]
550.0       [-0.55532855  0.5822522  -0.59379512]
550.0       [ 0.59716916 -0.58339214 -0.55049312]
550.0       [ 0.59721154  0.5822522  -0.55165279]
750.0       [ 1.57447299e-04 -9.99990702e-01 -4.30642394e-03]
750.0       [ 0.035193   -0.0050331  -0.99936783]
750.0       [ 0.99949938 -0.00536684  0.03117953]
950.0       [-0.89215833 -0.45083219 -0.02835147]
950.0       [-0.87861353 -0.00476657 -0.47750968]
950.0       [-0.44499338 -0.89545906 -0.01157728]
950.0       [-0.41462275 -0.00473653 -0.90998107]
950.0       [ 0.01569036 -0.89685941 -0.44203737]
950.0       [ 0.03162554 -0.45269731 -0.89110327]
950.0       [ 0.03165842  0.45092106 -0.89200222]
950.0       [ 0.0157556   0.89597696 -0.44382101]
950.0       [ 0.44495973 -0.89546472  0.01240334]
950.0       [ 0.48035115 -0.00473977 -0.87706345]
950.0       [ 0.89215767 -0.45083731  0.02829183]
950.0       [ 0.91131699 -0.0047629  -0.4116779 ]
1100.0       [-0.8006568  -0.41241115 -0.43458679]
1100.0       [-0.80062681  0.4116039  -0.4354066 ]
1150.0       [-0.39188367 -0.81930941 -0.41852036]
1100.0       [-0.37798244 -0.41318554 -0.82849681]
1100.0       [-0.37819222  0.41108319 -0.82944632]
1150.0       [-0.39182404  0.81850356 -0.42014974]
1150.0       [ 0.42140242 -0.81930941 -0.38878274]
1100.0       [ 0.43771255 -0.41342962 -0.79842573]
1100.0       [ 0.43774256  0.41180828 -0.79924673]
1150.0       [ 0.42146206  0.81850356 -0.39041218]
1100.0       [ 0.83049136 -0.41216639 -0.37470376]
1100.0       [ 0.83052135  0.41135955 -0.37552306]
1500.0       [-0.70487636 -0.70898139 -0.02224084]
1500.0       [-0.68153119 -0.00402451 -0.73177803]
1500.0       [ 0.02523778 -0.71063745 -0.70310557]
1500.0       [ 0.02528945  0.70923525 -0.70451814]
1500.0       [ 0.70485711 -0.70898575  0.02270808]
1500.0       [ 0.73361051 -0.00402437 -0.67955822]
1700.0       [-0.6530382 -0.669429  -0.3541269]
1700.0       [-0.64181405 -0.337212   -0.68873996]
1700.0       [-0.64196789  0.33558124 -0.68939286]
1700.0       [-0.65298957  0.66877061 -0.35545826]
1700.0       [-0.30828679 -0.66994303 -0.67537814]
1700.0       [-0.30823806  0.66862035 -0.67670983]
1700.0       [ 9.31803224e-05 -9.99996722e-01 -2.54880148e-03]
1700.0       [ 0.03594345 -0.00338214 -0.9993481 ]
1700.0       [ 0.35686672 -0.67011827 -0.65083605]
1700.0       [ 0.35691547  0.668796   -0.65216815]
1700.0       [ 0.67737341 -0.66925311 -0.30539396]
1700.0       [ 0.69078124 -0.3372111  -0.63961703]
1700.0       [ 0.69080573  0.33588749 -0.64028662]
1700.0       [ 0.67742211  0.6685949  -0.30672494]
1700.0       [ 0.99945182 -0.00298002  0.03297219]
1850.0       [-0.94716084 -0.3191641  -0.0319467 ]
1850.0       [-0.93709195 -0.0030258  -0.34906957]
1900.0       [-0.31502694 -0.94904715 -0.00821689]
1850.0       [-0.28119674 -0.00332227 -0.95964438]
1900.0       [ 0.01124274 -0.95000112 -0.31204408]
1850.0       [ 0.03411023 -0.32006919 -0.94677991]
1850.0       [ 0.03413346  0.31818223 -0.94741488]
1900.0       [ 0.01131187  0.94937754 -0.3139337 ]
1900.0       [ 0.3149932  -0.94905037  0.00909426]
1850.0       [ 0.35093278 -0.00332166 -0.93639475]
1850.0       [ 0.94717222 -0.31916806  0.03156787]
1850.0       [ 0.96012747 -0.00302442 -0.27954626]
2050.0       [-0.89265537 -0.30472818 -0.3321251 ]
2050.0       [-0.89263326  0.30413172 -0.33273083]
2050.0       [-0.289619   -0.90604866 -0.3085396 ]
2050.0       [-0.26800776 -0.30534935 -0.91374701]
2050.0       [-0.26798561  0.30355012 -0.91435277]
2050.0       [-0.28955308  0.90545404 -0.31034181]
2050.0       [ 0.31137881 -0.90604866 -0.28656426]
2050.0       [ 0.3343814  -0.30526856 -0.89162785]
2050.0       [ 0.33440354  0.30346951 -0.89223343]
2050.0       [ 0.31144473  0.90545404 -0.28836647]
2050.0       [ 0.91460311 -0.30460709 -0.26592416]
2050.0       [ 0.91462523  0.30401084 -0.26652968]
2250.0       [-0.55553049 -0.58032179 -0.59549344]
2250.0       [-0.55548829  0.57917619 -0.59664702]
2250.0       [ 0.59778398 -0.58032113 -0.55306578]
2250.0       [ 0.59782618  0.57917601 -0.55421931]
2450.0       [-0.83028978 -0.55664045 -0.02775336]
2450.0       [-0.81191009 -0.00295431 -0.58377504]
2450.0       [-0.55309689 -0.83293635 -0.0173472 ]
2400.0       [-0.52435875 -0.00311852 -0.85149175]
2450.0       [ 0.01992056 -0.83426058 -0.55101043]
2450.0       [ 0.02998101 -0.55800062 -0.82929873]
2450.0       [ 0.03002156  0.55634725 -0.83040738]
2450.0       [ 0.01998125  0.83316112 -0.55266929]
2450.0       [ 0.55293566 -0.8330276   0.01808865]
2400.0       [ 0.58529919 -0.00311822 -0.8108114 ]
2450.0       [ 0.83028078 -0.55664414  0.02794951]
2450.0       [ 0.85257506 -0.00295368 -0.52259642]
2600.0       [-0.79074991 -0.53692693 -0.2939797 ]
2600.0       [-0.78178853 -0.27052221 -0.56180465]
2600.0       [-0.78185868  0.26928654 -0.56230044]
2600.0       [-0.79071087  0.53639841 -0.29504749]
2650.0       [-0.52361286 -0.80344033 -0.28339583]
2600.0       [-0.50496739 -0.27059418 -0.81962597]
2600.0       [-0.50494772  0.26899955 -0.82016283]
2650.0       [-0.52355438  0.80291301 -0.28499392]
2600.0       [-0.24712168 -0.80395597 -0.54091191]
2600.0       [-0.23732647 -0.53782725 -0.80896103]
2600.0       [-0.23728737  0.53623384 -0.81002963]
2600.0       [-0.24706319  0.80289608 -0.54251051]
2600.0       [ 0.28598893 -0.8040427  -0.52127314]
2600.0       [ 0.29603377 -0.53773963 -0.7894302 ]
2600.0       [ 0.29607287  0.53614628 -0.79049855]
2600.0       [ 0.2860474   0.80298311 -0.52287191]
2650.0       [ 0.54305577 -0.80335319 -0.24436465]
2600.0       [ 0.56362057 -0.27056465 -0.7804656 ]
2600.0       [ 0.56364024  0.26897016 -0.78100234]
2650.0       [ 0.54311419  0.80282587 -0.24596258]
2600.0       [ 0.8101542  -0.53692496 -0.2352909 ]
2600.0       [ 0.82091689 -0.27048492 -0.5029248 ]
2600.0       [ 0.8209365   0.26942396 -0.50346196]
2600.0       [ 0.81019324  0.53639674 -0.2363587 ]
3000.0       [ 3.93585069e-04 -9.99998569e-01 -1.65428536e-03]
3000.0       [ 0.03620483 -0.00300759 -0.99933988]
3000.0       [ 0.99942362 -0.00234467  0.03386699]

Is there something wrong with my data?

![图片](https://user-images.githubusercontent.com/1968438/150246892-42b08bd9-b91d-437f-8219-15a5c9c434bb.png)

[If reporting a bug, attach the entire traceback from Python and follow the way to reproduce below]
none
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version (run `python -c "import platform; print(platform.platform())"`)
- [ ] Python version (run `python -c "import sys; print("Python", sys.version)"`)
- [ ] dipy version (run `python -c "import dipy; print(dipy.__version__)"`)
- [ ] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
    * import numpy; print("NumPy", numpy.__version__)
    * import scipy; print("SciPy", scipy.__version__)
    * import nibabel; print("Nibabel", nibabel.__version__)
    * import h5py; print("H5py", h5py.__version__)
    * import cvxpy; print("Cvxpy", cvxpy.__version__)
    * import fury; print("fury", fury.__version__)

**Comment by foxet** [comment]
I was confused and I noticed that as I shrunk the image to a smaller size, the parametric image appeared and as the image size got smaller, the more informative the image became.


data_small = data[30:59, 50:51,30:59]
size: 29,1,29

![图片](https://user-images.githubusercontent.com/1968438/150274501-bc3bb5a6-1ad0-449e-95ac-e1bc6a20c2c0.png)


data_small = data[30:54, 50:51,30:54]
size:24,1,24
![图片](https://user-images.githubusercontent.com/1968438/150274562-80b7eb64-df65-48f0-81a9-3fc33e31f75f.png)

**Comment by ShreyasFadnavis** [comment]
Hi @foxet - this seems to be related to the range of the values when plotting the data with matplotlib. You may want to control this range using vmin and vmax attributes within imshow(). 

See the plot here for instance:

[DKI Tutorial in DIPY](https://dipy.org/documentation/1.4.1./examples_built/reconst_dki/#example-reconst-dki)
