### ISSUE TITLE
kernel died when use dipy.viz

### ISSUE THREAD

**Issue by foxet** [dipy/dipy#2507]
## Description
[Please provide a general introduction to the issue/proposal.]
I'm using jupyter notebook to run example code "https://dipy.org/documentation/1.4.1./examples_built/bundle_assignment_maps/#example-bundle-assignment-maps"   in  my computer (no displayer, but I use my TV moniter to display, system: ubuntu 18 with GUI )
The kernel dies when I run  "window.record(scene, out_path='before_assignment_maps.png',size=(600, 600))"

Is there something wrong with my graphics card driver or setting?

[If reporting a bug, attach the entire traceback from Python and follow the way to reproduce below]
no traceback,just crash
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]
"https://dipy.org/documentation/1.4.1./examples_built/bundle_assignment_maps/#example-bundle-assignment-maps" 

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] window.record(scene, out_path='before_assignment_maps.png',size=(600, 600))
- [ ] Relevant images (if any)
- [ ] none
- [ ] Operating system and version (run `python -c "import platform; print(platform.platform())"`)
- [ ] Linux-4.15.0-100-generic-x86_64-with-debian-buster-sid
- [ ] Python version (run `python -c "import sys; print("Python", sys.version)"`)
- [ ] Python 3.7.6 | packaged by conda-forge | (default, Mar  5 2020, 15:27:18) GCC 7.3.0
- [] dipy version (run `python -c "import dipy; print(dipy.__version__)"`)
- 1.4.1 
- [] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
NumPy 1.18.0
SciPy 1.4.1
Nibabel 3.0.2
H5py 2.10.0
Cvxpy 1.1.0a3
fury 0.7.1

**Comment by skoudoro** [comment]
Hi @foxet,

Please, can you reformat your issue and provide the requested information? thanks
