### ISSUE TITLE
Easy robustness for streamline_near_roi and near_roi for empty streamlines?

### ISSUE THREAD

**Issue by DanNBullock** [dipy/dipy#2509]
## Description
It seems that it would be fairly easy to make [streamline_near_roi](https://github.com/dipy/dipy/blob/be956a529465b28085f8fc435a756947ddee1c89/dipy/tracking/utils.py#L674-L724) and [near_roi](https://github.com/dipy/dipy/blob/be956a529465b28085f8fc435a756947ddee1c89/dipy/tracking/utils.py#L727-L796) robust against various forms of empty streamline inputs.  Is there an intentional desire / design decision that precludes this possibility?

An example of how to implement this would be to use np.any, as demonstrated [here](https://github.com/DanNBullock/dipy/blob/1490492e3f9929a8e28bc682358b957fc8dda328/dipy/tracking/utils.py#L706-L707)

## Way to reproduce
I've implemented tests for this solution in [test_utils here](https://github.com/DanNBullock/dipy/blob/1490492e3f9929a8e28bc682358b957fc8dda328/dipy/tracking/tests/test_utils.py#L347-L359),

However, in a likely unrelated (and possibly local) issue, my current local tests are indicating that the tests associated with the end options "both_end" and "either_end" are returning unexpected results for the *already existing* tests.  The tests specific to this modification seem to be fine.

## Additional notes

- There may be a potential weird edge case, if *literally* every coordinate of every streamline node is 0 (due to the behavior of np.any()), but I would expect such a case to be impossible under normal circumstances (I would not expect a singleton node at 0,0,0).

## Justification / Use case

The suggested modification might be useful for users who may wish to subset (via some criterion) the streamline nodes that that are being passed to streamline_near_roi.  Such an option would reduce the footprint of subsequent cdist computations, in some cases substantially.

An example of such an application would be in the[ implementation of a faster near_roi function, as prototyped here](https://github.com/DanNBullock/wma_pyTools/blob/ee0f96b99f548f661633db0f4cf9068acc90c340/wmaPyTools/segmentationTools.py#L267-L409).  In this example, nodes outside of the ROI bounding box are not passed to streamlines_near_roi, reducing the computation's footprint.  However, this sometimes (or even often) results in passing "empty" streamlines (streamlines with no nodes, as they all occur outside the bounding box).

There may be a desire to implicitly not support the use of such degenerate streamlines, or collections of streamlines which include these.  Pre-subsetting the input streamline collection using list comprehension (e.g. [iStreamlines if iStreamlines for iStreamlines in streamlines]) would not work as this would alter the index sequencing of streamlines (by dropping "empty" streamlines).  Alternatively, it may be possible to do something like:

[streamline_near_roi(iStreamlines, x_roi_coords, tol=tol, mode=mode) if iStreamlines else False for iStreamlines in streamlines]

but this would require the user working around  or outside the current implementation of [near_roi](https://github.com/dipy/dipy/blob/54324e5acd6f790d62294d43e150c48be94cb573/dipy/tracking/utils.py#L786) to achieve this same functionality, rather than it being inherent to streamline_near_roi itself.

**Comment by skoudoro** [comment]
Thank you for this detailed issue. I might be wrong but I do not think there is an intentional desire to keep empty streamline in such functions. 

So, I think, this update would be good.

But I would like the opinion of @Garyfallidis @arokem @gabknight @BramshQamar

**Comment by arokem** [comment]
+1 sounds like an improvement to me!

**Comment by DanNBullock** [comment]
Sounds like it might be viable from the responses I'm getting here.

@arokem insfoar as updating the test_utils for this, should I just create a separate block of tests (distinct from the existing tests) for [various forms of blank inputs like this](https://github.com/DanNBullock/dipy/blob/1490492e3f9929a8e28bc682358b957fc8dda328/dipy/tracking/tests/test_utils.py#L347-L351)?  My current version of the test_utils is probably a bit messier than it ought to be, and I think a separate block may be the preferable design choice.

**Comment by skoudoro** [comment]
Closed by #2515
