### ISSUE TITLE
slr_with_qbx breaks when bundle has only one streamline

### ISSUE THREAD

**Issue by BramshQamar** [dipy/dipy#2530]
In **slr_with_qbx** function, https://github.com/dipy/dipy/blob/f234810ad388323aad095a71e3b22383123c48c2/dipy/align/streamlinear.py#L852 **rm_small_clusters** is set to 50 by default https://github.com/dipy/dipy/blob/f234810ad388323aad095a71e3b22383123c48c2/dipy/align/streamlinear.py#L854

The function removes clusters of less than 50 streamlines before performing the registration. In case someone has a very thin bundle or bundle with only one streamline, this function breaks. 

I propose we set the default value to 0 and users can change when they are performing registration of whole-brain tractograms or big bundles like CC. We can set the default value of **rm_small_clusters** to 50 for **whole_brain_slr** function and not for the **slr_with_qbx** function. https://github.com/dipy/dipy/blob/f234810ad388323aad095a71e3b22383123c48c2/dipy/align/streamlinear.py#L1015

**Comment by skoudoro** [comment]
closed by #2540
