### ISSUE TITLE
DTI workflow should allow user-defined fitting method

### ISSUE THREAD

**Issue by GalBenZvi** [dipy/dipy#2542]
## Description
Currently, it seems that the DTI reconstruction workflow (ReconstDtiFlow) uses only the "WLS" fitting method, although other methods are available through DIPY.

It should be quite easy to add the fitting method as a keyword with a default value of "WLS" rather than forcing it.

I think it's worth it especially due to the exemplary results described in [the relevant tutorial](https://dipy.org/documentation/1.4.1./examples_built/restore_dti/#example-restore-dti)

## Way to reproduce
```python
from dipy.workflows.reconst import ReconstDtiFlow
ReconstDtiFlow.run(..., fit_method="RESTORE")
```

**Comment by GalBenZvi** [comment]
Sorry, I just saw that this issue has already been addressed and this functionality is present under the *master* branch, although it isn't published (which is why I couldn't see it under my pip-installable dipy package.

**Comment by skoudoro** [comment]
Hi @GalBenZvi,

We plan to release this week, so this functionality will be available next week

**Comment by GalBenZvi** [comment]
Hi @skoudoro,
First of all - thank you for the prompt reply!

After playing around with this workflow, I noticed something that may be a bug (?):
When choosing "RESTORE" as the fitting method, the workflow fails to run as it requires a noise estimation ("sigma").

I'm wondering if "sigma" should be an input in the "run" method or rather computed automatically as part of the workflow?
