### ISSUE TITLE
StatefulTractogram.are_compatible compare data_per_point keys as list instead of set

### ISSUE THREAD

**Issue by NotaCS** [dipy/dipy#2543]
## Description
Using `StatefulTractogram.are_compatible(sft1, sft2)` to check if two sft are compatible returns `False` if the keys in data_per_point are the same but not in the same order.

## Easy fix
Line 160 of dipy/io/stateful_tractogram.py
Change
`if sft_1.get_data_per_point_keys() != sft_2.get_data_per_point_keys():`
to
`if set(sft_1.get_data_per_point_keys()) != set(sft_2.get_data_per_point_keys()):`

(and it's probably the same with lines 164-165 `sft_1.get_data_per_streamline_keys() != sft_2.get_data_per_streamline_keys()`)

**Comment by NotaCS** [comment]
The fix proposed by @frheault works well in my case (don't forget to modify the docstrings too).

However, I'm afraid that it might break some codes if people were indexing the results from get_data_per_point_keys and get_data_per_streamline_keys. I'm not sure why someone would want to do that, but who knows...

I do think it makes more sense that they return a set (as is proposed in the fix), though. It is a choice between retro-compatibility (maybe) and proper type for a given object. Your call.

**Comment by skoudoro** [comment]
Closed by https://github.com/dipy/dipy/pull/2545
