### ISSUE TITLE
Confusing import in 'reconst_sh`

### ISSUE THREAD

**Issue by gabknight** [dipy/dipy#2546]
## Description
In the ['reconst_sh](https://dipy.org/documentation/1.4.0./examples_built/reconst_sh/) example, the code start with `from gradients_spheres import sph`. This is confusing for new users as the import cannot be run in a python terminal (except if you are in the example folder). `sph` should be replaced with low-resolution standard DIPY `Sphere` for clarity.

**Comment by skoudoro** [comment]
Thank you for the feedback, Good catch, this is the second tutorial with this issue
