### ISSUE TITLE
CLI denoise patch_size error

### ISSUE THREAD

**Issue by slieped** [dipy/dipy#2559]
## Description
To update CLI documentation.

When doing a CLI call for dipy denoise methods, if patch size is not provided with 3 values, the cmd return an ValueError.
This differ from what is written in the documentation  (https://dipy.org/documentation/1.4.1./interfaces/denoise_flow/#denoising-using-marcenko-pastur-pca)

## Info
DIPY version: 1.4.1

## Way to reproduce
CMD call that return error
dipy_denoise_mppca sub-002S6652_ses-m12_dwi.nii   --out_dir dwipreproc1.0.0  --patch_radius 3

CMD call that works
dipy_denoise_mppca sub-002S6652_ses-m12_dwi.nii   --out_dir dwipreproc1.0.0  --patch_radius 3 3 3

## Solution
Update CLI documentation. Both dipy_denoise_mppca  && dipy_denoise_nlmeans

**Comment by skoudoro** [comment]
Hi @slieped,

Thank you for the feedback. 

This is a bug since it should work with both cases. we will look into it.
