### ISSUE TITLE
compress_streamlines() not available anymore

### ISSUE THREAD

**Issue by wasserth** [dipy/dipy#2565]
Using dipy 1.5.0 I get an error when trying to import compress_streamline:

```
from dipy.tracking.streamline import compress_streamlines
``` 

results in the following error
```
ImportError: cannot import name 'compress_streamlines' from 'dipy.tracking.streamline'
```

Where did this method move to? I did not find any information regarding this function in the changelog.

**Comment by Garyfallidis** [comment]
Let us know if that worked @wasserth !

**Comment by wasserth** [comment]
That is working.
Is it stable to change my code to `from dipy.tracking.streamlinespeed import compress_streamlines` ?

Maybe it is related to this commit: https://github.com/dipy/dipy/commit/c5eb6283754860576aac091decf8f24ae03cf8c9
But when installing dipy from the newest master I get the same error as with 1.5.0

**Comment by Garyfallidis** [comment]
Yes it is stable to import directly from ``streamlinespeed``. @skoudoro may know why importing from streamline did not work. I do confirm that I got the same error in my system Ubuntu 20.04 with Python 3.8.

**Comment by skoudoro** [comment]
The change seems to be from July 2019 so quite old. it looks like it was just a pep8 issue.  `compress_streamlines` was not used in the `streamline` package.  so it was part of cleaning the codebase.

I am surprised you did not get the error before since we had many releases since July 2019

**Comment by wasserth** [comment]
I experienced the same problem for the following import (using dipy 1.5.0).
`from dipy.segment.metric import ResampleFeature` results in an import error.  
`from dipy.segment.featurespeed import ResampleFeature` is working.

**Comment by skoudoro** [comment]
> I experienced the same problem for the following import (using dipy 1.5.0).
from dipy.segment.metric import ResampleFeature results in an import error.
from dipy.segment.featurespeed import ResampleFeature is working.

Yes, this has changed on DIPY 1.5.0. I need to check if it is present on the API CHANGES notes of the release. 
So this is normal behavior.

**Comment by skoudoro** [comment]
Closing, feel free to reopen if you have any other questions
