### ISSUE TITLE
Cannot Import "Feature" From "dipy.segment.metric"

### ISSUE THREAD

**Issue by junwei0001** [dipy/dipy#2573]
Hi,

When I was trying to import "Feature" from the module "dipy.segment.metric", an error was reported as attachment. 

Thank you so much for the help!

<img width="995" alt="WX20220407-021539@2x" src="https://user-images.githubusercontent.com/98662392/162141937-0c62764a-fcf6-48d4-af77-701da5b8282a.png">

**Comment by skoudoro** [comment]
Hi @junwei0001,

you need to use `from dipy.segment.featurespeed import Feature` instead. 

This has changed from the last release. You can check the release notes.

related to #2565.

Closing.

**Comment by junwei0001** [comment]
> Hi @junwei0001,
> 
> you need to use `from dipy.segment.featurespeed import Feature` instead.
> 
> This has changed from the last release. You can check the release notes.
> 
> related to #2565.
> 
> Closing.

That works. Thank you so much!
