### ISSUE TITLE
Thread safety concerns with reliance on `nibabel.tmpdirs.InTemporaryDirectory`

### ISSUE THREAD

**Issue by jacobdr** [dipy/dipy#2587]
## Description

We hit an issue specifically in the [`read_bvals_bvecs`](https://github.com/dipy/dipy/blob/master/dipy/io/gradients.py#L9) implementation where dipy farms out to nibabel's [`InTemporaryDirectory`](https://github.com/nipy/nibabel/blob/a8382384ca24564719ca9bc03488226733c3f2ec/nibabel/tmpdirs.py)

Reading through the nibabel source code its doing some quite sketchy things like:

```python
self._pwd = os.getcwd()
os.chdir(self.name)
```

which seem quite unfriendly toward multithreaded applications.

dipy isn't doing anything fancy at all -- it just needs a tempfile -- so I think switching to the [standard library way](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryFile) would be a safe change to make

## Way to reproduce

- Python version: 3.7.12
- dipy version:  this impacts from at least 0.16.0 to 1.5.0

I can work on a reproduction but logically since Python threads share a single process and `os.chdir` operates at the process level, conceptually I think its obvious nibabel is making some bad assumptions

**Comment by arokem** [comment]
+1 good call! 

Do you want to propose a change in a PR?

**Comment by jacobdr** [comment]
I can take a crack at that -- how invasive do you feel comfortable with me going? Removing all references to `InTemporaryDirectory`?

**Comment by arokem** [comment]
A lot of these are probably in test code. I don't think we need to change those: 

From `git grep InTemporaryDirectory`: 

```
dipy/align/tests/test_api.py:    with nbtmp.InTemporaryDirectory() as tmpdir:
dipy/align/tests/test_api.py:    with nbtmp.InTemporaryDirectory() as tmpdir:
dipy/align/tests/test_api.py:    with nbtmp.InTemporaryDirectory() as tmpdir:
dipy/direction/peaks.py:from nibabel.tmpdirs import InTemporaryDirectory
dipy/direction/peaks.py:    with InTemporaryDirectory() as tmpdir:
dipy/io/gradients.py:from nibabel.tmpdirs import InTemporaryDirectory
dipy/io/gradients.py:            with InTemporaryDirectory():
dipy/io/tests/test_dpy.py:from nibabel.tmpdirs import InTemporaryDirectory
dipy/io/tests/test_dpy.py:    with InTemporaryDirectory():
dipy/io/tests/test_io_gradients.py:from nibabel.tmpdirs import InTemporaryDirectory
dipy/io/tests/test_io_gradients.py:    with InTemporaryDirectory():
dipy/io/tests/test_io_peaks.py:from nibabel.tmpdirs import InTemporaryDirectory
dipy/io/tests/test_io_peaks.py:    with InTemporaryDirectory():
dipy/io/tests/test_io_peaks.py:    with InTemporaryDirectory():
dipy/io/tests/test_stateful_tractogram.py:from nibabel.tmpdirs import InTemporaryDirectory
dipy/io/tests/test_stateful_tractogram.py:    with InTemporaryDirectory():
dipy/io/tests/test_stateful_tractogram.py:    with InTemporaryDirectory():
dipy/io/tests/test_stateful_tractogram.py:    with InTemporaryDirectory():
dipy/io/tests/test_stateful_tractogram.py:    with InTemporaryDirectory():
dipy/io/tests/test_stateful_tractogram.py:        with InTemporaryDirectory():
dipy/io/tests/test_stateful_tractogram.py:        with InTemporaryDirectory():
dipy/io/tests/test_stateful_tractogram.py:        with InTemporaryDirectory():
dipy/io/tests/test_streamline.py:from nibabel.tmpdirs import InTemporaryDirectory
dipy/io/tests/test_streamline.py:    with InTemporaryDirectory():
dipy/io/tests/test_streamline.py:    with InTemporaryDirectory():
dipy/io/tests/test_streamline.py:        with InTemporaryDirectory():
dipy/io/tests/test_streamline.py:        with InTemporaryDirectory():
dipy/tests/test_scripts.py:from nibabel.tmpdirs import InTemporaryDirectory
dipy/tests/test_scripts.py:    with InTemporaryDirectory():
dipy/tests/test_scripts.py:    with InTemporaryDirectory():
dipy/tests/test_scripts.py:    with InTemporaryDirectory():
dipy/tests/test_scripts.py:    with InTemporaryDirectory():
```

I think the only two places that need to be changed is in `dipy/direction/peaks.py` and the one you mention here.

**Comment by jacobdr** [comment]
I also opened up a ticket against the upstream -- https://github.com/nipy/nibabel/issues/1102

**Comment by effigies** [comment]
Agreed that this shouldn't be used in non-test code. It's unclear what the problem would be in test code; pytest's parallel runners are multiprocessing-based, not multithreading. I suppose everybody could move to pytest fixtures, though that sets up another chore when pytest eventually goes the way of nose...

**Comment by arokem** [comment]
Thanks for your input @effigies! Following your advice, I think that we can leave this in the tests, but should change this in the non-test code (as proposed in #2589)
