### ISSUE TITLE
Update cmd_line dipy_fit_dti

### ISSUE THREAD

**Issue by skoudoro** [dipy/dipy#2662]
Small reminder from gitter:

> Hi, I find a small mistake in Documentation 1.5.0 dipy_fit_dti
https://dipy.org/documentation/1.5.0/reference_cmd/dipy_fit_dti/ , in which some optional arguments(sigma, b0_threshold, bvecs_tol) didn't match the explanation. By the way, it will be much better if user can define the order of tensor. Thank you for your outstanding work!

**Comment by jhlegarreta** [comment]
> By the way, it will be much better if user can define the order of tensor. Thank you for your outstanding work!

@Nanyiliyuan What do you mean by order in this context? The DTI fit always produces a rank-2 tensor; there is no such an order parameter to the method. Higher order tensors would correspond to other models, such as DKI, and they require another set of fitting methods, and therefore, are provided under different workflow names, (e.g. `dipy_fit_dki` for DKI).

**Comment by Nanyiliyuan** [comment]
I'm sorry, maybe I didn't express myself clearly. What I really mean is that 'dipy_fit_dti'  implements a custom tensor output order, such as Dxx, Dyy, Dzz, Dxy, Dyz, Dxz, or some other order.
In addition, it will be better to be able to estimate and return s0_hat in 'dipy_fit_dti'. 
And in the code of DTI tensor fitting: 
tenmodel = dti.TensorModel(gtab) 
tenfit = tenmodel.fit(dti_data)
tenfit has all kinds of useful quantitative parameters in it. But unfortunately, there is no return diffusion tensor.
Thank you very much for your reply!

**Comment by jhlegarreta** [comment]
> What I really mean is that 'dipy_fit_dti' implements a custom tensor output order, such as Dxx, Dyy, Dzz, Dxy, Dyz, Dxz, or some other order.

Why do you think that being able to get those values sorted differently would be advantageous? I do not see it.
