### ISSUE TITLE
Defaults for Patch2Self

### ISSUE THREAD

**Issue by araikes** [dipy/dipy#2667]
Hi @skoudoro and @ShreyasFadnavis,

Question about Patch2Self (and particularly the CLI implementation). I was reading another thread from a bit ago (#2334) about needing to do both the intensity shifting and negative clipping to better ensure that voxels have a value. Looking at both the definition, it appears that the defaults are to `shift_intensity` but not `clip_negatives`. However, the help for the function indicates that the defaults are to clip negatives but not shift_intensity.

https://github.com/dipy/dipy/blob/1c2ac3857b30bb4862884084591a62347411078a/dipy/denoise/patch2self.py#L165-L168

https://github.com/dipy/dipy/blob/1c2ac3857b30bb4862884084591a62347411078a/dipy/denoise/patch2self.py#L213-L215

https://github.com/dipy/dipy/blob/1c2ac3857b30bb4862884084591a62347411078a/dipy/denoise/patch2self.py#L217-L220

So, with all of this in mind, is it possible to set both of those options on the CLI? I am assuming that based on the function definition that it is running the shift but not the clip.

Thanks

**Comment by jhlegarreta** [comment]
@araikes
- See PR #2669 for the documentation issue.
- See PR #2670 for the additional options being exposed in the CLI.

**Comment by araikes** [comment]
Thanks @jhlegarreta

**Comment by araikes** [comment]
@skoudoro, is there a timeline on the 1.6 release? I would like to use this CLI fix and don't mind pulling in the master off here but if 1.6 is imminent, I'll just wait.

Thanks

**Comment by skoudoro** [comment]
it is imminent @araikes. Thank you for asking

**Comment by araikes** [comment]
Sounds good. I'll go ahead and be patient then :)
