### ISSUE TITLE
Problems with a .nii.gz file when loading and floating

### ISSUE THREAD

**Issue by ggomezji** [dipy/dipy#2679]
## Description
I am trying to plot and load a .nii.gz file and every time I run the lines I obtain the next error:

> AttributeError: 'tuple' object has no attribute 'startswith'
<img width="1044" alt="Screenshot 2022-11-18 at 16 55 36" src="https://user-images.githubusercontent.com/118550984/202746970-84d05589-bc4f-43aa-bf1f-0989747f2b13.png">

The lines I run are either: 

> plot_roi("path/file.nii.gz")

or

> imgMask=nib.load("path/file.nii.gz")

Both of the lines give me the same error. However, when I run them with another file with same extension both lines work perfectly. The only thing I compute before those commands are the libraries I am going to use in the project.

I don't know what can be the problem the file that gives me problems was sent by my supervisor through mattermost while the other file that works was cloned from a remote server to my local computer. Also, the file that gives me problems, is stored in the same file as I have my project created, while the  other one that works fine is stored in a different folder  with other data (the problem doesn't seem to be the path though).

My supervisor can work perfectly withe the file (he has also tried the downloaded version and still works), however I cannot and when I send the file to a colleague and she tries to run the same lines, she cannot either.

We've checked the versions of Nilearn and nibabel to check if they are correct and that's not neither the problem. I've also checked the version of the packages I am using and doesn't seem to be that. I don't know how to solve that problem.

**Comment by skoudoro** [comment]
Hi @ggomezji,

thank you for asking. However, I do not think it is related to DIPY.  

Also, without a complete code, we can not help (what is `plot_roi` ? not in DIPY).

I recommend you to ask this question in https://neurostars.org/  which will be much more helpful for you in this particular case.

Good luck, closing
