### ISSUE TITLE
FYI: Deprecating nisext in nibabel

### ISSUE THREAD

**Issue by effigies** [dipy/dipy#2706]
The nisext tools are obsolete and unmaintained, so we are planning on deprecating them. AFAIK the only place they are still used is the dipy Makefile:

https://github.com/dipy/dipy/blob/089a02ad0520895bd30370591f965c685293e480/Makefile#L80-L97

Do you all still use these, or are they cruft? We can probably help with alternative implementations using modern build tools, if needed.

This is not urgent; we will be raising a `DeprecationWarning` in the next release, but the tools will remain for another year at least (until 6.0).

**Comment by skoudoro** [comment]
Thank you for the feedback @effigies. 

We planned to remove this part, so at least, now, we have a deadline. 😄

**Comment by shilpiprd** [comment]
I'm sorry, but what is needed to be done in PR for this issue? 
Are we supposed to create a deadline warning  like warn(...) or a deprecation warning like @deprecated_params( ... , None, since='1.17', until='1.19') ?

**Comment by skoudoro** [comment]
No worries @shilpiprd, I will take care of this part.

**Comment by shilpiprd** [comment]
Oh, ok sure.
