### ISSUE TITLE
Provide the dataset of this code

### ISSUE THREAD

**Issue by Paluck1Arora2** [dipy/dipy#2708]
Can anyone please provide the dataset of this code "https://github.com/sarathknv/voxelmorph"
data = np.load('drive/My Drive/DIPY/brain_affine_128.npy')
static = np.load('drive/My Drive/DIPY/static.npy')
These lines are mention in voxelmorph.ipynb file

data = np.load('data/t1_moving_128.npy')
static = np.load('data/t1_static_128.npy')
These lines are mention in main.py

**Comment by jhlegarreta** [comment]
@Paluck1Arora2 you'll need to ask @sarathknv. Maybe opening an issue in the repository you linked as a last resource:
https://github.com/sarathknv/voxelmorph

Note that those data do not belong to or dwell in any resource managed by the DIPY team: those are files that @sarathknv hosted in their own resources.

The data the Voxelmorph authors originally used is made available in the original repository:
https://github.com/voxelmorph/voxelmorph/tree/dev/data

NumPy will be able to load the npz files without trouble.

Also, you may use any other T1-weighted NIfTI data/NumPy files to test the Voxelmorph method. The ones used are just to demonstrated the method. It should generalize reasonably well to any other data of your choice (unless authors mention limitations or constraints in their paper).

Hope this helps.

Closing the issue.

**Comment by Paluck1Arora2** [comment]
Hi sir,
I have checked many datasets of T1 weighted and T2 weighted but didn't get
more than one static image in the dataset. Can you please help me. You have
done a lot of work in this area. Kindly resolve this issue.
This is the dataset which I have worked on.
https://www.kaggle.com/code/yeonghyeon/convert-dicom-to-numpy-array-super-simple/data

**Comment by jhlegarreta** [comment]
> I have checked many datasets of T1 weighted and T2 weighted but didn't get
more than one static image in the dataset. 

Not sure I understand. T1 or T2 NIfTI files contain a _single_ image volume.

> This is the dataset which I have worked on.
> https://www.kaggle.com/code/yeonghyeon/convert-dicom-to-numpy-array-super-simple/data

I am not familiar with the data, but from the sizes and the name of the challenge, these are T1 or T2 images, and you should be able to download each dataset and use them for your registration purposes. Go through the notebook to familiarize yourself with the data or to learn how to manipulate it:
https://www.kaggle.com/code/yeonghyeon/convert-dicom-to-numpy-array-super-simple/notebook
