### ISSUE TITLE
DiffeomorphicMap object on github not the same as recent release

### ISSUE THREAD

**Issue by sportnoah14** [dipy/dipy#2709]
Hi,

I'm hoping to use the ANTs registration algorithm and I'm getting it to work. However, I'd like to use the `transform_points()` method for the `DiffeomorphicMap`. I see it's on github under dipy/align/imwarp.py but I don't have that function when I install dipy via conda or pip. Any idea why that is? Would I have to install dipy via github master branch to have this function? Please let me know when you get a chance. Thank you in advance.

**Comment by skoudoro** [comment]
Hi @sportnoah14,

Yes, it is normal. This feature will be on the next release (DIPY 1.16). When you install DIPY via pip or conda, it installs the version 1.15.  

For now, if you need it, using master branch is the only way.
