### ISSUE TITLE
Numpy Version Incompatibility, AttributeError in dipy.align

### ISSUE THREAD

**Issue by gnee-git** [dipy/dipy#2729]
## Description
I've started testing dipy for PET image registration. In attempting to use dipy.align.affine_registration, I came across a version incompatibility with numpy (AttributeError due to typeDict being phased out). Can't see this reported elsewhere from a cursory issue search so thought I'd just share.

Versions...
dipy: 1.6.0
numpy: 1.24.2
python: 3.8.11
System: Windows-10-10.0.19042-SP0

Code: (largely taken from dipy examples)
```
from dipy.align import affine_registration
from dipy.io import load_nifti
folder = "D:/Hoffman/NiftiImages_PET"
pipeline = ["center_of_mass", "translation", "rigid", "affine"]

static_data, static_affine, static_img = load_nifti(os.path.join(folder, 'Aberdeen_01.nii'),return_img=True)
static = np.squeeze(static_data)[..., 0]
static_grid2world = static_affine

moving_data, moving_affine, moving_img = load_nifti(os.path.join(folder, 'Aberdeen_02.nii'),return_img=True)
moving = np.squeeze(moving_data)[..., 0]
moving_grid2world = moving_affine

xformed_img, reg_affine = affine_registration(
    moving, static,
    moving_affine = moving_grid2world,
    static_affine = static_grid2world,
    nbins = 32,
    metric = "MI",
    pipeline = pipeline,
    level_iters = [10000, 1000, 100],
    sigmas = [3.0, 1.0, 0.0],
    factors = [4, 2, 1]
)
```

Error message:

AttributeError                            Traceback (most recent call last)
d:\Hoffman\GN\Notebooks\Book2_CT_ROI_Analysis_Feb23.ipynb Cell 20 in <cell line: 1>()
----> [1](vscode-notebook-cell:/d%3A/Hoffman/GN/Notebooks/Book2_CT_ROI_Analysis_Feb23.ipynb#X24sZmlsZQ%3D%3D?line=0) from dipy.align import affine_registration
      [2](vscode-notebook-cell:/d%3A/Hoffman/GN/Notebooks/Book2_CT_ROI_Analysis_Feb23.ipynb#X24sZmlsZQ%3D%3D?line=1) from dipy.io import load_nifti
      [3](vscode-notebook-cell:/d%3A/Hoffman/GN/Notebooks/Book2_CT_ROI_Analysis_Feb23.ipynb#X24sZmlsZQ%3D%3D?line=2) folder = "D:/Hoffman/NiftiImages_PET"

File c:\Work\Anaconda3\lib\site-packages\dipy\align\__init__.py:27, in <module>
     16 VerbosityLevels = Bunch(NONE=0, STATUS=1, DIAGNOSE=2, DEBUG=3)
     17 r""" VerbosityLevels
     18 This enum defines the four levels of verbosity we use in the align
     19 module.
   (...)
     24 DEBUG : print as much information as possible to isolate the cause of a bug.
     25 """
---> 27 from dipy.align._public import (syn_registration, register_dwi_to_template, # noqa
     28                                 write_mapping, read_mapping, resample,
     29                                 center_of_mass, translation,
     30                                 rigid_isoscaling, rigid_scaling,
     31                                 rigid, affine, motion_correction,
     32                                 affine_registration, register_series,
     33                                 register_dwi_series, streamline_registration)
     35 __all__ = ["syn_registration", "register_dwi_to_template",
     36            "write_mapping", "read_mapping", "resample",
     37            "center_of_mass", "translation",
...
    318     return Tester
--> 320 raise AttributeError("module {!r} has no attribute "
    321                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'typeDict'

**Comment by arokem** [comment]
Hi @gnee-git : thanks for reporting this. I don't understand the stack trace you provided. 

In particular, what is in the `...` between line 37 and line 318 in this part of your trace? 

```
37 "center_of_mass", "translation",
...
318 return Tester
```

I am not sure where the error is emerging (I don't think that our code is directly using `typeDict`), and knowing a bit more about the stack trace might help.

**Comment by skoudoro** [comment]
The last release of Numpy is called `a deprecation release`.  One of the Highlights is `Many expired deprecations`.

we might have miss that. Looks like `Tester` is not anymore on Numpy or in a different level.

For us @arokem, Looks like we need to do a maintenance release soon. 

For you @gnee-git, a quick fix is to downgrade your Numpy version. use the 1.23, it should be ok.

**Comment by skoudoro** [comment]
ok, it seems to be something else after several tests. I still do not know why. 

my last comment is not valid for numpy 1.24.5. it should work. 

it will fail with the future numpy 1.25 following this PR https://github.com/numpy/numpy/pull/23041


also @gnee-git  `from dipy.io import load_nifti`  do not work for me.   the correct import is `from dipy.io.image import load_nifti`.  Can it be the reason of your issue? mixed environment ?

**Comment by lb-97** [comment]
Hi @gnee-git,
I retried your code(with the above import change by @skoudoro) with below library versions:
Numpy - 1.24.2
dipy - 1.6.0
Python - 3.8.10

I could successfully produce affine transformations. Could you please post the full trace of the error?

**Comment by gnee-git** [comment]
Hi all,

I tried this again with old package versions, still getting the same response (with updated import change as @skoudoro , @lb-97 )

Here's the full error (apologies - didn't see it cropped the previous one!)

```
from dipy import __version__ as dipy_version
import numpy as np
import sys

print("Using dipy version: ", dipy_version)
print("Using numpy version: ", np.__version__)
print("Using python version: ", sys.version)

from dipy.align import affine_registration
from dipy.io.image import load_nifti

folder = "D:/Hoffman/NiftiImages_PET"
pipeline = ["center_of_mass", "translation", "rigid"]

static_data, static_affine, static_img = load_nifti(os.path.join(folder, 'Aberdeen_01.nii'),return_img=True)
static = np.squeeze(static_data)[..., 0]
static_grid2world = static_affine

moving_data, moving_affine, moving_img = load_nifti(os.path.join(folder, 'Aberdeen_02.nii'),return_img=True)
moving = np.squeeze(moving_data)[..., 0]
moving_grid2world = moving_affine

xformed_img, reg_affine = affine_registration(
    moving, static,
    moving_affine = moving_grid2world,
    static_affine = static_grid2world,
    nbins = 32,
    metric = "MI",
    pipeline = pipeline,
    level_iters = [10000, 1000, 100],
    sigmas = [3.0, 1.0, 0.0],
    factors = [4, 2, 1]
)

```

Response:


_Using dipy version:  1.6.0
Using numpy version:  1.24.2
Using python version:  3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)]
[c:\Work\Anaconda3\lib\site-packages\dicom\__init__.py:53](file:///C:/Work/Anaconda3/lib/site-packages/dicom/__init__.py:53): UserWarning: 
This code is using an older version of pydicom, which is no longer 
maintained as of Jan 2017.  You can access the new pydicom features and API 
by installing `pydicom` from PyPI.
See 'Transitioning to pydicom 1.x' section at pydicom.readthedocs.org 
for more information.

  warnings.warn(msg)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
d:\Hoffman\GN\Notebooks\Book2_CT_ROI_Analysis_Feb23.ipynb Cell 22 in <cell line: 9>()
      [6](vscode-notebook-cell:/d%3A/Hoffman/GN/Notebooks/Book2_CT_ROI_Analysis_Feb23.ipynb#X30sZmlsZQ%3D%3D?line=5) print("Using numpy version: ", np.__version__)
      [7](vscode-notebook-cell:/d%3A/Hoffman/GN/Notebooks/Book2_CT_ROI_Analysis_Feb23.ipynb#X30sZmlsZQ%3D%3D?line=6) print("Using python version: ", sys.version)
----> [9](vscode-notebook-cell:/d%3A/Hoffman/GN/Notebooks/Book2_CT_ROI_Analysis_Feb23.ipynb#X30sZmlsZQ%3D%3D?line=8) from dipy.align import affine_registration
     [10](vscode-notebook-cell:/d%3A/Hoffman/GN/Notebooks/Book2_CT_ROI_Analysis_Feb23.ipynb#X30sZmlsZQ%3D%3D?line=9) from dipy.io.image import load_nifti
     [12](vscode-notebook-cell:/d%3A/Hoffman/GN/Notebooks/Book2_CT_ROI_Analysis_Feb23.ipynb#X30sZmlsZQ%3D%3D?line=11) folder = "D:/Hoffman/NiftiImages_PET"

File c:\Work\Anaconda3\lib\site-packages\dipy\align\__init__.py:27, in <module>
     16 VerbosityLevels = Bunch(NONE=0, STATUS=1, DIAGNOSE=2, DEBUG=3)
     17 r""" VerbosityLevels
     18 This enum defines the four levels of verbosity we use in the align
     19 module.
   (...)
     24 DEBUG : print as much information as possible to isolate the cause of a bug.
     25 """
---> 27 from dipy.align._public import (syn_registration, register_dwi_to_template, # noqa
     28                                 write_mapping, read_mapping, resample,
     29                                 center_of_mass, translation,
     30                                 rigid_isoscaling, rigid_scaling,
     31                                 rigid, affine, motion_correction,
     32                                 affine_registration, register_series,
     33                                 register_dwi_series, streamline_registration)
     35 __all__ = ["syn_registration", "register_dwi_to_template",
     36            "write_mapping", "read_mapping", "resample",
     37            "center_of_mass", "translation",
   (...)
     40            "affine_registration", "register_series",
     41            "register_dwi_series", "streamline_registration"]

File c:\Work\Anaconda3\lib\site-packages\dipy\align\_public.py:31, in <module>
     19 from dipy.align.imaffine import (transform_centers_of_mass,
     20                                  AffineMap,
     21                                  MutualInformationMetric,
     22                                  AffineRegistration)
     24 from dipy.align.transforms import (TranslationTransform3D,
     25                                    RigidTransform3D,
     26                                    RigidScalingTransform3D,
     27                                    RigidIsoScalingTransform3D,
     28                                    AffineTransform3D)
---> 31 import dipy.core.gradients as dpg
     32 import dipy.data as dpd
     33 from dipy.align.streamlinear import StreamlineLinearRegistration

File c:\Work\Anaconda3\lib\site-packages\dipy\core\gradients.py:7, in <module>
      4 import numpy as np
      5 from scipy.linalg import inv, polar
----> 7 from dipy.io import gradients as io
      8 from dipy.core.onetime import auto_attr
      9 from dipy.core.geometry import vector_norm, vec2vec_rotmat

File c:\Work\Anaconda3\lib\site-packages\dipy\io\__init__.py:4, in <module>
      1 # init for io routines
      3 from .gradients import read_bvals_bvecs
----> 4 from .dpy import Dpy
      5 from .bvectxt import (read_bvec_file, ornt_mapping, reorient_vectors,
      6                       reorient_on_axis, orientation_from_string,
      7                       orientation_to_string)
      8 from .pickles import save_pickle, load_pickle

File c:\Work\Anaconda3\lib\site-packages\dipy\io\dpy.py:12, in <module>
      1 """ A class for handling large tractography datasets.
      2 
      3     It is built using the h5py which in turn implement
   (...)
      8     .. [1] http://www.hdfgroup.org/HDF5/doc/H5.intro.html
      9 """
     11 import numpy as np
---> 12 import h5py
     14 from nibabel.streamlines import ArraySequence as Streamlines
     16 # Make sure not to carry across setup module from * import

File c:\Work\Anaconda3\lib\site-packages\h5py\__init__.py:46, in <module>
     37     _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
     38            "this may cause problems").format(
     39             '{0}.{1}.{2}'.format(*version.hdf5_version_tuple),
     40             '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
     41     ))
     44 _errors.silence_errors()
---> 46 from ._conv import register_converters as _register_converters
     47 _register_converters()
     49 from .h5z import _register_lzf

File h5py\h5t.pxd:14, in init h5py._conv()

File h5py\h5t.pyx:293, in init h5py.h5t()

File c:\Work\Anaconda3\lib\site-packages\numpy\__init__.py:320, in __getattr__(attr)
    317     from .testing import Tester
    318     return Tester
--> 320 raise AttributeError("module {!r} has no attribute "
    321                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'typeDict'_

**Comment by skoudoro** [comment]
What is your `h5py` version? this dependency fails for you and we have no control over it. 

you might need to update your h5py version or decrease this version because  the version you have is not compatible with the last version of Numpy.

Keep us updated, I will close this issue since it is not related to DIPY, it is a numpy <-> h5py issue.

**Comment by skoudoro** [comment]
also, feel free to reopen it if you are still stuck
