### ISSUE TITLE
dipy_horizon needs --force option if there is tmp.png

### ISSUE THREAD

**Issue by pjsjongsung** [dipy/dipy#2736]
## Description
dipy_horizon fails to open the file if there is an output file unless you use the --force option. (e.g. tmp.png) However, this is also the case even if you have no intention of creating an output file and just want to visualize something. I am not sure why it needs to be cautious about overwriting tmp.png, but judging by the name of the file, this does not seem necessary.

Below is the warning message:
INFO:The following output files already exist, the workflow will not continue processing any further. Add the --force flag to allow output files overwrite.
INFO:tmp.png

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example : dipy_horizon file_path (while you have a file named tmp.png in the current directory)
- [ ] Operating system and version: Windows-10-10.0.19045-SP0
- [ ] Python version: 3.8.11
- [ ] dipy version 1.6.0
- [ ] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
- [ ] numpy : 1.22.4
- [ ] scipy: 1.7.1
- [ ] nibabel: 3.2.1
- [ ] h5py 3.4.0
- [ ] no cvxpy installed
- [ ] fury 0.8.0

**Comment by pjsjongsung** [comment]
On a side note, we have cvxpy as dependency in the issue template but cvxpy does not seem to be a requirement when installing dipy. Is this intentional?

**Comment by lb-97** [comment]
@pjsjongsung, there's a 'overwrite' checker in the HorizonFlow workflow that throws this warning. I added a helper function to avoid this warning in interactive mode.

**Comment by maharshi-gor** [comment]
I have opened the PR https://github.com/dipy/dipy/pull/2969
which allow user to work without the --force option

**Comment by maharshi-gor** [comment]
The PR is merged and the behavior is fixed as closing this issue.
