### ISSUE TITLE
Weighted Non-Linear Fitting may be wrong

### ISSUE THREAD

**Issue by samcoveney** [dipy/dipy#2746]
The default weighting of `nlls_fit_tensor` in reconst/dti.py uses uniform weighting of the data. The option to use other weighting schemes is present, either `sigma` or `gmm`.

For `sigma` only a float can be supplied at the moment. But this means that the same weight is used for all datapoints, i.e. there is no weighting at all! This value ought to be generalized to allow a different weight for every image, which is presumably the intention.

For both `sigma` and `gmm` option for weighting, in functions `nlls_fit_tensor` and `restore_fit_tensor`, the default is to use the jacobian of the non-linear fitting function. However, the function `_nlls_jacobian_func` currently does not take any account of the weighting schemes! This would make it incorrect for `nlls_fit_tensor` even for weighting by a constant `sigma` (which in theory should do absolutely nothing since all datapoints would get the same weights) since the derivative will be wrong by a factor. For the case of `gmm` weighting, there appears to be no way to communicate the calculated weights to the jacobian function at all.

Am I wrong here, or do we need to make some important fixes?

**Comment by samcoveney** [comment]
I think I will have a go at fixing this then. I think we will probably need to change the optimization so that the cost function can either return the cost function value, or both the value and its derivative, otherwise I am not seeing how best to use `gmm` weighting - see https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html for example.

(I have been thinking about the enforcement of using the Cholesky decomp to constrain the tensor, it's a good idea in general and I have done it in my own Matlab code previously)

**Comment by Garyfallidis** [comment]
Sounds great @samcoveney ! @DenebBoito check #2730 as it develops and provide any suggestions you may have to @samcoveney .  A tutorial showing the fitting improvement over standard weighted least squares fitting would be nice too.

**Comment by arokem** [comment]
Yeah - thanks for catching theses issue! These are probably bugs that I introduced when I wrote this code about 10 years ago.

**Comment by RafaelNH** [comment]
About cholesky decomposition - didn't we implemented this already in the past?

I remember working on that - perhaps in the context of the fwDTI routine - cannot remember why we didn't make it compatible to both DTI and fwDTI.

**Comment by samcoveney** [comment]
#2730 should have fixed these issues now. Hopefully, given the fixes to the fitting, it can be prioritized?
