### ISSUE TITLE
BUG: Missing Python 3.11 macOS wheels

### ISSUE THREAD

**Issue by larsoner** [dipy/dipy#2771]
Based on https://github.com/conda-forge/dipy-feedstock/pull/41 1.6 should already be 3.11-compatible but macOS wheels are not on PyPI:

https://github.com/mne-tools/mne-gui-addons/actions/runs/4577184988/jobs/8082288800?pr=3
https://pypi.org/project/dipy/#files

**Comment by ravenep** [comment]
hello! I am running mac os 13.3.1 and encountered what looks like a related error. I am installing dypi as a dependency for another application. The error is below, does this seem related? Did you identify a workaround or know of updates? 

cheers, 
erika 

```
pip3 install dipy       
Collecting dipy
  Using cached dipy-1.6.0.tar.gz (12.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      /opt/homebrew/lib/python3.11/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      error in dipy setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
```

**Comment by skoudoro** [comment]
new release coming out tomorrow or this weekend should fix this issue

**Comment by ravenep** [comment]
yay! awesome news thanks for letting me know

**Comment by ravenep** [comment]
just logged in and had a clean install - thanks again for the heads up on the release, cheers !

**Comment by skoudoro** [comment]
Thank you for the feedback. closing
