### ISSUE TITLE
Error using dipy_motion_correct

### ISSUE THREAD

**Issue by araikes** [dipy/dipy#2777]
Hi @skoudoro ,

I'm attempting to use `dipy_motion_correct` on some data. As a test case, I have a file with 8 b=0 images at the front of the series and then 64 directions. When I run either `dipy_motion_correct` or follow the tutorial (https://dipy.org/documentation/1.6.0./examples_built/motion_correction/#example-motion-correction) using my data, I get the following error:

```
Traceback (most recent call last):
  File "/home/u26/adamraikes/.conda/envs/dipy/bin/dipy_correct_motion", line 7, in <module>
    run_flow(MotionCorrectionFlow())
  File "/home/u26/adamraikes/.conda/envs/dipy/lib/python3.10/site-packages/dipy/workflows/flow_runner.py", line 89, in run_flow
    return flow.run(**args)
  File "/home/u26/adamraikes/.conda/envs/dipy/lib/python3.10/site-packages/dipy/workflows/align.py", line 764, in run
    reg_img, reg_affines = motion_correction(data=data, gtab=gtab,
  File "/home/u26/adamraikes/.conda/envs/dipy/lib/python3.10/site-packages/dipy/align/_public.py", line 696, in register_dwi_series
    series_arr = np.concatenate([ref_data, moving_data], -1)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 4 dimension(s)
```

Functionally, I can see that this is a mismatch between the dimensions of the mean b0 image shape (64 96 64) and the moving data shape (64 96 64 64). What I can't see is how to fix it.

This is a clean conda install from today with Python 3.10.0 and only DIPY 1.6.0 (and it's requirements, particularly numpy `1.21.6`) installed.

**Comment by pjsjongsung** [comment]
@araikes @skoudoro It seems to be a bug in the register_dwi_series function. Think line 648 of dipy.align._public should have keepdims=True. Some parts of the tutorial might need fixing too.

For the meanwhile, a workaround might be running something like this below

```
import nibabel as nib
from dipy.align._public import register_series
import numpy as np

pipeline = ["center_of_mass", "translation", "rigid", "affine"]
b0_img = nib.Nifti1Image(data[..., gtab.b0s_mask], affine)
trans_b0, b0_affines = register_series(b0_img, ref=0, pipeline=pipeline)
ref_data = np.mean(trans_b0, -1, keepdims=True)

moving_data = data[..., ~gtab.b0s_mask]
new_bvals = np.pad(bvals[~gtab.b0s_mask], (1, 0))
new_bvecs = np.pad(bvecs[~gtab.b0s_mask, ...], ((1, 0), (0, 0)))
new_gtab = gradient_table(new_bvals, new_bvecs)

new_data = np.concatenate([ref_data, moving_data], -1)

motion_correction(data=new_data, gtab=new_gtab, affine=affine)
```

This runs the bugged part of the function and with proper option so should work, though I haven't tested the code yet. Let me know if this helps!

**Comment by araikes** [comment]
@pjsjongsung and @skoudoro 

`keepdims` certainly fixes it and I can run a locally patched version of `register_dwi_series`.  I dont know about the fix for `motion_correction` specifically.

However, new question: The affines returned by `register_dwi_series` should be useable for rotate the `bvecs`. `reorient_bvecs` expects them as an `(N, 4, 4)` array but they come back as `(4, 4, N)`. Is there a way to use these affines to rotate my bvecs?

**Comment by pjsjongsung** [comment]
Sorry for the late reply. I don't think the affines are transposed in anyway so you can do something like
`affine = np.moveaxis(affine, -1, 0)`

Thanks for finding this. It seems there is a bit of mismatch in the dimension between the two functions.

**Comment by skoudoro** [comment]
> However, new question: The affines returned by register_dwi_series should be useable for rotate the bvecs. reorient_bvecs expects them as an (N, 4, 4) array but they come back as (4, 4, N). Is there a way to use these affines to rotate my bvecs?

I need to ask @arokem for this point. it make more sense to me (4,4, N) than the opposite. I think `reorient_bvecs needs to be updated and not `register_dwi_series`.  it follows the same logic of nifti arrays in DIPY [x,y,z,N]. good catch @araikes.

> keepdims certainly fixes it and I can run a locally patched version of register_dwi_series. I dont know about the fix for motion_correction specifically.

thanks @pjsjongsung , and yes it should also fix `motion_correction`

**Comment by skoudoro** [comment]
fixed by https://github.com/dipy/dipy/pull/2781, closing
