### ISSUE TITLE
Horizon image's dtype validation

### ISSUE THREAD

**Issue by guaje** [dipy/dipy#2789]
## Description

When using horizon 

```python
from dipy.viz.app import horizon
```

In a Python script, the data types are not validated compared to when used via the respective workflow. This makes sense since the tool was originally intended to be used from the command line, but now we are promoting its usage through Python code, and we should ensure we can account for such cases. Here is the traceback I managed to get:

```bash
Original shape: (5, 5, 5)
Segmentation fault (core dumped)
```

It seems the `actor.slicer()` only supports `float64`, `float32`, `int32` but not `int64`.

## Way to reproduce

- Code example:
```python
import numpy as np
from dipy.viz.horizon.app import horizon

horizon(images=[((10 * np.random.rand(5, 5, 5)).astype(np.int64), np.eye(4))])
```

- Operating system and version:
`Linux-5.15.108-1-MANJARO-x86_64-with-glibc2.35`
But it was initially reported originally in MX MacOS.

- Python version:
`Python 3.8.10`
But it was found in other versions too.

- dipy version: `1.7.0`

- dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
    * import numpy; print("NumPy", numpy.__version__): `NumPy 1.24.3`
    * import scipy; print("SciPy", scipy.__version__): `SciPy 1.10.1`
    * import nibabel; print("Nibabel", nibabel.__version__): `Nibabel 5.1.0`
    * import h5py; print("H5py", h5py.__version__): `H5py 3.8.0`
    * import cvxpy; print("Cvxpy", cvxpy.__version__): `Cvxpy 1.3.1`
    * import fury; print("fury", fury.__version__): `fury 0.9.0`

**Comment by skoudoro** [comment]
Can you look at this @maharshi-gor?

**Comment by skoudoro** [comment]
fixed by https://github.com/dipy/dipy/pull/3031, closing
