### ISSUE TITLE
Tract profiles in the afq_profile example look terrible

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#2796]
In [this example](https://dipy.org/documentation/1.7.0/examples_built/17_streamline_analysis/afq_tract_profiles) the tract profile plots look terrible. I am not sure what this is about: bad tractography, bad data or bad mapping to the data (e.g., wrong affine or wrong use of the affine), but something is terribly wrong in this example.

**Comment by skoudoro** [comment]
closing in favor of #3175
