### ISSUE TITLE
Some left-overs from sphinx-gallery conversion 

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#2801]
There are some rendering issues still remaining from the conversion. For example, on this page: https://dipy.org/documentation/1.7.0/examples_built/04_preprocessing/denoise_ascm/#sphx-glr-examples-built-04-preprocessing-denoise-ascm-py

I noticed this: 
<img width="882" alt="Screenshot 2023-05-03 at 9 43 51 AM" src="https://user-images.githubusercontent.com/118582/235984563-e9d410cf-3353-4675-a365-fa5b936a3074.png">

**Comment by skoudoro** [comment]
Yes, I saw that too.

- clean up needed
- We also need to convert our example to the correct format.
- check image management,  sometimes it is good, sometimes, strange rendering.

All need to be fixed before the next release. 

Thank @arokem

**Comment by skoudoro** [comment]
Hi @arokem,

Do you know how to add caption to image with sphinx gallery ?  or should I get rid to all the captions ? Let me know if you have an idea

**Comment by arokem** [comment]
Maybe something like https://github.com/dipy/dipy/pull/2931?

**Comment by arokem** [comment]
I think that you ended up finding a stop-gap solution for this? Should we close this?

**Comment by skoudoro** [comment]
Not yet, I need to create the PR for that. Then, we can close when it is merged.
