### ISSUE TITLE
Type annotations integration

### ISSUE THREAD

**Issue by skoudoro** [dipy/dipy#2803]
## Description

it would be great if we could start to integrate type annotations in the whole DIPY codebase. 
Benefits are multiples (Improve code readibility so easier to maintain/debug, review and reduce cognitive load) and this summer can be an opportunity for that.

it would be great to know if someone is against this task.

Thank you all for the future feedback

Modules to to do
-----------------

- [ ] align
- [ ] boots
- [ ] core
- [ ] data
- [ ] denoise
- [ ] direction
- [ ] io
- [ ] nn
- [ ] reconst
- [ ] segment
- [ ] sims
- [ ] stats
- [ ] testing
- [ ] tests
- [ ] tracking
- [ ] utils
- [ ] viz
- [ ] workflows

**Comment by skoudoro** [comment]
Great @WassCodeur !

You should start with `io` modules of the project. 

You start by annotating the basic types, like `str`, `bool`. 

Also, I suppose there is library that can do the work for you, you will just need to check if it make sense. Let me know if you have any questions !

**Comment by WassCodeur** [comment]
sure

**Comment by skoudoro** [comment]
After the last DIPY Open Meeting, we decided to wait and see the evolution of type annotation adoption.

So closing this issue for now. 

Sorry @WassCodeur, I will have to close your PR also. Thanks for your nice work.
