### ISSUE TITLE
BundleWarp CLI Tutorial - Missing from Website

### ISSUE THREAD

**Issue by BramshQamar** [dipy/dipy#2827]
Hi,

The BundleWarp CLI tutorial is available on DIPY's GitHub page (https://github.com/dipy/dipy/blob/master/doc/interfaces/bundlewarp_registration_flow.rst) but not listed on the DIPY website (https://dipy.org/documentation/1.7.0/interfaces/). 

CLI tutorial PR was merged before the latest DIPY release.

**Comment by skoudoro** [comment]
Hi @BramshQamar,

Can you create a PR and add your tutorial [here (`interfaces/index.rst`)](https://github.com/dipy/dipy/blob/master/doc/interfaces/index.rst)

Then, it should appear.

Thanks!

**Comment by BramshQamar** [comment]
Sounds good! I will make a PR.

Thanks!

**Comment by skoudoro** [comment]
closed by https://github.com/dipy/dipy/pull/2832
