### ISSUE TITLE
Different behavior regarding color channels of horizon

### ISSUE THREAD

**Issue by pjsjongsung** [dipy/dipy#2852]
## Description
On the previous dipy version, it used to accept a 4D data with a size of 3 on the last channel as a colored 3D image. However, now it thinks of it as a multi volume.

We of course should not assume the last channel is a color channel, so a good solution would be creating an option for this? I am not sure, however, if this is a necessary function.

## Way to reproduce
dipy_horizon some_image.nii.gz
some_image should have a shape of (H, W, D, 3)

**Comment by skoudoro** [comment]
fixed by #2814, closing

**Comment by pjsjongsung** [comment]
@skoudoro The PR seems to solve the binary image issue, not the color channel issue. Could we reopen the issue?

**Comment by maharshi-gor** [comment]
The color channel support will be added by the PR https://github.com/dipy/dipy/pull/2992
@pjsjongsung please try the pr and let me know if anything else is required.

Thanks!

**Comment by maharshi-gor** [comment]
The PR has been merged to master, closing this issue
