### ISSUE TITLE
Bug in PFT when changing the random function

### ISSUE THREAD

**Issue by gabknight** [dipy/dipy#2867]
## Description
Changing `random.random(.)` in `dipy.direction.probabilistic_direction_getter.get_direction_c(.)` line 108, with `dipy.utils.fast_numpy.random()` makes the PFT test to fail on Windows. See #2806.

The test fail because the distance between the streamline points is not always equal to the step size. There is likely a corner case where points are incorrectly indexed, incorrectly removing an intermediary point.

I wasn't able to reproduce the bug on Linux. The test also run fine using `random.random(.)` on Windows.

**Comment by skoudoro** [comment]
closed by #2806
