### ISSUE TITLE
Website image (not showing up or wrong tag showing)

### ISSUE THREAD

**Issue by Atharva-Shah-2298** [dipy/dipy#2872]
## Description

When you go to the docs and look at the file below the matplotlib implementation, you will be able to see the tag quickstart1_example.png which is either not showing up or the tag is misplaced 

https://dipy.org/documentation/1.7.0/examples_built/01_quick_start/quick_start/#sphx-glr-examples-built-01-quick-start-quick-start-py

**Comment by skoudoro** [comment]
Hi @Atharva-Shah-2298,

Yes, we are doing a big update of the documentation to fix this issue. Thank you for the notification!

**Comment by skoudoro** [comment]
Duplicate of #2801. Closing for now. the fix should appear in the next release
