### ISSUE TITLE
Typo in the skills required section (Project 2) of Project Ideas

### ISSUE THREAD

**Issue by zjkumar** [dipy/dipy#2903]
# Description

### Typo :- 
- ***Skills required***: Familiarity with Python, experience with diffusion MRI ~~**with**~~ be a plus.

### Correction Suggested :- 
- ***Skills required***: Familiarity with Python, experience with diffusion MRI **would** be a plus.

***Typo source***  :-  
- https://github.com/dipy/dipy/wiki/Google-Summer-of-Code-2023 , **Project 2. Generalized along tract analysis of fiber orientation dispersion, _under Skills required section_**

**Comment by skoudoro** [comment]
Thank you for the feedback @zjkumar!

typo fixed, closing
