### ISSUE TITLE
spherical harmonic degree/order terminology swapped 

### ISSUE THREAD

**Issue by ebrahimebrahim** [dipy/dipy#2970]
For functions related to spherical harmonics, I noticed that the terminology "degree" and "order" is often used backwards in docstrings and variable names.

- in [this function](https://github.com/dipy/dipy/blob/b5efe4f8cd2fd4d88c0a5c08936f1b4ab314f8f0/dipy/reconst/shm.py#L578) for example `m` should be order and `n` should be degree
- in many places the maximum `n` (sometimes called $\ell$) value is a function argument called `sh_order`. it should be called `sh_degree` (or better `sh_degree_max`)

---

For a spherical harmonic $Y^m_n$ (sometimes called $Y^m_\ell$) , the $n$ ($\ell$)  is called _degree_ and the $m$  is called order.
- see terminology for [spherical harmonics](https://en.wikipedia.org/wiki/Spherical_harmonics)
- also see terminology for the [associated legendre polynomials](https://en.wikipedia.org/wiki/Associated_Legendre_polynomials#Definition_for_non-negative_integer_parameters_%E2%84%93_and_m) that show up up in the definition of spherical harmonics
- in [mrtrix docs](https://mrtrix.readthedocs.io/en/latest/concepts/spherical_harmonics.html#what-are-spherical-harmonics) we do sometimes see "order" used for $n$ (or $\ell$) but in that context the term _phase_ is then used for $m$.

**Comment by itellaetxe** [comment]
Hi,

I am Iñigo Tellaetxe, newcomer, and I would like to solve this issue.
I read the resources you included, and it does not seem to be very difficult to tackle. Can I get it assigned?

Thanks,

Iñigo

**Comment by skoudoro** [comment]
Yes, you can go ahead @itellaetxe,

thanks

**Comment by itellaetxe** [comment]
Thanks!
I have been reviewing the issue in more detail, and I have a couple of suggestions. I'd like to know your opinion before proceeding:

- Since `m` (order) and `n` (degree) are 1) visually similar symbols 2) they are subsequent in the alphabet, I would stop using `n` for the degree, and I would stay with `l` for the degree in all cases.
- _order_ and _degree_ are not very long words, so instead of using symbols like `m` and `l`, we could simply write the words themselves, for most (conceptual) clarity. It could result in slightly longer lines of code, though.

What are your thoughts on this? @ebrahimebrahim

**Comment by ebrahimebrahim** [comment]
- I agree that `m,l` is better than `m,n`. Good idea!
- It would be nice to have words for the variable names, but I have mixed feelings about it. My sense (and anyone can correct me about this) is that most people recognize  the indices using the letters `l` and `m` more than they recognize them by the words. Like if you go start talking to someone about "degree" they will probably ask what you mean by degree, and then when you say `l` then they'll say "oooh you mean `l`-value, got it." It's like if I started talking to you about the _absicissa_ and _ordinate_ of a point in a coordinate plane. You'd pause for a second until I clarify by saying `x`-value and `y`-value. I think order/degree terminology can just be a helper in docstrings to make it unambiguous what is meant by `m` and `l`

**Comment by skoudoro** [comment]
> I agree that m,l is better than m,n. Good idea!

I also agree

> order and degree are not very long words, so instead of using symbols like m and l, we could simply write the words themselves, for most (conceptual) clarity. It could result in slightly longer lines of code, though.

I like the idea. As a developer, I would say go for it. But, As a scientific, I agree with @ebrahimebrahim comment. (Personally, I use both. I avoid just `x`, but use `x_coord` or something similar which help for debugging purpose - it is hard to search for 1 letter in a code)

So I would recommend to use your first proposition. I know it will be ok to update the code but make sure to update our documentation also (especially this page: https://github.com/dipy/dipy/blob/master/doc/theory/sh_basis.rst)

**Comment by ebrahimebrahim** [comment]
> I avoid just `x`, but use `x_coord` or something similar

that is a good idea; a similar solution here would be to write `l_values` and `m_values` which is another good option

**Comment by itellaetxe** [comment]
Thanks for the feedback!
I will stick to `m_values` and `l_values`.
Working on it right now. Will keep you updated.

**Comment by itellaetxe** [comment]
Hi again,
I have been working on the code, trying to be as consistent as possible with the namings we discussed. Now I moved on to the docu, but I cannot build it, as I get many errors with the dependencies.
Also, I encountered some problems with the developer installation, and running the tests is not possible right now, but I want to do it before doing the PR. Could anyone provide some help with these issues? Perhaps I could ask in the gitter chat? Or open a new issue?

In additon, I think the developer manuals would benefit from a small update, and also from the ability to make an editable DIPY install in a virtual environment (the manual guides a user-environment installation), which is quite inconvenient for my other development activities even if I use virtual environment in the rest of my projects.

**Comment by ebrahimebrahim** [comment]
> In additon, I think the developer manuals would benefit from a small update, and also from the ability to make an editable DIPY install in a virtual environment

Development from a virtual environment is possible. When I set up my dev environment, it initially didn't work because I had the venv directory inside the source tree. Because of quirks of the meson-python build system this broke things. But putting a venv directory outside the dipy source tree worked for me just fine.


> Now I moved on to the docu, but I cannot build it, as I get many errors with the dependencies.

(I could never build the docs either.)

**Comment by itellaetxe** [comment]
Thank you @skoudoro and @ebrahimebrahim. I followed the steps in the cited documentation, but I must have messed up somewhere... I will try to fix it.

**Comment by itellaetxe** [comment]
Hi again!

This bit of information saved the day!
> When I set up my dev environment, it initially didn't work because I had the venv directory inside the source tree. Because of quirks of the meson-python build system this broke things. But putting a venv directory outside the dipy source tree worked for me just fine.
Now I have a working virtual environment. Thanks again for the advice.


Summary of what I did:
- Standardize the symbols for the spherical harmonic concepts of _order_ and _degree_ with `m_value` and `l_value`, respectively. In case these are arrays, we use `m_values` and `l_values` to be more informative of the type of the variable.
- Changed `sh_order` to `sh_degree_max` as @ebrahimebrahim suggested in the issue.
- Updated the examples according to the input argument name.
- Check that all tests are passing (locally)


Opening the PR now!

**Comment by skoudoro** [comment]
closed by #3086
