### ISSUE TITLE
DKI masking

### ISSUE THREAD

**Issue by samcoveney** [dipy/dipy#2994]
https://github.com/dipy/dipy/blob/7e158ffa52b81710f3a1b0d6afa3a364f42a650c/dipy/reconst/dki.py#L1678

I think, as mentioned in #2730, that the masking in the DKI function is not working properly except for the `multi_fit` method, because the mask does not appear to be passed into general fitting functions. Can I confirm that this appears to be the case?

**Comment by samcoveney** [comment]
so this sounds like a relatively simple fix... probably not urgent, but I'll try to look into it soon

**Comment by AkintolaRichard** [comment]
Hi @samcoveney, @skoudoro,
I want to help with the fix, and I would love to have your guidance.
