### ISSUE TITLE
Migrating to Keyword Only arguments (PEP 3102)

### ISSUE THREAD

**Issue by skoudoro** [dipy/dipy#3029]
## Description

Hi all, 

To simplify maintenance and avoid to messing around with function arguments order (it happens many times already), it would be great if we could switch our codebase to keyword-only arguments (see [pep 3102](https://peps.python.org/pep-3102/)).

To do a smooth transition, we might need to create a decorator that will warn the user about this feature. The decorator should stay in place for 3-4 releases (all this year (2024 and we remove it in 2025).

Please, Let me know what you think about this new feature or if you are against. 

I would like to start this work earliest as possible. 

ps: if we agree, all new function in DIPY codebase should follow this rules. 

Thank for the feedback.

**Comment by pjsjongsung** [comment]
Sounds reasonable! I had some related troubles during a PR last time, especially when using/changing functions written by another contributor, and this could really help.

**Comment by samcoveney** [comment]
Do you know of a way to check this using some tool? Would make the transition easier

**Comment by skoudoro** [comment]
For now, no, I do not know any tool.  With might do like scikit-learn,  create a decorator to warn user of this change, and apply this decorator in every single function in the codebase....

**Comment by skoudoro** [comment]
Closing since the decorator is merged #3239, and there is a whole code base update coming
