### ISSUE TITLE
Consider moving your nightly wheel away from the scipy-wheel-nightly (old location) to scientific-python-nightly-wheels 

### ISSUE THREAD

**Issue by lesteve** [dipy/dipy#3032]
## Description

You still seem to be uploading nightly wheels to scipy-wheel-nightly which is the old location. All the other projects have stopped uploading wheels to the old location roughly 6 months ago, see:
https://anaconda.org/scipy-wheels-nightly/

The new place is scientific-python-nightly-wheels:
https://anaconda.org/scientific-python-nightly-wheels/

Of course you may want to think about how this would impact the downstream consumers of your nightly wheel :wink:.

The SPEC about nightly wheels may be relevant:
https://github.com/scientific-python/specs/blob/main/spec-0004/index.md

**Comment by skoudoro** [comment]
Hi @lesteve,

Thank you for the update. 

For now, we can not upload to the new place. I have made a request 2 month ago and there is a discussion to determine which project can upload in the new place. See https://github.com/scientific-python/upload-nightly-action/issues/45.

I warned some downstream package as you can see in this link: https://github.com/dipy/dipy/issues/2979.

And we created and temporary nightly wheels repository : https://pypi.anaconda.org/dipy/label/dev/simple

But we are waiting for the final decision for the new place. Do you have any information concerning this? When do you plan to shutdown https://anaconda.org/scipy-wheels-nightly/

thank you in advance for the feedback

**Comment by AkintolaRichard** [comment]
Hi @skoudoro, I am newbie seeking an opportunity to contribute to open source, I would love to have guidance from you on how I can go about contribute to the project.

**Comment by skoudoro** [comment]
Hi @AkintolaRichard,

please, use the forum and not an issue for this. Also, I recommend you to look at our documentation like https://github.com/dipy/dipy/blob/master/.github/CONTRIBUTING.md or https://docs.dipy.org/stable/devel/index.html#development

I will delete your message since it is not related

**Comment by lesteve** [comment]
Sorry my issue was quite naive and I was not aware that projects that had access to scipy-wheels-nightly did not necessarily have access to scientific-python-nightly-wheels ...

Hosting your nightly wheels in your own Anaconda organization makes complete sense. One question though, out of curiosity: I see nightly wheels keep getting uploaded to https://anaconda.org/scipy-wheels-nightly/dipy, do you keep uploading there for backward-compatibility for your nightly wheel consumers?

Unfortunately, I am not involved too much in Scientific Python so I don't have too much information about the questions you are asking about.

**Comment by skoudoro** [comment]
>  I see nightly wheels keep getting uploaded to https://anaconda.org/scipy-wheels-nightly/dipy, do you keep uploading there for backward-compatibility for your nightly wheel consumers?

Yes

> Unfortunately, I am not involved too much in Scientific Python so I don't have too much information about the questions you are asking about.

Thanks for letting know!

Curiosity: Are you maintaining a downstream package? if yes, which one and what was your issue?

Closing the issue for now. I might reopen it when we have more info or some update.

**Comment by lesteve** [comment]
> Curiosity: Are you maintaining a downstream package? if yes, which one and what was your issue?

No, I am a scikit-learn maintainer who happened to look at scipy-wheels-nightly (don't even remember why), realised that dipy was the only project that still seemeed to upload wheels to the old location and opened an issue about it.

Thanks for your answers and I hope I did not sound too demanding in my initial request.

In case you want to chase projects that still are using the scipy-wheels-nightly one day, Github search supports regex so you can do something like:
https://github.com/search?q=%2Fanaconda.org.%2Bscipy-wheels-nightly.%2Bdipy%2F&type=code

The regex is not perfect since it only match single-line expressions, but this could be a start. For completeness, it seems like multi-line regexes are supported, see [this](https://github.com/orgs/community/discussions/9278).
