### ISSUE TITLE
Dipy website incorrect image

### ISSUE THREAD

**Issue by Atharva-Shah-2298** [dipy/dipy#3066]
## Description
The image in multi tensor simulation example is incorrect. 

https://docs.dipy.org/stable/examples_built/simulations/simulate_multi_tensor.html#sphx-glr-examples-built-simulations-simulate-multi-tensor-py
![Screenshot 2024-02-16 at 2 41 54 PM](https://github.com/dipy/dipy/assets/118627741/e1f1cb37-44db-4633-a6da-c69926d02309)

**Comment by pjsjongsung** [comment]
The issue seems to be in the shown image not the code itself. Might be better for the issue to be in dipy website github? https://github.com/dipy/dipy.org
