### ISSUE TITLE
Viz Tests failing

### ISSUE THREAD

**Issue by skoudoro** [dipy/dipy#3085]
Hi @maharshi-gor,

Your PR has been merged a bit too fast.  Tests are not passing.

Can you address the error below:

``` 
dipy/viz/__init__.py:4: in <module>
    from dipy.viz.horizon.app import horizon
dipy/viz/horizon/app.py:14: in <module>
    from dipy.viz.horizon.util import (check_img_dtype, check_img_shapes,
E     File "/Users/skoudoro/devel/dipy/dipy/viz/horizon/util.py", line 89
E       return np.unique(data[*indices]).shape[0] <= 2
E                                     ^
E   SyntaxError: invalid syntax
=============================================== short test summary info ================================================
ERROR dipy/viz/horizon/tab/tests/test_base.py
ERROR dipy/viz/tests/test_apps.py
ERROR dipy/viz/tests/test_fury.py
ERROR dipy/viz/tests/test_regtools.py
ERROR dipy/viz/tests/test_streamline.py
ERROR dipy/viz/tests/test_util.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================== 6 errors in 1.01s ===================================================

```

Thank you,

**Comment by Garyfallidis** [comment]
Great catch @skoudoro !!!

**Comment by maharshi-gor** [comment]
Hi I tried running those on my computer they run completely fine on my computer
Can you check for fury installation on the computer
============================= test session starts ==============================
platform darwin -- Python 3.11.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /Users/maharshigor/Desktop/GRG/dipy
configfile: pyproject.toml
collected 21 items

dipy/viz/horizon/tab/tests/test_base.py ....                             [ 19%]
dipy/viz/tests/test_apps.py .....                                        [ 42%]
dipy/viz/tests/test_fury.py .....                                        [ 66%]
dipy/viz/tests/test_regtools.py .                                        [ 71%]
dipy/viz/tests/test_streamline.py ...                                    [ 85%]
dipy/viz/tests/test_util.py ...                                          [100%]

============================= 21 passed in 42.22s ==============================
<<<PYTHON-EXEC-OUTPUT
Finished running tests!

**Comment by skoudoro** [comment]
Hi @maharshi-gor,

it is not related to FURY but python version. it fails with python 3.9 and pass with python 3.11.

we support python 3.9+. it needs to work with python3.9.

Can you look at this? 

Thanks

**Comment by maharshi-gor** [comment]
Hi @skoudoro you can check #3087 for resolved issue.

Thank you so much for the your feedback.

**Comment by maharshi-gor** [comment]
I have also created environment with different python version to make sure that I test backward compatibility on my local till the time test cases gets fixed.
