### ISSUE TITLE
TissueClassifierHMRF has some argument logic error

### ISSUE THREAD

**Issue by pjsjongsung** [dipy/dipy#3096]
`dipy.segment.tissue.TissueClassifierHMRF` according to the document and code is supposed to not break the loop through `tolerance` in two scenarios
1. `max_iter` is given
2. `tolerance` is not given

However, in this case `tolerance` having a default value does not make any sense. It also does not have `max_iter` cancel out `tolerance`, given how they are completely independent parameters.

I believe the correct direction is not having the `allow_break` argument at all, and if someone does not want to use it, they can always just pass 0 to `tolerance`.

One additional thing we have to edit is  the different behavior of `allow_break` when` save_history` is given, and if both are True results in a duplicate append.

I (or someone else if they want) could work on this PR, but need some feedback on whether removing `allow_break` is the correct direction. As an alternative, we could just remove the default `tolerance` value, but I do not think that is the original intention.

**Comment by Pavan-Satyam** [comment]
@pjsjongsung I want to look on this issue .Could you guide me what are the next steps where I could look at the code?

**Comment by arokem** [comment]
Sorry I missed this befor. I think that removing `allow_break` and keeping the `tolerance` default is the right direction.

**Comment by pjsjongsung** [comment]
Thanks @arokem ! @Pavan-Satyam if you want to work on this PR, now we seem to know the direction it should go.

**Comment by skoudoro** [comment]
fixed by #3132
