### ISSUE TITLE
Add `peaks_from_model` to `dipy_fit_dti` CLI

### ISSUE THREAD

**Issue by alexrockhill** [dipy/dipy#3122]
Since the other `dipy_fit_x` commands output a `pam` file, it would be nice if you could have a `--extract_pam_values` for vanilla DTI as well. If you want to do tracking, there isn't a way through the CLI as far as I can tell without it.

If that sounds reasonable, happy to write the PR.

**Comment by skoudoro** [comment]
Hi @alexrockhill,

it makes completely sense and not sure why we do not have it initially.

Feel free to go ahead!
