### ISSUE TITLE
csdeconv response as callable

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#313]
This option doesn't make sense, is not tested and probably wouldn't work as the code is structured right now. On this line: https://github.com/nipy/dipy/blob/master/dipy/reconst/csdeconv.py#L97, the callable is getting assigned into `S_r`, but that is then indexed into immediately afterwards, without any call being made to this function (https://github.com/nipy/dipy/blob/master/dipy/reconst/csdeconv.py#L104). Some additional logic would be required to make this work.

What was the original intent of this option?

**Comment by skoudoro** [comment]
Can we close this issue @arokem? it seems to be fixed by #314. 

Same for #218, Can we close it?

**Comment by arokem** [comment]
Looks like it.
