### ISSUE TITLE
Horizon slider does not show proper 0-1 range images such as FA

### ISSUE THREAD

**Issue by Garyfallidis** [dipy/dipy#3142]
Not showing properly decimals for 0-1 images (such as FA). 

See here
![image](https://github.com/dipy/dipy/assets/134276/1c9d8f08-688d-4455-988a-710e4b358746)

**Comment by maharshi-gor** [comment]
Hello @Garyfallidis , This issue requires to check a binary flag, which is introduced in the PR #3126 Let's merge this and I can fix this issue.

**Comment by Garyfallidis** [comment]
With MD maps the problem is even worse. Because mean diffusivity have low numbers.
