### ISSUE TITLE
dki_fit errors from divide by zero

### ISSUE THREAD

**Issue by yizhwan** [dipy/dipy#3145]
dipy_fit_dki.sh ${dwi_path} ${bval_path} ${bvec_path} ${mask} gives the following error:

dear team, i am running dipy_fit_dk in a shell script, receiving the following error:
.py:497: RuntimeWarning: invalid value encountered in divide
  return 3 * np.sqrt(6) * determinant((A_squiggle / A_s_norm)) 

If this is due to brain mask edges or noisy fit in low kurtosis regions, can the error be handled in a better way?

Thanks

**Comment by skoudoro** [comment]
Hi @yizhwan,

You can look at PR https://github.com/dipy/dipy/pull/3180 to see the fix. 
The next release on July will contains this fix.

Thanks to @RafaelNH !
