### ISSUE TITLE
Improve consistency of affine_registration docstring

### ISSUE THREAD

**Issue by FWijanto** [dipy/dipy#3185]
## Description
Hi, I found the docstring of affine_registration to be inconsistent with the actual function returns. The docstring says the function returns transformed:
https://github.com/dipy/dipy/blob/72847d73b8ec187dbbbc2f856a0f818559f6353b/dipy/align/_public.py#L435

Whereas the body of the function does not reference transformed, but returns resampled:
https://github.com/dipy/dipy/blob/72847d73b8ec187dbbbc2f856a0f818559f6353b/dipy/align/_public.py#L523-L526

Similarly, I think the affine resulting from the transform should not be called starting_affine, following the docstring:
https://github.com/dipy/dipy/blob/72847d73b8ec187dbbbc2f856a0f818559f6353b/dipy/align/_public.py#L503

https://github.com/dipy/dipy/blob/72847d73b8ec187dbbbc2f856a0f818559f6353b/dipy/align/_public.py#L514

I will make the proposed changes in a PR, but since this is my first contribution, I'd welcome some feedback on whether this is sensible.

Thanks!

**Comment by samcoveney** [comment]
resampled is transformed, just different names, you are right that the docstring should be more consistent.

Not sure why starting_affine is replaced in this way, are you sure it's not part of doing a multistage registration where starting_affine really does need to be updated before the next stage of registration is applied?

**Comment by FWijanto** [comment]
1. We are on the same page re: resampled or transformed. It's just a naming thing that got me confused, so I thought it would be a positive change.
2. My reading is that there is a multi-stage registration, (configurable, but defaults to `["center_of_mass", "translation", "rigid", "affine"]`) and at each step the affine is put in `starting_affine` and is used as the affine for the next step. So I see it as a parsimony thing: no need to create a copy of `starting_affine` if we don't refer back to the initial value later. But the end result is that we return an affine which is called `starting_affine`and no longer has the contents of `starting_affine` when it was defined.

**Comment by samcoveney** [comment]
It's true, seems a bit odd. I think updating starting_affine is fine, (it's always the start of the next type), but then at the end perhaps it should be saved into a variable final_affine for parsimony?

**Comment by arokem** [comment]
> It's true, seems a bit odd. I think updating starting_affine is fine, (it's always the start of the next type), but then at the end perhaps it should be saved into a variable final_affine for parsimony?


I'd be fine with that, if you think that improves clarity.

**Comment by skoudoro** [comment]
+1

**Comment by FWijanto** [comment]
Thanks for the feedback everyone, I'll make a PR according to what we discussed here.
