### ISSUE TITLE
numpy.core.multiarray failed when importing dipy.io.streamline (dipy.tracking.streamlinespeed)

### ISSUE THREAD

**Issue by DelinteNicolas** [dipy/dipy#3280]
## Description
Hello, I recently tried to create an environement with numpy 2.0.0 but importing the dipy.io.streamline module seems to be broken.

I didn't find another issue documenting this, altough it might be related to #3266. But this issue was closed and there has not been any change to the dipy.tracking.streamlinespeed module in the last seven month. Feel free to close this issue if this is being fixed somewhere else.

I assume there are a lot of changes to be covered with the recent update to numpy 2.0.0, so good luck with ironing the remaining bugs.

## Way to reproduce
- [x] Code example
```
from dipy.io.streamline import load_tractogram

  File ~\anaconda3\envs\numpy2\Lib\site-packages\dipy\io\streamline.py:13
    from dipy.io.vtk import save_vtk_streamlines, load_vtk_streamlines

  File ~\anaconda3\envs\numpy2\Lib\site-packages\dipy\io\vtk.py:2
    from dipy.tracking.streamline import transform_streamlines

  File ~\anaconda3\envs\numpy2\Lib\site-packages\dipy\tracking\streamline.py:10
    from dipy.tracking.streamlinespeed import length, set_number_of_points

  File streamlinespeed.pyx:1 in init dipy.tracking.streamlinespeed

ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```
- [x] Operating system and version
Windows
- [x] Python version
Python 3.12.4
- [x] dipy version
Dipy 1.9.0
- [x] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
Numpy 2.0.0
Scipy 1.14.0
Nibabel 5.2.1

**Comment by skoudoro** [comment]
Hi @DelinteNicolas,

It is fixed on master, we need to cut a release ASAP and we need to communicate that 1.9.0 and lower are not compatible with numpy 2.0.

In general, Any cython extensions not compiled with Numpy 2.0 will not work

Sorry for that and you should see a release this week or next week
