### ISSUE TITLE
BUG: Gradient table requires at least 2 orientations

### ISSUE THREAD

**Issue by oesteban** [dipy/dipy#3283]
Trying to create a GradientTable with only one bval/bvec fails:

```
bvals = array(1000.), bvecs = array([-0.346, -0.847, -0.402]), big_delta = None, small_delta = None, b0_threshold = 50, atol = 0.01, btens = None

    def gradient_table(bvals, bvecs=None, big_delta=None, small_delta=None,
                       b0_threshold=50, atol=1e-2, btens=None):
        """A general function for creating diffusion MR gradients.
    
        It reads, loads and prepares scanner parameters like the b-values and
        b-vectors so that they can be useful during the reconstruction process.
    
        Parameters
        ----------
    
        bvals : can be any of the four options
    
            1. an array of shape (N,) or (1, N) or (N, 1) with the b-values.
            2. a path for the file which contains an array like the above (1).
            3. an array of shape (N, 4) or (4, N). Then this parameter is
               considered to be a b-table which contains both bvals and bvecs. In
               this case the next parameter is skipped.
            4. a path for the file which contains an array like the one at (3).
    
        bvecs : can be any of two options
    
            1. an array of shape (N, 3) or (3, N) with the b-vectors.
            2. a path for the file which contains an array like the previous.
    
        big_delta : float
            acquisition pulse separation time in seconds (default None)
    
        small_delta : float
            acquisition pulse duration time in seconds (default None)
    
        b0_threshold : float
            All b-values with values less than or equal to `bo_threshold` are
            considered as b0s i.e. without diffusion weighting.
    
        atol : float
            All b-vectors need to be unit vectors up to a tolerance.
    
        btens : can be any of three options
    
            1. a string specifying the shape of the encoding tensor for all volumes
               in data. Options: 'LTE', 'PTE', 'STE', 'CTE' corresponding to
               linear, planar, spherical, and "cigar-shaped" tensor encoding.
               Tensors are rotated so that linear and cigar tensors are aligned
               with the corresponding gradient direction and the planar tensor's
               normal is aligned with the corresponding gradient direction.
               Magnitude is scaled to match the b-value.
            2. an array of strings of shape (N,), (N, 1), or (1, N) specifying
               encoding tensor shape for each volume separately. N corresponds to
               the number volumes in data. Options for elements in array: 'LTE',
               'PTE', 'STE', 'CTE' corresponding to linear, planar, spherical, and
               "cigar-shaped" tensor encoding. Tensors are rotated so that linear
               and cigar tensors are aligned with the corresponding gradient
               direction and the planar tensor's normal is aligned with the
               corresponding gradient direction. Magnitude is scaled to match the
               b-value.
            3. an array of shape (N,3,3) specifying the b-tensor of each volume
               exactly. N corresponds to the number volumes in data. No rotation or
               scaling is performed.
    
        Returns
        -------
        gradients : GradientTable
            A GradientTable with all the gradient information.
    
        Examples
        --------
        >>> from dipy.core.gradients import gradient_table
        >>> bvals = 1500 * np.ones(7)
        >>> bvals[0] = 0
        >>> sq2 = np.sqrt(2) / 2
        >>> bvecs = np.array([[0, 0, 0],
        ...                   [1, 0, 0],
        ...                   [0, 1, 0],
        ...                   [0, 0, 1],
        ...                   [sq2, sq2, 0],
        ...                   [sq2, 0, sq2],
        ...                   [0, sq2, sq2]])
        >>> gt = gradient_table(bvals, bvecs)
        >>> gt.bvecs.shape == bvecs.shape
        True
        >>> gt = gradient_table(bvals, bvecs.T)
        >>> gt.bvecs.shape == bvecs.T.shape
        False
    
        Notes
        -----
        1. Often b0s (b-values which correspond to images without diffusion
           weighting) have 0 values however in some cases the scanner cannot
           provide b0s of an exact 0 value and it gives a bit higher values
           e.g. 6 or 12. This is the purpose of the b0_threshold in the __init__.
        2. We assume that the minimum number of b-values is 7.
        3. B-vectors should be unit vectors.
    
        """
    
        # If you provided strings with full paths, we go and load those from
        # the files:
        if isinstance(bvals, str):
            bvals, _ = io.read_bvals_bvecs(bvals, None)
        if isinstance(bvecs, str):
            _, bvecs = io.read_bvals_bvecs(None, bvecs)
    
        bvals = np.asarray(bvals)
    
        # If bvecs is None we expect bvals to be an (N, 4) or (4, N) array.
        if bvecs is None:
            if bvals.shape[-1] == 4:
                bvecs = bvals[:, 1:]
                bvals = np.squeeze(bvals[:, 0])
            elif bvals.shape[0] == 4:
                bvecs = bvals[1:, :].T
                bvals = np.squeeze(bvals[0, :])
            else:
                raise ValueError("input should be bvals and bvecs OR an (N, 4)"
                                 " array containing both bvals and bvecs")
        else:
            bvecs = np.asarray(bvecs)
>           if bvecs.shape[1] != 3 and bvecs.shape[0] > 1:
E           IndexError: tuple index out of range

/home/oesteban/.miniconda/lib/python3.9/site-packages/dipy/core/gradients.py:707: IndexError
```

**Comment by MartinKjunior** [comment]
> Trying to create a GradientTable with only one bval/bvec fails:
> 
> ```
> bvals = array(1000.), bvecs = array([-0.346, -0.847, -0.402]), big_delta = None, small_delta = None, b0_threshold = 50, atol = 0.01, btens = None
> 
>     def gradient_table(bvals, bvecs=None, big_delta=None, small_delta=None,
>                        b0_threshold=50, atol=1e-2, btens=None):
>         """A general function for creating diffusion MR gradients.
>     
>         It reads, loads and prepares scanner parameters like the b-values and
>         b-vectors so that they can be useful during the reconstruction process.
>     
>         Parameters
>         ----------
>     
>         bvals : can be any of the four options
>     
>             1. an array of shape (N,) or (1, N) or (N, 1) with the b-values.
>             2. a path for the file which contains an array like the above (1).
>             3. an array of shape (N, 4) or (4, N). Then this parameter is
>                considered to be a b-table which contains both bvals and bvecs. In
>                this case the next parameter is skipped.
>             4. a path for the file which contains an array like the one at (3).
>     
>         bvecs : can be any of two options
>     
>             1. an array of shape (N, 3) or (3, N) with the b-vectors.
>             2. a path for the file which contains an array like the previous.
>     
>         big_delta : float
>             acquisition pulse separation time in seconds (default None)
>     
>         small_delta : float
>             acquisition pulse duration time in seconds (default None)
>     
>         b0_threshold : float
>             All b-values with values less than or equal to `bo_threshold` are
>             considered as b0s i.e. without diffusion weighting.
>     
>         atol : float
>             All b-vectors need to be unit vectors up to a tolerance.
>     
>         btens : can be any of three options
>     
>             1. a string specifying the shape of the encoding tensor for all volumes
>                in data. Options: 'LTE', 'PTE', 'STE', 'CTE' corresponding to
>                linear, planar, spherical, and "cigar-shaped" tensor encoding.
>                Tensors are rotated so that linear and cigar tensors are aligned
>                with the corresponding gradient direction and the planar tensor's
>                normal is aligned with the corresponding gradient direction.
>                Magnitude is scaled to match the b-value.
>             2. an array of strings of shape (N,), (N, 1), or (1, N) specifying
>                encoding tensor shape for each volume separately. N corresponds to
>                the number volumes in data. Options for elements in array: 'LTE',
>                'PTE', 'STE', 'CTE' corresponding to linear, planar, spherical, and
>                "cigar-shaped" tensor encoding. Tensors are rotated so that linear
>                and cigar tensors are aligned with the corresponding gradient
>                direction and the planar tensor's normal is aligned with the
>                corresponding gradient direction. Magnitude is scaled to match the
>                b-value.
>             3. an array of shape (N,3,3) specifying the b-tensor of each volume
>                exactly. N corresponds to the number volumes in data. No rotation or
>                scaling is performed.
>     
>         Returns
>         -------
>         gradients : GradientTable
>             A GradientTable with all the gradient information.
>     
>         Examples
>         --------
>         >>> from dipy.core.gradients import gradient_table
>         >>> bvals = 1500 * np.ones(7)
>         >>> bvals[0] = 0
>         >>> sq2 = np.sqrt(2) / 2
>         >>> bvecs = np.array([[0, 0, 0],
>         ...                   [1, 0, 0],
>         ...                   [0, 1, 0],
>         ...                   [0, 0, 1],
>         ...                   [sq2, sq2, 0],
>         ...                   [sq2, 0, sq2],
>         ...                   [0, sq2, sq2]])
>         >>> gt = gradient_table(bvals, bvecs)
>         >>> gt.bvecs.shape == bvecs.shape
>         True
>         >>> gt = gradient_table(bvals, bvecs.T)
>         >>> gt.bvecs.shape == bvecs.T.shape
>         False
>     
>         Notes
>         -----
>         1. Often b0s (b-values which correspond to images without diffusion
>            weighting) have 0 values however in some cases the scanner cannot
>            provide b0s of an exact 0 value and it gives a bit higher values
>            e.g. 6 or 12. This is the purpose of the b0_threshold in the __init__.
>         2. We assume that the minimum number of b-values is 7.
>         3. B-vectors should be unit vectors.
>     
>         """
>     
>         # If you provided strings with full paths, we go and load those from
>         # the files:
>         if isinstance(bvals, str):
>             bvals, _ = io.read_bvals_bvecs(bvals, None)
>         if isinstance(bvecs, str):
>             _, bvecs = io.read_bvals_bvecs(None, bvecs)
>     
>         bvals = np.asarray(bvals)
>     
>         # If bvecs is None we expect bvals to be an (N, 4) or (4, N) array.
>         if bvecs is None:
>             if bvals.shape[-1] == 4:
>                 bvecs = bvals[:, 1:]
>                 bvals = np.squeeze(bvals[:, 0])
>             elif bvals.shape[0] == 4:
>                 bvecs = bvals[1:, :].T
>                 bvals = np.squeeze(bvals[0, :])
>             else:
>                 raise ValueError("input should be bvals and bvecs OR an (N, 4)"
>                                  " array containing both bvals and bvecs")
>         else:
>             bvecs = np.asarray(bvecs)
> >           if bvecs.shape[1] != 3 and bvecs.shape[0] > 1:
> E           IndexError: tuple index out of range
> 
> /home/oesteban/.miniconda/lib/python3.9/site-packages/dipy/core/gradients.py:707: IndexError
> ```

The issue is in how you've defined your numpy arrays. `np.array(1000.).shape -> ()` and `np.array([-0.346, -0.847, -0.402]).shape -> (3,)`, but `gradient_table()` asks for shapes `(N,)` and `(N,3)`. The following code works as you intended:
```py
print(gradient_table(bvals = np.array([1000.]), bvecs = np.array([[-0.346, -0.847, -0.402]]), big_delta = None, small_delta = None, b0_threshold = 50, atol = 0.01, btens = None))
```
giving
```
B-values shape (1,)
         min 1000.000000
         max 1000.000000
B-vectors shape (1, 3)
          min -0.847000
          max -0.346000
```
