### ISSUE TITLE
Reconstruction model list not linked in documentation since it cannot be located

### ISSUE THREAD

**Issue by jhlegarreta** [dipy/dipy#3347]
## Description

The table of reconstruction methods located in
https://github.com/dipy/dipy/blob/master/doc/reconstruction_models_list.rst

cannot be located properly when generating the documentation:

```
/home/runner/work/dipy/dipy/doc/examples_built/reconstruction/index.rst:13: CRITICAL: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'examples_built/reconstruction_models_list.rst'.
```

https://github.com/dipy/dipy/actions/runs/10647467841/job/29515431777#step:5:698

The script expects it to be in `examples_built` but it is not found there; it is originally located in `examples`.

Probably the `prepare_gallery.py` script should copy the file to the `examples_built` folder.

## Way to reproduce
- Clone DIPY.
- Follow the installation in https://docs.dipy.org/stable/devel/installation_from_source.html#getting-the-source to install DIPY
- Generate the documentation following https://docs.dipy.org/stable/devel/installation_from_source.html#documentation.
- Check the error.

**Comment by skoudoro** [comment]
or maybe we can do a `..include:  :ref:{reconstruction_models_list_name}` 

something to check. Thank you for the report

**Comment by skoudoro** [comment]
> or maybe we can do a ..include:  :ref:{reconstruction_models_list_name}

not possible, I checked

**Comment by jhlegarreta** [comment]
Thanks for having given this a try. @skoudoro So is `cp examples/reconstruction_models_list.rst examples_built/reconstruction_models_list.rst' the only option left? Do we need to copy this into each of the conditional possibilities in `docs/make.bat`?

**Comment by jhlegarreta** [comment]
I think I tried copying the file to `examples_built` manually prior to generation and that did not make the trick, so not sure how to fix this.

**Comment by jhlegarreta** [comment]
So the table appears in
https://docs.dipy.org/stable/examples_built/index.html
but not in
https://docs.dipy.org/stable/examples_built/reconstruction/index.html

I assume that this issue is related, or that we'd like the table appear in the `Reconstruction` section index.

I'll look into improving the references to adopt the new bibtex convention once we manage to fix this issue and as time permits. A slightly related thought would be to have all bibtex references (including those that exist across the docstrings) listed in a section of the website.
