### ISSUE TITLE
support for numpy 2.0 seems missing

### ISSUE THREAD

**Issue by pjmark** [dipy/dipy#3416]
When using numpy>=2.0, I get an error here:
from dipy.align import vector_fields as vfu

ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<voImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
id>numpy._import_array' to disable if you are certain you don't need it).

it goes away with numpy 1.26

**Comment by pjsjongsung** [comment]
To my knowledge, DIPY does not support numpy>=2.0 at the moment. numpy had quite some change moving to 2.0. Hopefully this will be resolved soon.

**Comment by llctrautmann** [comment]
Running into the same issues. What is the expectation for when the next version will be released?

 Thank for your work!

**Comment by skoudoro** [comment]
fixed by the last release, closing
