### ISSUE TITLE
Code review items for `dipy.reconst.shore`

### ISSUE THREAD

**Issue by matthew-brett** [dipy/dipy#365]
From https://github.com/nipy/dipy/pull/363 - useful code review from Ariel:

- [x] Can the docstring code here: https://github.com/nipy/dipy/blob/8abe71f9e2746c7107e0ff5cccb068adb9f00947/dipy/reconst/shore.py#L145 be made into a doctest?

- [x] This error: https://github.com/nipy/dipy/blob/8abe71f9e2746c7107e0ff5cccb068adb9f00947/dipy/reconst/shore.py#L169

- [ ] Calculating tau when it's not defined: https://github.com/nipy/dipy/blob/8abe71f9e2746c7107e0ff5cccb068adb9f00947/dipy/reconst/shore.py#L178

- [x] This error: https://github.com/nipy/dipy/blob/8abe71f9e2746c7107e0ff5cccb068adb9f00947/dipy/reconst/shore.py#L180

- [ ] This one is tricky. What happens if no solution if found: https://github.com/nipy/dipy/blob/8abe71f9e2746c7107e0ff5cccb068adb9f00947/dipy/reconst/shore.py#L267

- [ ] This caching trick (the documentation there could also be better): https://github.com/nipy/dipy/blob/8abe71f9e2746c7107e0ff5cccb068adb9f00947/dipy/reconst/shore.py#L339

- [x] This method: https://github.com/nipy/dipy/blob/8abe71f9e2746c7107e0ff5cccb068adb9f00947/dipy/reconst/shore.py#L461

- [x] This error: https://github.com/nipy/dipy/blob/8abe71f9e2746c7107e0ff5cccb068adb9f00947/dipy/reconst/shore.py#L741

- [x] This error: https://github.com/nipy/dipy/blob/8abe71f9e2746c7107e0ff5cccb068adb9f00947/dipy/reconst/shore.py#L778

I admit that most of these are rather trivial. Error handling is a no-brainer and I don't mean to pick on anyone. Just thought I would make a list of these things, so that it's easier to go back and improve testing, when we get a chance.

**Comment by kushaangupta** [comment]
1. Converting the example code into doctest is giving an error due to the assumption of the code that data exists in file _ISBI_testing_2shells_table_.
https://github.com/nipy/dipy/blob/8abe71f9e2746c7107e0ff5cccb068adb9f00947/dipy/reconst/shore.py#L145
