### ISSUE TITLE
Some doc missing

### ISSUE THREAD

**Issue by EmmaRenauld** [dipy/dipy#366]
Hi,
the module tracking.distances (http://nipy.org/dipy/reference/dipy.tracking.distances.html) doesn't appear on the documentation page for tracking (http://nipy.org/dipy/reference/dipy.tracking.html).

**Comment by skoudoro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#366](https://trello.com/c/4OgLE3DQ/2-366)
