### ISSUE TITLE
mrtrix 0.3 default basis is different from mrtrix 0.2

### ISSUE THREAD

**Issue by samuelstjean** [dipy/dipy#392]
So according to this https://github.com/jdtournier/mrtrix3/wiki/Orthonormal-SH-basis, the new mrtrix 0.3 will have an orthornormal basis. That means that any function using the -basis option will either
1. Need to call it mrtrix 0.2 basis to distinguish the old from the new one.
2. Implement a mrtrix 0.2 and mrtrix 0.3 basis since they are not the same.

They now say it will be orthornormal, so if it fits with dipy basis all is good, else the new basis will have to be implemented when the 0.3 release is more mainstream.

**Comment by jhlegarreta** [comment]
Partially addressed by #1657.

I guess explaining the MRtrix0.2 vs. MRtrix3 basis does no longer make sense, since DIPY uses MRtrix3, and stopped using MRtrix0.2.

ToDo's:
- [ ] Explain **why the sqrt(2) is relevant**.
- [ ] Add a **function to infer the SH basis used by the data**, as it has been suggested.

**Comment by jhlegarreta** [comment]
True, a confusion on my side. Edited/removed the part. The factor is not actually present in the code as you said in #1657, and as shown in the new doc `sh_basis.rst` doc.

**Comment by scott-trinkle** [comment]
Raised a separate issue (https://github.com/nipy/dipy/issues/1782), but it looks like I should move the discussion here. 

I think something is still off between the default DIPY and MRtrix3 bases. It doesn't look like the current DIPY `basis_type` implementations are accounting for the following quote from the [`dwi2fod` documentation](https://mrtrix.readthedocs.io/en/latest/reference/commands/dwi2fod.html) in MRtrix:

> Note that the spherical harmonics equations used here differ slightly from those conventionally used, in that the (-1)^m factor has been omitted. 

So currently, both software packages include the sqrt(2) scaling factor, but have opposite conventions for taking the Real vs. Imaginary components for m > 0 or m < 0 (which amounts to just reordering the way in which the SH coefficients are stored), and MRtrix does not have the (-1)^m factor included in `scipy.special.sph_harm`, which amounts to certain coefficients being off by a factor of -1. 

Currently, the `basis_type='tournier07'` argument calls to the `real_sym_sh_mrtrix` function, which correctly reorders the coefficients, but does not include the sqrt(2) factor and does not account for the (-1)^m factor. 

[Here](https://github.com/scott-trinkle/hardi/blob/master/mrtrix3_to_dipy_sh/mrtrix3_to_dipy_SH.ipynb) I show that when you expand the same spherical function onto SH coefficients in both DIPY and MRtrix, you can use a (admittedly sloppy for now) utility function to convert mrtrix coefficients into the dipy basis, and work with them from there. Using the `basis_type='tournier07'` results in different ODFs.

**Comment by skoudoro** [comment]
Hi @CHrlS98,

Since you are looking and updating the SH basis via PR #2206, Could you also look at this issue and give feedback to the community,  please?

Thank you
