### ISSUE TITLE
Multiprocessing the tensor reconstruction

### ISSUE THREAD

**Issue by samuelstjean** [dipy/dipy#562]
As a reminder, could be useful to have that for really large dataset like the HCP. It seems the multiprocessing part happens in peaks from model for everything else, so I have no idea how it would be easy to add that to the tensor model itself.

**Comment by MrBago** [comment]
If anyone wants to work on this ping me. I have a pretty good idea of how we could do this and I have a good bit of the code written. I plan on getting back to it eventually, but it might not be for a while so if someone wants to take over I'm more than happy to share.

**Comment by MrBago** [comment]
I've put some thoughts on this topic into code [here](https://github.com/nipy/dipy/compare/master...MrBago:nf_parallel_framework), thought I'd share in case someone is interested.

**Comment by skoudoro** [comment]
closing in favor of #1026
