### ISSUE TITLE
Download each shell of the CENIR data separately? 

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#717]
In some cases (e.g. DKI examples in #677), only parts of the data are being used. Should we also modularize downloading, so that you can download only some shells of these data? This might complicate matters a bit on #716

**Comment by ChantalTax** [comment]
Is this dataset going to be used in more example scripts? In that case I guess it is fine, then users download it once and use certain shells for different examples (e.g. up to 2000 for DKI, only 3000 for CSD).

**Comment by arokem** [comment]
Yes - I think that it could be used in other examples, and future demos. For example, I still need to create an example that uses the multi b-value SFM (#559), which can be done with these data.

**Comment by arokem** [comment]
#718

**Comment by skoudoro** [comment]
Hi @arokem,

When I look at [here](https://github.com/dipy/dipy/blob/master/dipy/data/fetcher.py#L1090), the download of each shell seems already split.

Can I go ahead and close this issue?

**Comment by arokem** [comment]
Yes. Thanks!
