### ISSUE TITLE
Auto-convert the examples into IPython notebooks

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#720]
And vice versa: enable writing examples in IPython notebooks, which then get converted into the compliant python + rst to get built into the documentation.

**Comment by sahmed95** [comment]
@arokem Hi, I made a quick script to generate ipython notebooks from all the examples. You can see a sample [here](https://github.com/sahmed95/dipy/blob/issue-720_notebooks/doc/examples_notebook/affine_registration_3d.ipynb) Apart from some markup issues and things with math formulas, this works for all the examples which follow the standard dipy examples format.

The code used to generate the files can be seen here - [make_notebooks](https://github.com/sahmed95/dipy/blob/issue-720_notebooks/doc/examples/make_notebooks.ipynb)

**Comment by arokem** [comment]
This is a great idea! However, I would prefer that we automate this, such that the notebooks get automatically generated when we build the documentation. 

That is, rather than committing all these notebooks to the repository, we would have a script that converts the python examples to jupyter notebooks, and uploads them together with the python example scripts, so they can be downloaded. Even better, a script that would automatically create/update a gist on github and create the nbviewer page would be fantastic.

**Comment by sahmed95** [comment]
Yeah, that seems to be achievable if all the examples follow this format : 

```python
""" Some text and description of the code.
Some references and how to use the package
"""

import nibabel
import dipy

"""Some more text
and usage
"""
a = 2+3
print (a)

"""End text
"""
```
I can then easily separate text and code blocks. I guess this is the prescribed way to write examples. Am I correct?

**Comment by arokem** [comment]
Yes - that's correct.

The examples get processed using this module:
https://github.com/nipy/dipy/blob/master/tools/make_examples.py

All the .py files in the examples folder get automatically rendered into
rst files (into the examples_built folder), and they then get picked up by
sphinx, as it builds the documentation.

Multi-line text blocks (in triple quotes) get rendered into text blocks in
the rst file, pretty much as is. The code sections in the py file get
rendered as code blocks in the rst.

**Comment by sahmed95** [comment]
@arokem I automated the script such that notebooks are generated when tools/make_examples.py is run. The built notebooks are stored in the folder doc/examples_notebook. I will go ahead and implement the .rst and nbviewer conversion. The script still needs some work but for now it generates all examples. Since the examples are already built from the python files, can we just link the notebooks at the end of each example instead of generating new html from notebooks ? Since the content is same.
