### ISSUE TITLE
Adding optional (GPL) dependencies to have new features

### ISSUE THREAD

**Issue by samuelstjean** [dipy/dipy#722]
What is the recommended stance about new optional deps? So far some modules requires them in order to work (Life, SHORE, fvtk, soon MAPMRI), which brings unique features not readily available anywhere else. So, is it recommendable to add stuff in order to have unique features, and if people are not interested in those they just don't install them.

I'm asking since I have some stuff which works with an L1 GPL optimizer written in C++ (http://spams-devel.gforge.inria.fr/downloads.html), and nothing which is BSD licensed and widely used offers an alternative. This is the same lib that Sylvain Merlet dictionary stuff was using and is also used by some other projects that might end up here when polished (and if the person working on it wants to of course).

**Comment by arokem** [comment]
I think that the stance is that optional dependencies are a case-by-case issue. If it's a well-supported piece of software that is very easy to install (e.g. scikit-image, vtk, etc.), and is BSD licensed, it's not a huge issue, and seems like a no-brainer to me. 

Specifically for this case: dependencies that are GPL licensed are a strict no no. I've already mentioned on #675 what I think a way forward for that is. In addition to that particular hindrance, this one also looks non-trivial to install.

By the way - LiFE introduced no optional/additional dependencies.

**Comment by samuelstjean** [comment]
I meant the SFM then, must have mixed these two. And I was thinking about
adding another specialized solver besides cvxopt as it does noit fit my
purposes. It can easily be pip inbstalled of course, its just a wrapper
over somne c++ stuff with swig. And there is also 2-3 others things that
use it at least. And its unrelated to the gsl thing, although I still think
it is needed as nothing else works.

**Comment by arokem** [comment]
Yes - the SFM depends on scikit-learn, a well-maintained, BSD-licensed
software library that is very easy to install.

By  the way - for and optimizer with L1 constraints, would the sklearn
implementation of the LASSO algorithm work for you?

This is the only SPAM I could find on pypi:
https://pypi.python.org/pypi/spam/4.0.9, and though it looks eminently
useful, it's not the software you are talking about. How do you pip install
the software in question? Or do you propose that we maintain a wheel of
this thing? I am of course a strong -1 on that.

**Comment by samuelstjean** [comment]
Most people just pip install url, or just build the download I guess. I am
looking for a constrained lasso actually, as opposed to the regularized one
in sklearn. The l1 optimizer in cvxopt is just generic and too sloiw for
thius problem.

I also broke this morning my sole way of accessing internet, so if I dont
respond to this or your other bugfix pr thats why.

**Comment by arokem** [comment]
Sorry to hear about your internet - hope you've sorted that out. 

I don't think we have great data about what "most people" do. I certainly have met many scientists for whom "building the download" is a barrier that would prevent them from using your software. For one, I couldn't figure out how I would install this software using pip (still can't, even with your very detailed instructions ;D). 

More importantly, as a more general point, I think that we should be careful not to sprawl over too much new functionality, with new-fangled methods that will be hard to support (adding complex external dependencies increases the burden in maintaining these things). There is so much work to do on the functionality that we already have. For example, we currently have several open PRs that need review, the tracking functionality could use some love, there is plenty of work to make the denoising methods more user friendly (a uniform and consistent API would be nice), etc.

**Comment by samuelstjean** [comment]
Well, for the first point, simply giving the needed one liner did it for the 5-6 people that tried it, and one even forgot he had to actually install stuff when I asked him about him since I just printed the needed one-liner in case it was not installed. It's actually the original implementation from where sklearn gets its dictionary learning stuff, but they only partly re-implemented it and are missing some specialized functions.

If you want to, its a simple matter of building it from http://spams-devel.gforge.inria.fr/downloads.htm by just running the setup.py includedl or pip install downloaded_file or even running pip install http://spams-devel.gforge.inria.fr/hitcounter2.php?file=33816/spams-python-v2.5-svn2014-07-04.tar.gz, but that one of course if probably only temporary.

As for the second part, this is actually in line with making stuff work as I use it for the 4D denoising, which should work better than trying to patch around the old nlmeans. It also bridge the gaps with the various noise estimation algorithms already available at the same time. As for the tracking, I have no experience in that, but Gab latest algorithm (available at this last summer ipmi, still under works internally) also uses this as it's much faster than scipy or cvxopt.

**Comment by arokem** [comment]
Regardless of all that, it's still GPL licensed. See my comment here: https://github.com/nipy/dipy/pull/675#issuecomment-127287170 for what I think we should do in these cases. Short recap: separate repo, separate installation, as a dipy "add on", rather than part of the main project. Same should be done with SHORE, if you ask me.

**Comment by arokem** [comment]
As another aside, spams seems to only run on legacy python ("python 2"), so will also slow us down in the long run. Admittedly, this is also true for fvtk, but that Kitware have been saying that will change soon, so at least there's hope.

**Comment by samuelstjean** [comment]
Since it's just using a wrapper, rebuilding it with a more recent version of swig makes it compatible with python 3 (see https://github.com/samuelstjean/spams-python, should still be working). 

Won't separating stuff makes it less used though? Unless there is a dipy_gpl folder inside the same repo which mimics the same structure, and the two just interoperate transparently, it might just fall out unused if it's a completely separate project.

**Comment by matthew-brett** [comment]
I'm on the VTK mailing list, the next release of VTK should be Python 3
compatible.
​

**Comment by Garyfallidis** [comment]
I think what Ariel suggests is very generous and an important time investment for him and the rest of the devs. We will make a small package with the non-bsd licence dependencies. But I do hope that this package will not have any compiled parts which would make releasing it more complicated. Anyway there is no easy solution here. Let's see how it goes. And also we should investigate if some other people are working on BSD optimizers you never know. New modules appear every day.

**Comment by skoudoro** [comment]
5 years later, I'm closing this issue. We are still avoiding GPL License, we are still concern about long-term maintenance, and as expected, new modules appeared.
