### ISSUE TITLE
open mp defaults to one core, is that a good idea?

### ISSUE THREAD

**Issue by samuelstjean** [dipy/dipy#861]
In the nlmeans module, if one does not have open mp , it defaults to using only one core. If some problem happens and it is not properly detected, then it also defaults to only one core. The previous behavior was to use everything if possible, and were the user did not have open mp for real then it would of course use only one core. Shouldn't using everything be better instead of stuff being awfully slow?

``` python
def cpu_count():
    if have_openmp:
        return openmp.omp_get_num_procs()
    else:
        return 1
```

**Comment by skoudoro** [comment]
It seems that `cpu_count()` is not used anymore. closing
